// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/live"
	"github.com/zibbp/ganymede/ent/livetitleregex"
)

// LiveTitleRegexCreate is the builder for creating a LiveTitleRegex entity.
type LiveTitleRegexCreate struct {
	config
	mutation *LiveTitleRegexMutation
	hooks    []Hook
}

// SetNegative sets the "negative" field.
func (_c *LiveTitleRegexCreate) SetNegative(v bool) *LiveTitleRegexCreate {
	_c.mutation.SetNegative(v)
	return _c
}

// SetNillableNegative sets the "negative" field if the given value is not nil.
func (_c *LiveTitleRegexCreate) SetNillableNegative(v *bool) *LiveTitleRegexCreate {
	if v != nil {
		_c.SetNegative(*v)
	}
	return _c
}

// SetRegex sets the "regex" field.
func (_c *LiveTitleRegexCreate) SetRegex(v string) *LiveTitleRegexCreate {
	_c.mutation.SetRegex(v)
	return _c
}

// SetApplyToVideos sets the "apply_to_videos" field.
func (_c *LiveTitleRegexCreate) SetApplyToVideos(v bool) *LiveTitleRegexCreate {
	_c.mutation.SetApplyToVideos(v)
	return _c
}

// SetNillableApplyToVideos sets the "apply_to_videos" field if the given value is not nil.
func (_c *LiveTitleRegexCreate) SetNillableApplyToVideos(v *bool) *LiveTitleRegexCreate {
	if v != nil {
		_c.SetApplyToVideos(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LiveTitleRegexCreate) SetID(v uuid.UUID) *LiveTitleRegexCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LiveTitleRegexCreate) SetNillableID(v *uuid.UUID) *LiveTitleRegexCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetLiveID sets the "live" edge to the Live entity by ID.
func (_c *LiveTitleRegexCreate) SetLiveID(id uuid.UUID) *LiveTitleRegexCreate {
	_c.mutation.SetLiveID(id)
	return _c
}

// SetLive sets the "live" edge to the Live entity.
func (_c *LiveTitleRegexCreate) SetLive(v *Live) *LiveTitleRegexCreate {
	return _c.SetLiveID(v.ID)
}

// Mutation returns the LiveTitleRegexMutation object of the builder.
func (_c *LiveTitleRegexCreate) Mutation() *LiveTitleRegexMutation {
	return _c.mutation
}

// Save creates the LiveTitleRegex in the database.
func (_c *LiveTitleRegexCreate) Save(ctx context.Context) (*LiveTitleRegex, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LiveTitleRegexCreate) SaveX(ctx context.Context) *LiveTitleRegex {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LiveTitleRegexCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LiveTitleRegexCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LiveTitleRegexCreate) defaults() {
	if _, ok := _c.mutation.Negative(); !ok {
		v := livetitleregex.DefaultNegative
		_c.mutation.SetNegative(v)
	}
	if _, ok := _c.mutation.ApplyToVideos(); !ok {
		v := livetitleregex.DefaultApplyToVideos
		_c.mutation.SetApplyToVideos(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := livetitleregex.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LiveTitleRegexCreate) check() error {
	if _, ok := _c.mutation.Negative(); !ok {
		return &ValidationError{Name: "negative", err: errors.New(`ent: missing required field "LiveTitleRegex.negative"`)}
	}
	if _, ok := _c.mutation.Regex(); !ok {
		return &ValidationError{Name: "regex", err: errors.New(`ent: missing required field "LiveTitleRegex.regex"`)}
	}
	if _, ok := _c.mutation.ApplyToVideos(); !ok {
		return &ValidationError{Name: "apply_to_videos", err: errors.New(`ent: missing required field "LiveTitleRegex.apply_to_videos"`)}
	}
	if len(_c.mutation.LiveIDs()) == 0 {
		return &ValidationError{Name: "live", err: errors.New(`ent: missing required edge "LiveTitleRegex.live"`)}
	}
	return nil
}

func (_c *LiveTitleRegexCreate) sqlSave(ctx context.Context) (*LiveTitleRegex, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LiveTitleRegexCreate) createSpec() (*LiveTitleRegex, *sqlgraph.CreateSpec) {
	var (
		_node = &LiveTitleRegex{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(livetitleregex.Table, sqlgraph.NewFieldSpec(livetitleregex.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Negative(); ok {
		_spec.SetField(livetitleregex.FieldNegative, field.TypeBool, value)
		_node.Negative = value
	}
	if value, ok := _c.mutation.Regex(); ok {
		_spec.SetField(livetitleregex.FieldRegex, field.TypeString, value)
		_node.Regex = value
	}
	if value, ok := _c.mutation.ApplyToVideos(); ok {
		_spec.SetField(livetitleregex.FieldApplyToVideos, field.TypeBool, value)
		_node.ApplyToVideos = value
	}
	if nodes := _c.mutation.LiveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livetitleregex.LiveTable,
			Columns: []string{livetitleregex.LiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(live.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.live_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LiveTitleRegexCreateBulk is the builder for creating many LiveTitleRegex entities in bulk.
type LiveTitleRegexCreateBulk struct {
	config
	err      error
	builders []*LiveTitleRegexCreate
}

// Save creates the LiveTitleRegex entities in the database.
func (_c *LiveTitleRegexCreateBulk) Save(ctx context.Context) ([]*LiveTitleRegex, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LiveTitleRegex, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LiveTitleRegexMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LiveTitleRegexCreateBulk) SaveX(ctx context.Context) []*LiveTitleRegex {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LiveTitleRegexCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LiveTitleRegexCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
