// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/live"
	"github.com/zibbp/ganymede/ent/livecategory"
)

// LiveCategoryCreate is the builder for creating a LiveCategory entity.
type LiveCategoryCreate struct {
	config
	mutation *LiveCategoryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *LiveCategoryCreate) SetName(v string) *LiveCategoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *LiveCategoryCreate) SetNillableName(v *string) *LiveCategoryCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LiveCategoryCreate) SetID(v uuid.UUID) *LiveCategoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LiveCategoryCreate) SetNillableID(v *uuid.UUID) *LiveCategoryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetLiveID sets the "live" edge to the Live entity by ID.
func (_c *LiveCategoryCreate) SetLiveID(id uuid.UUID) *LiveCategoryCreate {
	_c.mutation.SetLiveID(id)
	return _c
}

// SetLive sets the "live" edge to the Live entity.
func (_c *LiveCategoryCreate) SetLive(v *Live) *LiveCategoryCreate {
	return _c.SetLiveID(v.ID)
}

// Mutation returns the LiveCategoryMutation object of the builder.
func (_c *LiveCategoryCreate) Mutation() *LiveCategoryMutation {
	return _c.mutation
}

// Save creates the LiveCategory in the database.
func (_c *LiveCategoryCreate) Save(ctx context.Context) (*LiveCategory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LiveCategoryCreate) SaveX(ctx context.Context) *LiveCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LiveCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LiveCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LiveCategoryCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := livecategory.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LiveCategoryCreate) check() error {
	if len(_c.mutation.LiveIDs()) == 0 {
		return &ValidationError{Name: "live", err: errors.New(`ent: missing required edge "LiveCategory.live"`)}
	}
	return nil
}

func (_c *LiveCategoryCreate) sqlSave(ctx context.Context) (*LiveCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LiveCategoryCreate) createSpec() (*LiveCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &LiveCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(livecategory.Table, sqlgraph.NewFieldSpec(livecategory.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(livecategory.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if nodes := _c.mutation.LiveIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   livecategory.LiveTable,
			Columns: []string{livecategory.LiveColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(live.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.live_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LiveCategoryCreateBulk is the builder for creating many LiveCategory entities in bulk.
type LiveCategoryCreateBulk struct {
	config
	err      error
	builders []*LiveCategoryCreate
}

// Save creates the LiveCategory entities in the database.
func (_c *LiveCategoryCreateBulk) Save(ctx context.Context) ([]*LiveCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LiveCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LiveCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LiveCategoryCreateBulk) SaveX(ctx context.Context) []*LiveCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LiveCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LiveCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
