// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/mutedsegment"
	"github.com/zibbp/ganymede/ent/vod"
)

// MutedSegmentCreate is the builder for creating a MutedSegment entity.
type MutedSegmentCreate struct {
	config
	mutation *MutedSegmentMutation
	hooks    []Hook
}

// SetStart sets the "start" field.
func (_c *MutedSegmentCreate) SetStart(v int) *MutedSegmentCreate {
	_c.mutation.SetStart(v)
	return _c
}

// SetEnd sets the "end" field.
func (_c *MutedSegmentCreate) SetEnd(v int) *MutedSegmentCreate {
	_c.mutation.SetEnd(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MutedSegmentCreate) SetID(v uuid.UUID) *MutedSegmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MutedSegmentCreate) SetNillableID(v *uuid.UUID) *MutedSegmentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetVodID sets the "vod" edge to the Vod entity by ID.
func (_c *MutedSegmentCreate) SetVodID(id uuid.UUID) *MutedSegmentCreate {
	_c.mutation.SetVodID(id)
	return _c
}

// SetVod sets the "vod" edge to the Vod entity.
func (_c *MutedSegmentCreate) SetVod(v *Vod) *MutedSegmentCreate {
	return _c.SetVodID(v.ID)
}

// Mutation returns the MutedSegmentMutation object of the builder.
func (_c *MutedSegmentCreate) Mutation() *MutedSegmentMutation {
	return _c.mutation
}

// Save creates the MutedSegment in the database.
func (_c *MutedSegmentCreate) Save(ctx context.Context) (*MutedSegment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MutedSegmentCreate) SaveX(ctx context.Context) *MutedSegment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MutedSegmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MutedSegmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MutedSegmentCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := mutedsegment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MutedSegmentCreate) check() error {
	if _, ok := _c.mutation.Start(); !ok {
		return &ValidationError{Name: "start", err: errors.New(`ent: missing required field "MutedSegment.start"`)}
	}
	if _, ok := _c.mutation.End(); !ok {
		return &ValidationError{Name: "end", err: errors.New(`ent: missing required field "MutedSegment.end"`)}
	}
	if len(_c.mutation.VodIDs()) == 0 {
		return &ValidationError{Name: "vod", err: errors.New(`ent: missing required edge "MutedSegment.vod"`)}
	}
	return nil
}

func (_c *MutedSegmentCreate) sqlSave(ctx context.Context) (*MutedSegment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MutedSegmentCreate) createSpec() (*MutedSegment, *sqlgraph.CreateSpec) {
	var (
		_node = &MutedSegment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mutedsegment.Table, sqlgraph.NewFieldSpec(mutedsegment.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Start(); ok {
		_spec.SetField(mutedsegment.FieldStart, field.TypeInt, value)
		_node.Start = value
	}
	if value, ok := _c.mutation.End(); ok {
		_spec.SetField(mutedsegment.FieldEnd, field.TypeInt, value)
		_node.End = value
	}
	if nodes := _c.mutation.VodIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mutedsegment.VodTable,
			Columns: []string{mutedsegment.VodColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.vod_muted_segments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MutedSegmentCreateBulk is the builder for creating many MutedSegment entities in bulk.
type MutedSegmentCreateBulk struct {
	config
	err      error
	builders []*MutedSegmentCreate
}

// Save creates the MutedSegment entities in the database.
func (_c *MutedSegmentCreateBulk) Save(ctx context.Context) ([]*MutedSegment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MutedSegment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MutedSegmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MutedSegmentCreateBulk) SaveX(ctx context.Context) []*MutedSegment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MutedSegmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MutedSegmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
