// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/playlist"
	"github.com/zibbp/ganymede/ent/playlistrule"
	"github.com/zibbp/ganymede/ent/playlistrulegroup"
)

// PlaylistRuleGroupCreate is the builder for creating a PlaylistRuleGroup entity.
type PlaylistRuleGroupCreate struct {
	config
	mutation *PlaylistRuleGroupMutation
	hooks    []Hook
}

// SetOperator sets the "operator" field.
func (_c *PlaylistRuleGroupCreate) SetOperator(v playlistrulegroup.Operator) *PlaylistRuleGroupCreate {
	_c.mutation.SetOperator(v)
	return _c
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_c *PlaylistRuleGroupCreate) SetNillableOperator(v *playlistrulegroup.Operator) *PlaylistRuleGroupCreate {
	if v != nil {
		_c.SetOperator(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *PlaylistRuleGroupCreate) SetPosition(v int) *PlaylistRuleGroupCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *PlaylistRuleGroupCreate) SetNillablePosition(v *int) *PlaylistRuleGroupCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PlaylistRuleGroupCreate) SetID(v uuid.UUID) *PlaylistRuleGroupCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PlaylistRuleGroupCreate) SetNillableID(v *uuid.UUID) *PlaylistRuleGroupCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPlaylistID sets the "playlist" edge to the Playlist entity by ID.
func (_c *PlaylistRuleGroupCreate) SetPlaylistID(id uuid.UUID) *PlaylistRuleGroupCreate {
	_c.mutation.SetPlaylistID(id)
	return _c
}

// SetPlaylist sets the "playlist" edge to the Playlist entity.
func (_c *PlaylistRuleGroupCreate) SetPlaylist(v *Playlist) *PlaylistRuleGroupCreate {
	return _c.SetPlaylistID(v.ID)
}

// AddRuleIDs adds the "rules" edge to the PlaylistRule entity by IDs.
func (_c *PlaylistRuleGroupCreate) AddRuleIDs(ids ...uuid.UUID) *PlaylistRuleGroupCreate {
	_c.mutation.AddRuleIDs(ids...)
	return _c
}

// AddRules adds the "rules" edges to the PlaylistRule entity.
func (_c *PlaylistRuleGroupCreate) AddRules(v ...*PlaylistRule) *PlaylistRuleGroupCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRuleIDs(ids...)
}

// Mutation returns the PlaylistRuleGroupMutation object of the builder.
func (_c *PlaylistRuleGroupCreate) Mutation() *PlaylistRuleGroupMutation {
	return _c.mutation
}

// Save creates the PlaylistRuleGroup in the database.
func (_c *PlaylistRuleGroupCreate) Save(ctx context.Context) (*PlaylistRuleGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlaylistRuleGroupCreate) SaveX(ctx context.Context) *PlaylistRuleGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaylistRuleGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaylistRuleGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlaylistRuleGroupCreate) defaults() {
	if _, ok := _c.mutation.Operator(); !ok {
		v := playlistrulegroup.DefaultOperator
		_c.mutation.SetOperator(v)
	}
	if _, ok := _c.mutation.Position(); !ok {
		v := playlistrulegroup.DefaultPosition
		_c.mutation.SetPosition(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := playlistrulegroup.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlaylistRuleGroupCreate) check() error {
	if _, ok := _c.mutation.Operator(); !ok {
		return &ValidationError{Name: "operator", err: errors.New(`ent: missing required field "PlaylistRuleGroup.operator"`)}
	}
	if v, ok := _c.mutation.Operator(); ok {
		if err := playlistrulegroup.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "PlaylistRuleGroup.operator": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "PlaylistRuleGroup.position"`)}
	}
	if len(_c.mutation.PlaylistIDs()) == 0 {
		return &ValidationError{Name: "playlist", err: errors.New(`ent: missing required edge "PlaylistRuleGroup.playlist"`)}
	}
	return nil
}

func (_c *PlaylistRuleGroupCreate) sqlSave(ctx context.Context) (*PlaylistRuleGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlaylistRuleGroupCreate) createSpec() (*PlaylistRuleGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &PlaylistRuleGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(playlistrulegroup.Table, sqlgraph.NewFieldSpec(playlistrulegroup.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Operator(); ok {
		_spec.SetField(playlistrulegroup.FieldOperator, field.TypeEnum, value)
		_node.Operator = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(playlistrulegroup.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if nodes := _c.mutation.PlaylistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlistrulegroup.PlaylistTable,
			Columns: []string{playlistrulegroup.PlaylistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.playlist_rule_groups = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   playlistrulegroup.RulesTable,
			Columns: []string{playlistrulegroup.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistrule.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlaylistRuleGroupCreateBulk is the builder for creating many PlaylistRuleGroup entities in bulk.
type PlaylistRuleGroupCreateBulk struct {
	config
	err      error
	builders []*PlaylistRuleGroupCreate
}

// Save creates the PlaylistRuleGroup entities in the database.
func (_c *PlaylistRuleGroupCreateBulk) Save(ctx context.Context) ([]*PlaylistRuleGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlaylistRuleGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlaylistRuleGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlaylistRuleGroupCreateBulk) SaveX(ctx context.Context) []*PlaylistRuleGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaylistRuleGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaylistRuleGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
