// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/playback"
	"github.com/zibbp/ganymede/internal/utils"
)

// PlaybackCreate is the builder for creating a Playback entity.
type PlaybackCreate struct {
	config
	mutation *PlaybackMutation
	hooks    []Hook
}

// SetVodID sets the "vod_id" field.
func (_c *PlaybackCreate) SetVodID(v uuid.UUID) *PlaybackCreate {
	_c.mutation.SetVodID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PlaybackCreate) SetUserID(v uuid.UUID) *PlaybackCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTime sets the "time" field.
func (_c *PlaybackCreate) SetTime(v int) *PlaybackCreate {
	_c.mutation.SetTime(v)
	return _c
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_c *PlaybackCreate) SetNillableTime(v *int) *PlaybackCreate {
	if v != nil {
		_c.SetTime(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PlaybackCreate) SetStatus(v utils.PlaybackStatus) *PlaybackCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PlaybackCreate) SetNillableStatus(v *utils.PlaybackStatus) *PlaybackCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlaybackCreate) SetUpdatedAt(v time.Time) *PlaybackCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlaybackCreate) SetNillableUpdatedAt(v *time.Time) *PlaybackCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlaybackCreate) SetCreatedAt(v time.Time) *PlaybackCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlaybackCreate) SetNillableCreatedAt(v *time.Time) *PlaybackCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PlaybackCreate) SetID(v uuid.UUID) *PlaybackCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PlaybackCreate) SetNillableID(v *uuid.UUID) *PlaybackCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PlaybackMutation object of the builder.
func (_c *PlaybackCreate) Mutation() *PlaybackMutation {
	return _c.mutation
}

// Save creates the Playback in the database.
func (_c *PlaybackCreate) Save(ctx context.Context) (*Playback, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlaybackCreate) SaveX(ctx context.Context) *Playback {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaybackCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaybackCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlaybackCreate) defaults() {
	if _, ok := _c.mutation.Time(); !ok {
		v := playback.DefaultTime
		_c.mutation.SetTime(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := playback.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := playback.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := playback.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := playback.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlaybackCreate) check() error {
	if _, ok := _c.mutation.VodID(); !ok {
		return &ValidationError{Name: "vod_id", err: errors.New(`ent: missing required field "Playback.vod_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Playback.user_id"`)}
	}
	if _, ok := _c.mutation.Time(); !ok {
		return &ValidationError{Name: "time", err: errors.New(`ent: missing required field "Playback.time"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := playback.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Playback.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Playback.updated_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Playback.created_at"`)}
	}
	return nil
}

func (_c *PlaybackCreate) sqlSave(ctx context.Context) (*Playback, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlaybackCreate) createSpec() (*Playback, *sqlgraph.CreateSpec) {
	var (
		_node = &Playback{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(playback.Table, sqlgraph.NewFieldSpec(playback.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.VodID(); ok {
		_spec.SetField(playback.FieldVodID, field.TypeUUID, value)
		_node.VodID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(playback.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Time(); ok {
		_spec.SetField(playback.FieldTime, field.TypeInt, value)
		_node.Time = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(playback.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(playback.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(playback.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// PlaybackCreateBulk is the builder for creating many Playback entities in bulk.
type PlaybackCreateBulk struct {
	config
	err      error
	builders []*PlaybackCreate
}

// Save creates the Playback entities in the database.
func (_c *PlaybackCreateBulk) Save(ctx context.Context) ([]*Playback, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Playback, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlaybackMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlaybackCreateBulk) SaveX(ctx context.Context) []*Playback {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaybackCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaybackCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
