// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/queue"
	"github.com/zibbp/ganymede/ent/vod"
	"github.com/zibbp/ganymede/internal/utils"
)

// QueueCreate is the builder for creating a Queue entity.
type QueueCreate struct {
	config
	mutation *QueueMutation
	hooks    []Hook
}

// SetLiveArchive sets the "live_archive" field.
func (_c *QueueCreate) SetLiveArchive(v bool) *QueueCreate {
	_c.mutation.SetLiveArchive(v)
	return _c
}

// SetNillableLiveArchive sets the "live_archive" field if the given value is not nil.
func (_c *QueueCreate) SetNillableLiveArchive(v *bool) *QueueCreate {
	if v != nil {
		_c.SetLiveArchive(*v)
	}
	return _c
}

// SetOnHold sets the "on_hold" field.
func (_c *QueueCreate) SetOnHold(v bool) *QueueCreate {
	_c.mutation.SetOnHold(v)
	return _c
}

// SetNillableOnHold sets the "on_hold" field if the given value is not nil.
func (_c *QueueCreate) SetNillableOnHold(v *bool) *QueueCreate {
	if v != nil {
		_c.SetOnHold(*v)
	}
	return _c
}

// SetVideoProcessing sets the "video_processing" field.
func (_c *QueueCreate) SetVideoProcessing(v bool) *QueueCreate {
	_c.mutation.SetVideoProcessing(v)
	return _c
}

// SetNillableVideoProcessing sets the "video_processing" field if the given value is not nil.
func (_c *QueueCreate) SetNillableVideoProcessing(v *bool) *QueueCreate {
	if v != nil {
		_c.SetVideoProcessing(*v)
	}
	return _c
}

// SetChatProcessing sets the "chat_processing" field.
func (_c *QueueCreate) SetChatProcessing(v bool) *QueueCreate {
	_c.mutation.SetChatProcessing(v)
	return _c
}

// SetNillableChatProcessing sets the "chat_processing" field if the given value is not nil.
func (_c *QueueCreate) SetNillableChatProcessing(v *bool) *QueueCreate {
	if v != nil {
		_c.SetChatProcessing(*v)
	}
	return _c
}

// SetProcessing sets the "processing" field.
func (_c *QueueCreate) SetProcessing(v bool) *QueueCreate {
	_c.mutation.SetProcessing(v)
	return _c
}

// SetNillableProcessing sets the "processing" field if the given value is not nil.
func (_c *QueueCreate) SetNillableProcessing(v *bool) *QueueCreate {
	if v != nil {
		_c.SetProcessing(*v)
	}
	return _c
}

// SetTaskVodCreateFolder sets the "task_vod_create_folder" field.
func (_c *QueueCreate) SetTaskVodCreateFolder(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskVodCreateFolder(v)
	return _c
}

// SetNillableTaskVodCreateFolder sets the "task_vod_create_folder" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskVodCreateFolder(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskVodCreateFolder(*v)
	}
	return _c
}

// SetTaskVodDownloadThumbnail sets the "task_vod_download_thumbnail" field.
func (_c *QueueCreate) SetTaskVodDownloadThumbnail(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskVodDownloadThumbnail(v)
	return _c
}

// SetNillableTaskVodDownloadThumbnail sets the "task_vod_download_thumbnail" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskVodDownloadThumbnail(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskVodDownloadThumbnail(*v)
	}
	return _c
}

// SetTaskVodSaveInfo sets the "task_vod_save_info" field.
func (_c *QueueCreate) SetTaskVodSaveInfo(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskVodSaveInfo(v)
	return _c
}

// SetNillableTaskVodSaveInfo sets the "task_vod_save_info" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskVodSaveInfo(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskVodSaveInfo(*v)
	}
	return _c
}

// SetTaskVideoDownload sets the "task_video_download" field.
func (_c *QueueCreate) SetTaskVideoDownload(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskVideoDownload(v)
	return _c
}

// SetNillableTaskVideoDownload sets the "task_video_download" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskVideoDownload(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskVideoDownload(*v)
	}
	return _c
}

// SetTaskVideoConvert sets the "task_video_convert" field.
func (_c *QueueCreate) SetTaskVideoConvert(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskVideoConvert(v)
	return _c
}

// SetNillableTaskVideoConvert sets the "task_video_convert" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskVideoConvert(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskVideoConvert(*v)
	}
	return _c
}

// SetTaskVideoMove sets the "task_video_move" field.
func (_c *QueueCreate) SetTaskVideoMove(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskVideoMove(v)
	return _c
}

// SetNillableTaskVideoMove sets the "task_video_move" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskVideoMove(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskVideoMove(*v)
	}
	return _c
}

// SetTaskChatDownload sets the "task_chat_download" field.
func (_c *QueueCreate) SetTaskChatDownload(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskChatDownload(v)
	return _c
}

// SetNillableTaskChatDownload sets the "task_chat_download" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskChatDownload(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskChatDownload(*v)
	}
	return _c
}

// SetTaskChatConvert sets the "task_chat_convert" field.
func (_c *QueueCreate) SetTaskChatConvert(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskChatConvert(v)
	return _c
}

// SetNillableTaskChatConvert sets the "task_chat_convert" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskChatConvert(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskChatConvert(*v)
	}
	return _c
}

// SetTaskChatRender sets the "task_chat_render" field.
func (_c *QueueCreate) SetTaskChatRender(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskChatRender(v)
	return _c
}

// SetNillableTaskChatRender sets the "task_chat_render" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskChatRender(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskChatRender(*v)
	}
	return _c
}

// SetTaskChatMove sets the "task_chat_move" field.
func (_c *QueueCreate) SetTaskChatMove(v utils.TaskStatus) *QueueCreate {
	_c.mutation.SetTaskChatMove(v)
	return _c
}

// SetNillableTaskChatMove sets the "task_chat_move" field if the given value is not nil.
func (_c *QueueCreate) SetNillableTaskChatMove(v *utils.TaskStatus) *QueueCreate {
	if v != nil {
		_c.SetTaskChatMove(*v)
	}
	return _c
}

// SetChatStart sets the "chat_start" field.
func (_c *QueueCreate) SetChatStart(v time.Time) *QueueCreate {
	_c.mutation.SetChatStart(v)
	return _c
}

// SetNillableChatStart sets the "chat_start" field if the given value is not nil.
func (_c *QueueCreate) SetNillableChatStart(v *time.Time) *QueueCreate {
	if v != nil {
		_c.SetChatStart(*v)
	}
	return _c
}

// SetArchiveChat sets the "archive_chat" field.
func (_c *QueueCreate) SetArchiveChat(v bool) *QueueCreate {
	_c.mutation.SetArchiveChat(v)
	return _c
}

// SetNillableArchiveChat sets the "archive_chat" field if the given value is not nil.
func (_c *QueueCreate) SetNillableArchiveChat(v *bool) *QueueCreate {
	if v != nil {
		_c.SetArchiveChat(*v)
	}
	return _c
}

// SetRenderChat sets the "render_chat" field.
func (_c *QueueCreate) SetRenderChat(v bool) *QueueCreate {
	_c.mutation.SetRenderChat(v)
	return _c
}

// SetNillableRenderChat sets the "render_chat" field if the given value is not nil.
func (_c *QueueCreate) SetNillableRenderChat(v *bool) *QueueCreate {
	if v != nil {
		_c.SetRenderChat(*v)
	}
	return _c
}

// SetWorkflowID sets the "workflow_id" field.
func (_c *QueueCreate) SetWorkflowID(v string) *QueueCreate {
	_c.mutation.SetWorkflowID(v)
	return _c
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (_c *QueueCreate) SetNillableWorkflowID(v *string) *QueueCreate {
	if v != nil {
		_c.SetWorkflowID(*v)
	}
	return _c
}

// SetWorkflowRunID sets the "workflow_run_id" field.
func (_c *QueueCreate) SetWorkflowRunID(v string) *QueueCreate {
	_c.mutation.SetWorkflowRunID(v)
	return _c
}

// SetNillableWorkflowRunID sets the "workflow_run_id" field if the given value is not nil.
func (_c *QueueCreate) SetNillableWorkflowRunID(v *string) *QueueCreate {
	if v != nil {
		_c.SetWorkflowRunID(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QueueCreate) SetUpdatedAt(v time.Time) *QueueCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QueueCreate) SetNillableUpdatedAt(v *time.Time) *QueueCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QueueCreate) SetCreatedAt(v time.Time) *QueueCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QueueCreate) SetNillableCreatedAt(v *time.Time) *QueueCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QueueCreate) SetID(v uuid.UUID) *QueueCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *QueueCreate) SetNillableID(v *uuid.UUID) *QueueCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetVodID sets the "vod" edge to the Vod entity by ID.
func (_c *QueueCreate) SetVodID(id uuid.UUID) *QueueCreate {
	_c.mutation.SetVodID(id)
	return _c
}

// SetVod sets the "vod" edge to the Vod entity.
func (_c *QueueCreate) SetVod(v *Vod) *QueueCreate {
	return _c.SetVodID(v.ID)
}

// Mutation returns the QueueMutation object of the builder.
func (_c *QueueCreate) Mutation() *QueueMutation {
	return _c.mutation
}

// Save creates the Queue in the database.
func (_c *QueueCreate) Save(ctx context.Context) (*Queue, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QueueCreate) SaveX(ctx context.Context) *Queue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QueueCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QueueCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QueueCreate) defaults() {
	if _, ok := _c.mutation.LiveArchive(); !ok {
		v := queue.DefaultLiveArchive
		_c.mutation.SetLiveArchive(v)
	}
	if _, ok := _c.mutation.OnHold(); !ok {
		v := queue.DefaultOnHold
		_c.mutation.SetOnHold(v)
	}
	if _, ok := _c.mutation.VideoProcessing(); !ok {
		v := queue.DefaultVideoProcessing
		_c.mutation.SetVideoProcessing(v)
	}
	if _, ok := _c.mutation.ChatProcessing(); !ok {
		v := queue.DefaultChatProcessing
		_c.mutation.SetChatProcessing(v)
	}
	if _, ok := _c.mutation.Processing(); !ok {
		v := queue.DefaultProcessing
		_c.mutation.SetProcessing(v)
	}
	if _, ok := _c.mutation.TaskVodCreateFolder(); !ok {
		v := queue.DefaultTaskVodCreateFolder
		_c.mutation.SetTaskVodCreateFolder(v)
	}
	if _, ok := _c.mutation.TaskVodDownloadThumbnail(); !ok {
		v := queue.DefaultTaskVodDownloadThumbnail
		_c.mutation.SetTaskVodDownloadThumbnail(v)
	}
	if _, ok := _c.mutation.TaskVodSaveInfo(); !ok {
		v := queue.DefaultTaskVodSaveInfo
		_c.mutation.SetTaskVodSaveInfo(v)
	}
	if _, ok := _c.mutation.TaskVideoDownload(); !ok {
		v := queue.DefaultTaskVideoDownload
		_c.mutation.SetTaskVideoDownload(v)
	}
	if _, ok := _c.mutation.TaskVideoConvert(); !ok {
		v := queue.DefaultTaskVideoConvert
		_c.mutation.SetTaskVideoConvert(v)
	}
	if _, ok := _c.mutation.TaskVideoMove(); !ok {
		v := queue.DefaultTaskVideoMove
		_c.mutation.SetTaskVideoMove(v)
	}
	if _, ok := _c.mutation.TaskChatDownload(); !ok {
		v := queue.DefaultTaskChatDownload
		_c.mutation.SetTaskChatDownload(v)
	}
	if _, ok := _c.mutation.TaskChatConvert(); !ok {
		v := queue.DefaultTaskChatConvert
		_c.mutation.SetTaskChatConvert(v)
	}
	if _, ok := _c.mutation.TaskChatRender(); !ok {
		v := queue.DefaultTaskChatRender
		_c.mutation.SetTaskChatRender(v)
	}
	if _, ok := _c.mutation.TaskChatMove(); !ok {
		v := queue.DefaultTaskChatMove
		_c.mutation.SetTaskChatMove(v)
	}
	if _, ok := _c.mutation.ArchiveChat(); !ok {
		v := queue.DefaultArchiveChat
		_c.mutation.SetArchiveChat(v)
	}
	if _, ok := _c.mutation.RenderChat(); !ok {
		v := queue.DefaultRenderChat
		_c.mutation.SetRenderChat(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := queue.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := queue.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := queue.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QueueCreate) check() error {
	if _, ok := _c.mutation.LiveArchive(); !ok {
		return &ValidationError{Name: "live_archive", err: errors.New(`ent: missing required field "Queue.live_archive"`)}
	}
	if _, ok := _c.mutation.OnHold(); !ok {
		return &ValidationError{Name: "on_hold", err: errors.New(`ent: missing required field "Queue.on_hold"`)}
	}
	if _, ok := _c.mutation.VideoProcessing(); !ok {
		return &ValidationError{Name: "video_processing", err: errors.New(`ent: missing required field "Queue.video_processing"`)}
	}
	if _, ok := _c.mutation.ChatProcessing(); !ok {
		return &ValidationError{Name: "chat_processing", err: errors.New(`ent: missing required field "Queue.chat_processing"`)}
	}
	if _, ok := _c.mutation.Processing(); !ok {
		return &ValidationError{Name: "processing", err: errors.New(`ent: missing required field "Queue.processing"`)}
	}
	if v, ok := _c.mutation.TaskVodCreateFolder(); ok {
		if err := queue.TaskVodCreateFolderValidator(v); err != nil {
			return &ValidationError{Name: "task_vod_create_folder", err: fmt.Errorf(`ent: validator failed for field "Queue.task_vod_create_folder": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskVodDownloadThumbnail(); ok {
		if err := queue.TaskVodDownloadThumbnailValidator(v); err != nil {
			return &ValidationError{Name: "task_vod_download_thumbnail", err: fmt.Errorf(`ent: validator failed for field "Queue.task_vod_download_thumbnail": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskVodSaveInfo(); ok {
		if err := queue.TaskVodSaveInfoValidator(v); err != nil {
			return &ValidationError{Name: "task_vod_save_info", err: fmt.Errorf(`ent: validator failed for field "Queue.task_vod_save_info": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskVideoDownload(); ok {
		if err := queue.TaskVideoDownloadValidator(v); err != nil {
			return &ValidationError{Name: "task_video_download", err: fmt.Errorf(`ent: validator failed for field "Queue.task_video_download": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskVideoConvert(); ok {
		if err := queue.TaskVideoConvertValidator(v); err != nil {
			return &ValidationError{Name: "task_video_convert", err: fmt.Errorf(`ent: validator failed for field "Queue.task_video_convert": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskVideoMove(); ok {
		if err := queue.TaskVideoMoveValidator(v); err != nil {
			return &ValidationError{Name: "task_video_move", err: fmt.Errorf(`ent: validator failed for field "Queue.task_video_move": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskChatDownload(); ok {
		if err := queue.TaskChatDownloadValidator(v); err != nil {
			return &ValidationError{Name: "task_chat_download", err: fmt.Errorf(`ent: validator failed for field "Queue.task_chat_download": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskChatConvert(); ok {
		if err := queue.TaskChatConvertValidator(v); err != nil {
			return &ValidationError{Name: "task_chat_convert", err: fmt.Errorf(`ent: validator failed for field "Queue.task_chat_convert": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskChatRender(); ok {
		if err := queue.TaskChatRenderValidator(v); err != nil {
			return &ValidationError{Name: "task_chat_render", err: fmt.Errorf(`ent: validator failed for field "Queue.task_chat_render": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaskChatMove(); ok {
		if err := queue.TaskChatMoveValidator(v); err != nil {
			return &ValidationError{Name: "task_chat_move", err: fmt.Errorf(`ent: validator failed for field "Queue.task_chat_move": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Queue.updated_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Queue.created_at"`)}
	}
	if len(_c.mutation.VodIDs()) == 0 {
		return &ValidationError{Name: "vod", err: errors.New(`ent: missing required edge "Queue.vod"`)}
	}
	return nil
}

func (_c *QueueCreate) sqlSave(ctx context.Context) (*Queue, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QueueCreate) createSpec() (*Queue, *sqlgraph.CreateSpec) {
	var (
		_node = &Queue{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(queue.Table, sqlgraph.NewFieldSpec(queue.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.LiveArchive(); ok {
		_spec.SetField(queue.FieldLiveArchive, field.TypeBool, value)
		_node.LiveArchive = value
	}
	if value, ok := _c.mutation.OnHold(); ok {
		_spec.SetField(queue.FieldOnHold, field.TypeBool, value)
		_node.OnHold = value
	}
	if value, ok := _c.mutation.VideoProcessing(); ok {
		_spec.SetField(queue.FieldVideoProcessing, field.TypeBool, value)
		_node.VideoProcessing = value
	}
	if value, ok := _c.mutation.ChatProcessing(); ok {
		_spec.SetField(queue.FieldChatProcessing, field.TypeBool, value)
		_node.ChatProcessing = value
	}
	if value, ok := _c.mutation.Processing(); ok {
		_spec.SetField(queue.FieldProcessing, field.TypeBool, value)
		_node.Processing = value
	}
	if value, ok := _c.mutation.TaskVodCreateFolder(); ok {
		_spec.SetField(queue.FieldTaskVodCreateFolder, field.TypeEnum, value)
		_node.TaskVodCreateFolder = value
	}
	if value, ok := _c.mutation.TaskVodDownloadThumbnail(); ok {
		_spec.SetField(queue.FieldTaskVodDownloadThumbnail, field.TypeEnum, value)
		_node.TaskVodDownloadThumbnail = value
	}
	if value, ok := _c.mutation.TaskVodSaveInfo(); ok {
		_spec.SetField(queue.FieldTaskVodSaveInfo, field.TypeEnum, value)
		_node.TaskVodSaveInfo = value
	}
	if value, ok := _c.mutation.TaskVideoDownload(); ok {
		_spec.SetField(queue.FieldTaskVideoDownload, field.TypeEnum, value)
		_node.TaskVideoDownload = value
	}
	if value, ok := _c.mutation.TaskVideoConvert(); ok {
		_spec.SetField(queue.FieldTaskVideoConvert, field.TypeEnum, value)
		_node.TaskVideoConvert = value
	}
	if value, ok := _c.mutation.TaskVideoMove(); ok {
		_spec.SetField(queue.FieldTaskVideoMove, field.TypeEnum, value)
		_node.TaskVideoMove = value
	}
	if value, ok := _c.mutation.TaskChatDownload(); ok {
		_spec.SetField(queue.FieldTaskChatDownload, field.TypeEnum, value)
		_node.TaskChatDownload = value
	}
	if value, ok := _c.mutation.TaskChatConvert(); ok {
		_spec.SetField(queue.FieldTaskChatConvert, field.TypeEnum, value)
		_node.TaskChatConvert = value
	}
	if value, ok := _c.mutation.TaskChatRender(); ok {
		_spec.SetField(queue.FieldTaskChatRender, field.TypeEnum, value)
		_node.TaskChatRender = value
	}
	if value, ok := _c.mutation.TaskChatMove(); ok {
		_spec.SetField(queue.FieldTaskChatMove, field.TypeEnum, value)
		_node.TaskChatMove = value
	}
	if value, ok := _c.mutation.ChatStart(); ok {
		_spec.SetField(queue.FieldChatStart, field.TypeTime, value)
		_node.ChatStart = value
	}
	if value, ok := _c.mutation.ArchiveChat(); ok {
		_spec.SetField(queue.FieldArchiveChat, field.TypeBool, value)
		_node.ArchiveChat = value
	}
	if value, ok := _c.mutation.RenderChat(); ok {
		_spec.SetField(queue.FieldRenderChat, field.TypeBool, value)
		_node.RenderChat = value
	}
	if value, ok := _c.mutation.WorkflowID(); ok {
		_spec.SetField(queue.FieldWorkflowID, field.TypeString, value)
		_node.WorkflowID = value
	}
	if value, ok := _c.mutation.WorkflowRunID(); ok {
		_spec.SetField(queue.FieldWorkflowRunID, field.TypeString, value)
		_node.WorkflowRunID = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(queue.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(queue.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.VodIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   queue.VodTable,
			Columns: []string{queue.VodColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.vod_queue = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QueueCreateBulk is the builder for creating many Queue entities in bulk.
type QueueCreateBulk struct {
	config
	err      error
	builders []*QueueCreate
}

// Save creates the Queue entities in the database.
func (_c *QueueCreateBulk) Save(ctx context.Context) ([]*Queue, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Queue, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QueueMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QueueCreateBulk) SaveX(ctx context.Context) []*Queue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QueueCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QueueCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
