// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zibbp/ganymede/ent/twitchcategory"
)

// TwitchCategoryCreate is the builder for creating a TwitchCategory entity.
type TwitchCategoryCreate struct {
	config
	mutation *TwitchCategoryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TwitchCategoryCreate) SetName(v string) *TwitchCategoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetBoxArtURL sets the "box_art_url" field.
func (_c *TwitchCategoryCreate) SetBoxArtURL(v string) *TwitchCategoryCreate {
	_c.mutation.SetBoxArtURL(v)
	return _c
}

// SetNillableBoxArtURL sets the "box_art_url" field if the given value is not nil.
func (_c *TwitchCategoryCreate) SetNillableBoxArtURL(v *string) *TwitchCategoryCreate {
	if v != nil {
		_c.SetBoxArtURL(*v)
	}
	return _c
}

// SetIgdbID sets the "igdb_id" field.
func (_c *TwitchCategoryCreate) SetIgdbID(v string) *TwitchCategoryCreate {
	_c.mutation.SetIgdbID(v)
	return _c
}

// SetNillableIgdbID sets the "igdb_id" field if the given value is not nil.
func (_c *TwitchCategoryCreate) SetNillableIgdbID(v *string) *TwitchCategoryCreate {
	if v != nil {
		_c.SetIgdbID(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TwitchCategoryCreate) SetUpdatedAt(v time.Time) *TwitchCategoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TwitchCategoryCreate) SetNillableUpdatedAt(v *time.Time) *TwitchCategoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TwitchCategoryCreate) SetCreatedAt(v time.Time) *TwitchCategoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TwitchCategoryCreate) SetNillableCreatedAt(v *time.Time) *TwitchCategoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TwitchCategoryCreate) SetID(v string) *TwitchCategoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TwitchCategoryMutation object of the builder.
func (_c *TwitchCategoryCreate) Mutation() *TwitchCategoryMutation {
	return _c.mutation
}

// Save creates the TwitchCategory in the database.
func (_c *TwitchCategoryCreate) Save(ctx context.Context) (*TwitchCategory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TwitchCategoryCreate) SaveX(ctx context.Context) *TwitchCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TwitchCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TwitchCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TwitchCategoryCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := twitchcategory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := twitchcategory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TwitchCategoryCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TwitchCategory.name"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TwitchCategory.updated_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TwitchCategory.created_at"`)}
	}
	return nil
}

func (_c *TwitchCategoryCreate) sqlSave(ctx context.Context) (*TwitchCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TwitchCategory.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TwitchCategoryCreate) createSpec() (*TwitchCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &TwitchCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(twitchcategory.Table, sqlgraph.NewFieldSpec(twitchcategory.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(twitchcategory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.BoxArtURL(); ok {
		_spec.SetField(twitchcategory.FieldBoxArtURL, field.TypeString, value)
		_node.BoxArtURL = value
	}
	if value, ok := _c.mutation.IgdbID(); ok {
		_spec.SetField(twitchcategory.FieldIgdbID, field.TypeString, value)
		_node.IgdbID = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(twitchcategory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(twitchcategory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// TwitchCategoryCreateBulk is the builder for creating many TwitchCategory entities in bulk.
type TwitchCategoryCreateBulk struct {
	config
	err      error
	builders []*TwitchCategoryCreate
}

// Save creates the TwitchCategory entities in the database.
func (_c *TwitchCategoryCreateBulk) Save(ctx context.Context) ([]*TwitchCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TwitchCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TwitchCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TwitchCategoryCreateBulk) SaveX(ctx context.Context) []*TwitchCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TwitchCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TwitchCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
