// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/channel"
	"github.com/zibbp/ganymede/ent/chapter"
	"github.com/zibbp/ganymede/ent/multistreaminfo"
	"github.com/zibbp/ganymede/ent/mutedsegment"
	"github.com/zibbp/ganymede/ent/playlist"
	"github.com/zibbp/ganymede/ent/queue"
	"github.com/zibbp/ganymede/ent/vod"
	"github.com/zibbp/ganymede/ent/youtubeupload"
	"github.com/zibbp/ganymede/internal/utils"
)

// VodCreate is the builder for creating a Vod entity.
type VodCreate struct {
	config
	mutation *VodMutation
	hooks    []Hook
}

// SetExtID sets the "ext_id" field.
func (_c *VodCreate) SetExtID(v string) *VodCreate {
	_c.mutation.SetExtID(v)
	return _c
}

// SetClipExtVodID sets the "clip_ext_vod_id" field.
func (_c *VodCreate) SetClipExtVodID(v string) *VodCreate {
	_c.mutation.SetClipExtVodID(v)
	return _c
}

// SetNillableClipExtVodID sets the "clip_ext_vod_id" field if the given value is not nil.
func (_c *VodCreate) SetNillableClipExtVodID(v *string) *VodCreate {
	if v != nil {
		_c.SetClipExtVodID(*v)
	}
	return _c
}

// SetExtStreamID sets the "ext_stream_id" field.
func (_c *VodCreate) SetExtStreamID(v string) *VodCreate {
	_c.mutation.SetExtStreamID(v)
	return _c
}

// SetNillableExtStreamID sets the "ext_stream_id" field if the given value is not nil.
func (_c *VodCreate) SetNillableExtStreamID(v *string) *VodCreate {
	if v != nil {
		_c.SetExtStreamID(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *VodCreate) SetPlatform(v utils.VideoPlatform) *VodCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *VodCreate) SetNillablePlatform(v *utils.VideoPlatform) *VodCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *VodCreate) SetType(v utils.VodType) *VodCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *VodCreate) SetNillableType(v *utils.VodType) *VodCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *VodCreate) SetTitle(v string) *VodCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDuration sets the "duration" field.
func (_c *VodCreate) SetDuration(v int) *VodCreate {
	_c.mutation.SetDuration(v)
	return _c
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_c *VodCreate) SetNillableDuration(v *int) *VodCreate {
	if v != nil {
		_c.SetDuration(*v)
	}
	return _c
}

// SetClipVodOffset sets the "clip_vod_offset" field.
func (_c *VodCreate) SetClipVodOffset(v int) *VodCreate {
	_c.mutation.SetClipVodOffset(v)
	return _c
}

// SetNillableClipVodOffset sets the "clip_vod_offset" field if the given value is not nil.
func (_c *VodCreate) SetNillableClipVodOffset(v *int) *VodCreate {
	if v != nil {
		_c.SetClipVodOffset(*v)
	}
	return _c
}

// SetViews sets the "views" field.
func (_c *VodCreate) SetViews(v int) *VodCreate {
	_c.mutation.SetViews(v)
	return _c
}

// SetNillableViews sets the "views" field if the given value is not nil.
func (_c *VodCreate) SetNillableViews(v *int) *VodCreate {
	if v != nil {
		_c.SetViews(*v)
	}
	return _c
}

// SetResolution sets the "resolution" field.
func (_c *VodCreate) SetResolution(v string) *VodCreate {
	_c.mutation.SetResolution(v)
	return _c
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_c *VodCreate) SetNillableResolution(v *string) *VodCreate {
	if v != nil {
		_c.SetResolution(*v)
	}
	return _c
}

// SetProcessing sets the "processing" field.
func (_c *VodCreate) SetProcessing(v bool) *VodCreate {
	_c.mutation.SetProcessing(v)
	return _c
}

// SetNillableProcessing sets the "processing" field if the given value is not nil.
func (_c *VodCreate) SetNillableProcessing(v *bool) *VodCreate {
	if v != nil {
		_c.SetProcessing(*v)
	}
	return _c
}

// SetThumbnailPath sets the "thumbnail_path" field.
func (_c *VodCreate) SetThumbnailPath(v string) *VodCreate {
	_c.mutation.SetThumbnailPath(v)
	return _c
}

// SetNillableThumbnailPath sets the "thumbnail_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableThumbnailPath(v *string) *VodCreate {
	if v != nil {
		_c.SetThumbnailPath(*v)
	}
	return _c
}

// SetWebThumbnailPath sets the "web_thumbnail_path" field.
func (_c *VodCreate) SetWebThumbnailPath(v string) *VodCreate {
	_c.mutation.SetWebThumbnailPath(v)
	return _c
}

// SetVideoPath sets the "video_path" field.
func (_c *VodCreate) SetVideoPath(v string) *VodCreate {
	_c.mutation.SetVideoPath(v)
	return _c
}

// SetVideoHlsPath sets the "video_hls_path" field.
func (_c *VodCreate) SetVideoHlsPath(v string) *VodCreate {
	_c.mutation.SetVideoHlsPath(v)
	return _c
}

// SetNillableVideoHlsPath sets the "video_hls_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableVideoHlsPath(v *string) *VodCreate {
	if v != nil {
		_c.SetVideoHlsPath(*v)
	}
	return _c
}

// SetChatPath sets the "chat_path" field.
func (_c *VodCreate) SetChatPath(v string) *VodCreate {
	_c.mutation.SetChatPath(v)
	return _c
}

// SetNillableChatPath sets the "chat_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableChatPath(v *string) *VodCreate {
	if v != nil {
		_c.SetChatPath(*v)
	}
	return _c
}

// SetLiveChatPath sets the "live_chat_path" field.
func (_c *VodCreate) SetLiveChatPath(v string) *VodCreate {
	_c.mutation.SetLiveChatPath(v)
	return _c
}

// SetNillableLiveChatPath sets the "live_chat_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableLiveChatPath(v *string) *VodCreate {
	if v != nil {
		_c.SetLiveChatPath(*v)
	}
	return _c
}

// SetLiveChatConvertPath sets the "live_chat_convert_path" field.
func (_c *VodCreate) SetLiveChatConvertPath(v string) *VodCreate {
	_c.mutation.SetLiveChatConvertPath(v)
	return _c
}

// SetNillableLiveChatConvertPath sets the "live_chat_convert_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableLiveChatConvertPath(v *string) *VodCreate {
	if v != nil {
		_c.SetLiveChatConvertPath(*v)
	}
	return _c
}

// SetChatVideoPath sets the "chat_video_path" field.
func (_c *VodCreate) SetChatVideoPath(v string) *VodCreate {
	_c.mutation.SetChatVideoPath(v)
	return _c
}

// SetNillableChatVideoPath sets the "chat_video_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableChatVideoPath(v *string) *VodCreate {
	if v != nil {
		_c.SetChatVideoPath(*v)
	}
	return _c
}

// SetInfoPath sets the "info_path" field.
func (_c *VodCreate) SetInfoPath(v string) *VodCreate {
	_c.mutation.SetInfoPath(v)
	return _c
}

// SetNillableInfoPath sets the "info_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableInfoPath(v *string) *VodCreate {
	if v != nil {
		_c.SetInfoPath(*v)
	}
	return _c
}

// SetCaptionPath sets the "caption_path" field.
func (_c *VodCreate) SetCaptionPath(v string) *VodCreate {
	_c.mutation.SetCaptionPath(v)
	return _c
}

// SetNillableCaptionPath sets the "caption_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableCaptionPath(v *string) *VodCreate {
	if v != nil {
		_c.SetCaptionPath(*v)
	}
	return _c
}

// SetFolderName sets the "folder_name" field.
func (_c *VodCreate) SetFolderName(v string) *VodCreate {
	_c.mutation.SetFolderName(v)
	return _c
}

// SetNillableFolderName sets the "folder_name" field if the given value is not nil.
func (_c *VodCreate) SetNillableFolderName(v *string) *VodCreate {
	if v != nil {
		_c.SetFolderName(*v)
	}
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *VodCreate) SetFileName(v string) *VodCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_c *VodCreate) SetNillableFileName(v *string) *VodCreate {
	if v != nil {
		_c.SetFileName(*v)
	}
	return _c
}

// SetTmpVideoDownloadPath sets the "tmp_video_download_path" field.
func (_c *VodCreate) SetTmpVideoDownloadPath(v string) *VodCreate {
	_c.mutation.SetTmpVideoDownloadPath(v)
	return _c
}

// SetNillableTmpVideoDownloadPath sets the "tmp_video_download_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableTmpVideoDownloadPath(v *string) *VodCreate {
	if v != nil {
		_c.SetTmpVideoDownloadPath(*v)
	}
	return _c
}

// SetTmpVideoConvertPath sets the "tmp_video_convert_path" field.
func (_c *VodCreate) SetTmpVideoConvertPath(v string) *VodCreate {
	_c.mutation.SetTmpVideoConvertPath(v)
	return _c
}

// SetNillableTmpVideoConvertPath sets the "tmp_video_convert_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableTmpVideoConvertPath(v *string) *VodCreate {
	if v != nil {
		_c.SetTmpVideoConvertPath(*v)
	}
	return _c
}

// SetTmpChatDownloadPath sets the "tmp_chat_download_path" field.
func (_c *VodCreate) SetTmpChatDownloadPath(v string) *VodCreate {
	_c.mutation.SetTmpChatDownloadPath(v)
	return _c
}

// SetNillableTmpChatDownloadPath sets the "tmp_chat_download_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableTmpChatDownloadPath(v *string) *VodCreate {
	if v != nil {
		_c.SetTmpChatDownloadPath(*v)
	}
	return _c
}

// SetTmpLiveChatDownloadPath sets the "tmp_live_chat_download_path" field.
func (_c *VodCreate) SetTmpLiveChatDownloadPath(v string) *VodCreate {
	_c.mutation.SetTmpLiveChatDownloadPath(v)
	return _c
}

// SetNillableTmpLiveChatDownloadPath sets the "tmp_live_chat_download_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableTmpLiveChatDownloadPath(v *string) *VodCreate {
	if v != nil {
		_c.SetTmpLiveChatDownloadPath(*v)
	}
	return _c
}

// SetTmpLiveChatConvertPath sets the "tmp_live_chat_convert_path" field.
func (_c *VodCreate) SetTmpLiveChatConvertPath(v string) *VodCreate {
	_c.mutation.SetTmpLiveChatConvertPath(v)
	return _c
}

// SetNillableTmpLiveChatConvertPath sets the "tmp_live_chat_convert_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableTmpLiveChatConvertPath(v *string) *VodCreate {
	if v != nil {
		_c.SetTmpLiveChatConvertPath(*v)
	}
	return _c
}

// SetTmpChatRenderPath sets the "tmp_chat_render_path" field.
func (_c *VodCreate) SetTmpChatRenderPath(v string) *VodCreate {
	_c.mutation.SetTmpChatRenderPath(v)
	return _c
}

// SetNillableTmpChatRenderPath sets the "tmp_chat_render_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableTmpChatRenderPath(v *string) *VodCreate {
	if v != nil {
		_c.SetTmpChatRenderPath(*v)
	}
	return _c
}

// SetTmpVideoHlsPath sets the "tmp_video_hls_path" field.
func (_c *VodCreate) SetTmpVideoHlsPath(v string) *VodCreate {
	_c.mutation.SetTmpVideoHlsPath(v)
	return _c
}

// SetNillableTmpVideoHlsPath sets the "tmp_video_hls_path" field if the given value is not nil.
func (_c *VodCreate) SetNillableTmpVideoHlsPath(v *string) *VodCreate {
	if v != nil {
		_c.SetTmpVideoHlsPath(*v)
	}
	return _c
}

// SetLocked sets the "locked" field.
func (_c *VodCreate) SetLocked(v bool) *VodCreate {
	_c.mutation.SetLocked(v)
	return _c
}

// SetNillableLocked sets the "locked" field if the given value is not nil.
func (_c *VodCreate) SetNillableLocked(v *bool) *VodCreate {
	if v != nil {
		_c.SetLocked(*v)
	}
	return _c
}

// SetLocalViews sets the "local_views" field.
func (_c *VodCreate) SetLocalViews(v int) *VodCreate {
	_c.mutation.SetLocalViews(v)
	return _c
}

// SetNillableLocalViews sets the "local_views" field if the given value is not nil.
func (_c *VodCreate) SetNillableLocalViews(v *int) *VodCreate {
	if v != nil {
		_c.SetLocalViews(*v)
	}
	return _c
}

// SetSpriteThumbnailsEnabled sets the "sprite_thumbnails_enabled" field.
func (_c *VodCreate) SetSpriteThumbnailsEnabled(v bool) *VodCreate {
	_c.mutation.SetSpriteThumbnailsEnabled(v)
	return _c
}

// SetNillableSpriteThumbnailsEnabled sets the "sprite_thumbnails_enabled" field if the given value is not nil.
func (_c *VodCreate) SetNillableSpriteThumbnailsEnabled(v *bool) *VodCreate {
	if v != nil {
		_c.SetSpriteThumbnailsEnabled(*v)
	}
	return _c
}

// SetSpriteThumbnailsImages sets the "sprite_thumbnails_images" field.
func (_c *VodCreate) SetSpriteThumbnailsImages(v []string) *VodCreate {
	_c.mutation.SetSpriteThumbnailsImages(v)
	return _c
}

// SetSpriteThumbnailsInterval sets the "sprite_thumbnails_interval" field.
func (_c *VodCreate) SetSpriteThumbnailsInterval(v int) *VodCreate {
	_c.mutation.SetSpriteThumbnailsInterval(v)
	return _c
}

// SetNillableSpriteThumbnailsInterval sets the "sprite_thumbnails_interval" field if the given value is not nil.
func (_c *VodCreate) SetNillableSpriteThumbnailsInterval(v *int) *VodCreate {
	if v != nil {
		_c.SetSpriteThumbnailsInterval(*v)
	}
	return _c
}

// SetSpriteThumbnailsWidth sets the "sprite_thumbnails_width" field.
func (_c *VodCreate) SetSpriteThumbnailsWidth(v int) *VodCreate {
	_c.mutation.SetSpriteThumbnailsWidth(v)
	return _c
}

// SetNillableSpriteThumbnailsWidth sets the "sprite_thumbnails_width" field if the given value is not nil.
func (_c *VodCreate) SetNillableSpriteThumbnailsWidth(v *int) *VodCreate {
	if v != nil {
		_c.SetSpriteThumbnailsWidth(*v)
	}
	return _c
}

// SetSpriteThumbnailsHeight sets the "sprite_thumbnails_height" field.
func (_c *VodCreate) SetSpriteThumbnailsHeight(v int) *VodCreate {
	_c.mutation.SetSpriteThumbnailsHeight(v)
	return _c
}

// SetNillableSpriteThumbnailsHeight sets the "sprite_thumbnails_height" field if the given value is not nil.
func (_c *VodCreate) SetNillableSpriteThumbnailsHeight(v *int) *VodCreate {
	if v != nil {
		_c.SetSpriteThumbnailsHeight(*v)
	}
	return _c
}

// SetSpriteThumbnailsRows sets the "sprite_thumbnails_rows" field.
func (_c *VodCreate) SetSpriteThumbnailsRows(v int) *VodCreate {
	_c.mutation.SetSpriteThumbnailsRows(v)
	return _c
}

// SetNillableSpriteThumbnailsRows sets the "sprite_thumbnails_rows" field if the given value is not nil.
func (_c *VodCreate) SetNillableSpriteThumbnailsRows(v *int) *VodCreate {
	if v != nil {
		_c.SetSpriteThumbnailsRows(*v)
	}
	return _c
}

// SetSpriteThumbnailsColumns sets the "sprite_thumbnails_columns" field.
func (_c *VodCreate) SetSpriteThumbnailsColumns(v int) *VodCreate {
	_c.mutation.SetSpriteThumbnailsColumns(v)
	return _c
}

// SetNillableSpriteThumbnailsColumns sets the "sprite_thumbnails_columns" field if the given value is not nil.
func (_c *VodCreate) SetNillableSpriteThumbnailsColumns(v *int) *VodCreate {
	if v != nil {
		_c.SetSpriteThumbnailsColumns(*v)
	}
	return _c
}

// SetStorageSizeBytes sets the "storage_size_bytes" field.
func (_c *VodCreate) SetStorageSizeBytes(v int64) *VodCreate {
	_c.mutation.SetStorageSizeBytes(v)
	return _c
}

// SetNillableStorageSizeBytes sets the "storage_size_bytes" field if the given value is not nil.
func (_c *VodCreate) SetNillableStorageSizeBytes(v *int64) *VodCreate {
	if v != nil {
		_c.SetStorageSizeBytes(*v)
	}
	return _c
}

// SetStreamedAt sets the "streamed_at" field.
func (_c *VodCreate) SetStreamedAt(v time.Time) *VodCreate {
	_c.mutation.SetStreamedAt(v)
	return _c
}

// SetNillableStreamedAt sets the "streamed_at" field if the given value is not nil.
func (_c *VodCreate) SetNillableStreamedAt(v *time.Time) *VodCreate {
	if v != nil {
		_c.SetStreamedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VodCreate) SetUpdatedAt(v time.Time) *VodCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VodCreate) SetNillableUpdatedAt(v *time.Time) *VodCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VodCreate) SetCreatedAt(v time.Time) *VodCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VodCreate) SetNillableCreatedAt(v *time.Time) *VodCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VodCreate) SetID(v uuid.UUID) *VodCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *VodCreate) SetNillableID(v *uuid.UUID) *VodCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_c *VodCreate) SetChannelID(id uuid.UUID) *VodCreate {
	_c.mutation.SetChannelID(id)
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *VodCreate) SetChannel(v *Channel) *VodCreate {
	return _c.SetChannelID(v.ID)
}

// SetQueueID sets the "queue" edge to the Queue entity by ID.
func (_c *VodCreate) SetQueueID(id uuid.UUID) *VodCreate {
	_c.mutation.SetQueueID(id)
	return _c
}

// SetNillableQueueID sets the "queue" edge to the Queue entity by ID if the given value is not nil.
func (_c *VodCreate) SetNillableQueueID(id *uuid.UUID) *VodCreate {
	if id != nil {
		_c = _c.SetQueueID(*id)
	}
	return _c
}

// SetQueue sets the "queue" edge to the Queue entity.
func (_c *VodCreate) SetQueue(v *Queue) *VodCreate {
	return _c.SetQueueID(v.ID)
}

// AddPlaylistIDs adds the "playlists" edge to the Playlist entity by IDs.
func (_c *VodCreate) AddPlaylistIDs(ids ...uuid.UUID) *VodCreate {
	_c.mutation.AddPlaylistIDs(ids...)
	return _c
}

// AddPlaylists adds the "playlists" edges to the Playlist entity.
func (_c *VodCreate) AddPlaylists(v ...*Playlist) *VodCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPlaylistIDs(ids...)
}

// AddChapterIDs adds the "chapters" edge to the Chapter entity by IDs.
func (_c *VodCreate) AddChapterIDs(ids ...uuid.UUID) *VodCreate {
	_c.mutation.AddChapterIDs(ids...)
	return _c
}

// AddChapters adds the "chapters" edges to the Chapter entity.
func (_c *VodCreate) AddChapters(v ...*Chapter) *VodCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChapterIDs(ids...)
}

// AddMutedSegmentIDs adds the "muted_segments" edge to the MutedSegment entity by IDs.
func (_c *VodCreate) AddMutedSegmentIDs(ids ...uuid.UUID) *VodCreate {
	_c.mutation.AddMutedSegmentIDs(ids...)
	return _c
}

// AddMutedSegments adds the "muted_segments" edges to the MutedSegment entity.
func (_c *VodCreate) AddMutedSegments(v ...*MutedSegment) *VodCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMutedSegmentIDs(ids...)
}

// AddMultistreamInfoIDs adds the "multistream_info" edge to the MultistreamInfo entity by IDs.
func (_c *VodCreate) AddMultistreamInfoIDs(ids ...int) *VodCreate {
	_c.mutation.AddMultistreamInfoIDs(ids...)
	return _c
}

// AddMultistreamInfo adds the "multistream_info" edges to the MultistreamInfo entity.
func (_c *VodCreate) AddMultistreamInfo(v ...*MultistreamInfo) *VodCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMultistreamInfoIDs(ids...)
}

// SetYoutubeUploadID sets the "youtube_upload" edge to the YoutubeUpload entity by ID.
func (_c *VodCreate) SetYoutubeUploadID(id uuid.UUID) *VodCreate {
	_c.mutation.SetYoutubeUploadID(id)
	return _c
}

// SetNillableYoutubeUploadID sets the "youtube_upload" edge to the YoutubeUpload entity by ID if the given value is not nil.
func (_c *VodCreate) SetNillableYoutubeUploadID(id *uuid.UUID) *VodCreate {
	if id != nil {
		_c = _c.SetYoutubeUploadID(*id)
	}
	return _c
}

// SetYoutubeUpload sets the "youtube_upload" edge to the YoutubeUpload entity.
func (_c *VodCreate) SetYoutubeUpload(v *YoutubeUpload) *VodCreate {
	return _c.SetYoutubeUploadID(v.ID)
}

// Mutation returns the VodMutation object of the builder.
func (_c *VodCreate) Mutation() *VodMutation {
	return _c.mutation
}

// Save creates the Vod in the database.
func (_c *VodCreate) Save(ctx context.Context) (*Vod, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VodCreate) SaveX(ctx context.Context) *Vod {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VodCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VodCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VodCreate) defaults() {
	if _, ok := _c.mutation.Platform(); !ok {
		v := vod.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := vod.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Duration(); !ok {
		v := vod.DefaultDuration
		_c.mutation.SetDuration(v)
	}
	if _, ok := _c.mutation.Views(); !ok {
		v := vod.DefaultViews
		_c.mutation.SetViews(v)
	}
	if _, ok := _c.mutation.Processing(); !ok {
		v := vod.DefaultProcessing
		_c.mutation.SetProcessing(v)
	}
	if _, ok := _c.mutation.Locked(); !ok {
		v := vod.DefaultLocked
		_c.mutation.SetLocked(v)
	}
	if _, ok := _c.mutation.LocalViews(); !ok {
		v := vod.DefaultLocalViews
		_c.mutation.SetLocalViews(v)
	}
	if _, ok := _c.mutation.SpriteThumbnailsEnabled(); !ok {
		v := vod.DefaultSpriteThumbnailsEnabled
		_c.mutation.SetSpriteThumbnailsEnabled(v)
	}
	if _, ok := _c.mutation.StorageSizeBytes(); !ok {
		v := vod.DefaultStorageSizeBytes
		_c.mutation.SetStorageSizeBytes(v)
	}
	if _, ok := _c.mutation.StreamedAt(); !ok {
		v := vod.DefaultStreamedAt()
		_c.mutation.SetStreamedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := vod.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := vod.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := vod.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VodCreate) check() error {
	if _, ok := _c.mutation.ExtID(); !ok {
		return &ValidationError{Name: "ext_id", err: errors.New(`ent: missing required field "Vod.ext_id"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Vod.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := vod.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Vod.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Vod.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := vod.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Vod.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Vod.title"`)}
	}
	if _, ok := _c.mutation.Duration(); !ok {
		return &ValidationError{Name: "duration", err: errors.New(`ent: missing required field "Vod.duration"`)}
	}
	if _, ok := _c.mutation.Views(); !ok {
		return &ValidationError{Name: "views", err: errors.New(`ent: missing required field "Vod.views"`)}
	}
	if _, ok := _c.mutation.Processing(); !ok {
		return &ValidationError{Name: "processing", err: errors.New(`ent: missing required field "Vod.processing"`)}
	}
	if _, ok := _c.mutation.WebThumbnailPath(); !ok {
		return &ValidationError{Name: "web_thumbnail_path", err: errors.New(`ent: missing required field "Vod.web_thumbnail_path"`)}
	}
	if _, ok := _c.mutation.VideoPath(); !ok {
		return &ValidationError{Name: "video_path", err: errors.New(`ent: missing required field "Vod.video_path"`)}
	}
	if _, ok := _c.mutation.Locked(); !ok {
		return &ValidationError{Name: "locked", err: errors.New(`ent: missing required field "Vod.locked"`)}
	}
	if _, ok := _c.mutation.LocalViews(); !ok {
		return &ValidationError{Name: "local_views", err: errors.New(`ent: missing required field "Vod.local_views"`)}
	}
	if _, ok := _c.mutation.SpriteThumbnailsEnabled(); !ok {
		return &ValidationError{Name: "sprite_thumbnails_enabled", err: errors.New(`ent: missing required field "Vod.sprite_thumbnails_enabled"`)}
	}
	if _, ok := _c.mutation.StorageSizeBytes(); !ok {
		return &ValidationError{Name: "storage_size_bytes", err: errors.New(`ent: missing required field "Vod.storage_size_bytes"`)}
	}
	if _, ok := _c.mutation.StreamedAt(); !ok {
		return &ValidationError{Name: "streamed_at", err: errors.New(`ent: missing required field "Vod.streamed_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Vod.updated_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Vod.created_at"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "Vod.channel"`)}
	}
	return nil
}

func (_c *VodCreate) sqlSave(ctx context.Context) (*Vod, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VodCreate) createSpec() (*Vod, *sqlgraph.CreateSpec) {
	var (
		_node = &Vod{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vod.Table, sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ExtID(); ok {
		_spec.SetField(vod.FieldExtID, field.TypeString, value)
		_node.ExtID = value
	}
	if value, ok := _c.mutation.ClipExtVodID(); ok {
		_spec.SetField(vod.FieldClipExtVodID, field.TypeString, value)
		_node.ClipExtVodID = value
	}
	if value, ok := _c.mutation.ExtStreamID(); ok {
		_spec.SetField(vod.FieldExtStreamID, field.TypeString, value)
		_node.ExtStreamID = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(vod.FieldPlatform, field.TypeEnum, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(vod.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(vod.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Duration(); ok {
		_spec.SetField(vod.FieldDuration, field.TypeInt, value)
		_node.Duration = value
	}
	if value, ok := _c.mutation.ClipVodOffset(); ok {
		_spec.SetField(vod.FieldClipVodOffset, field.TypeInt, value)
		_node.ClipVodOffset = value
	}
	if value, ok := _c.mutation.Views(); ok {
		_spec.SetField(vod.FieldViews, field.TypeInt, value)
		_node.Views = value
	}
	if value, ok := _c.mutation.Resolution(); ok {
		_spec.SetField(vod.FieldResolution, field.TypeString, value)
		_node.Resolution = value
	}
	if value, ok := _c.mutation.Processing(); ok {
		_spec.SetField(vod.FieldProcessing, field.TypeBool, value)
		_node.Processing = value
	}
	if value, ok := _c.mutation.ThumbnailPath(); ok {
		_spec.SetField(vod.FieldThumbnailPath, field.TypeString, value)
		_node.ThumbnailPath = value
	}
	if value, ok := _c.mutation.WebThumbnailPath(); ok {
		_spec.SetField(vod.FieldWebThumbnailPath, field.TypeString, value)
		_node.WebThumbnailPath = value
	}
	if value, ok := _c.mutation.VideoPath(); ok {
		_spec.SetField(vod.FieldVideoPath, field.TypeString, value)
		_node.VideoPath = value
	}
	if value, ok := _c.mutation.VideoHlsPath(); ok {
		_spec.SetField(vod.FieldVideoHlsPath, field.TypeString, value)
		_node.VideoHlsPath = value
	}
	if value, ok := _c.mutation.ChatPath(); ok {
		_spec.SetField(vod.FieldChatPath, field.TypeString, value)
		_node.ChatPath = value
	}
	if value, ok := _c.mutation.LiveChatPath(); ok {
		_spec.SetField(vod.FieldLiveChatPath, field.TypeString, value)
		_node.LiveChatPath = value
	}
	if value, ok := _c.mutation.LiveChatConvertPath(); ok {
		_spec.SetField(vod.FieldLiveChatConvertPath, field.TypeString, value)
		_node.LiveChatConvertPath = value
	}
	if value, ok := _c.mutation.ChatVideoPath(); ok {
		_spec.SetField(vod.FieldChatVideoPath, field.TypeString, value)
		_node.ChatVideoPath = value
	}
	if value, ok := _c.mutation.InfoPath(); ok {
		_spec.SetField(vod.FieldInfoPath, field.TypeString, value)
		_node.InfoPath = value
	}
	if value, ok := _c.mutation.CaptionPath(); ok {
		_spec.SetField(vod.FieldCaptionPath, field.TypeString, value)
		_node.CaptionPath = value
	}
	if value, ok := _c.mutation.FolderName(); ok {
		_spec.SetField(vod.FieldFolderName, field.TypeString, value)
		_node.FolderName = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(vod.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.TmpVideoDownloadPath(); ok {
		_spec.SetField(vod.FieldTmpVideoDownloadPath, field.TypeString, value)
		_node.TmpVideoDownloadPath = value
	}
	if value, ok := _c.mutation.TmpVideoConvertPath(); ok {
		_spec.SetField(vod.FieldTmpVideoConvertPath, field.TypeString, value)
		_node.TmpVideoConvertPath = value
	}
	if value, ok := _c.mutation.TmpChatDownloadPath(); ok {
		_spec.SetField(vod.FieldTmpChatDownloadPath, field.TypeString, value)
		_node.TmpChatDownloadPath = value
	}
	if value, ok := _c.mutation.TmpLiveChatDownloadPath(); ok {
		_spec.SetField(vod.FieldTmpLiveChatDownloadPath, field.TypeString, value)
		_node.TmpLiveChatDownloadPath = value
	}
	if value, ok := _c.mutation.TmpLiveChatConvertPath(); ok {
		_spec.SetField(vod.FieldTmpLiveChatConvertPath, field.TypeString, value)
		_node.TmpLiveChatConvertPath = value
	}
	if value, ok := _c.mutation.TmpChatRenderPath(); ok {
		_spec.SetField(vod.FieldTmpChatRenderPath, field.TypeString, value)
		_node.TmpChatRenderPath = value
	}
	if value, ok := _c.mutation.TmpVideoHlsPath(); ok {
		_spec.SetField(vod.FieldTmpVideoHlsPath, field.TypeString, value)
		_node.TmpVideoHlsPath = value
	}
	if value, ok := _c.mutation.Locked(); ok {
		_spec.SetField(vod.FieldLocked, field.TypeBool, value)
		_node.Locked = value
	}
	if value, ok := _c.mutation.LocalViews(); ok {
		_spec.SetField(vod.FieldLocalViews, field.TypeInt, value)
		_node.LocalViews = value
	}
	if value, ok := _c.mutation.SpriteThumbnailsEnabled(); ok {
		_spec.SetField(vod.FieldSpriteThumbnailsEnabled, field.TypeBool, value)
		_node.SpriteThumbnailsEnabled = value
	}
	if value, ok := _c.mutation.SpriteThumbnailsImages(); ok {
		_spec.SetField(vod.FieldSpriteThumbnailsImages, field.TypeJSON, value)
		_node.SpriteThumbnailsImages = value
	}
	if value, ok := _c.mutation.SpriteThumbnailsInterval(); ok {
		_spec.SetField(vod.FieldSpriteThumbnailsInterval, field.TypeInt, value)
		_node.SpriteThumbnailsInterval = value
	}
	if value, ok := _c.mutation.SpriteThumbnailsWidth(); ok {
		_spec.SetField(vod.FieldSpriteThumbnailsWidth, field.TypeInt, value)
		_node.SpriteThumbnailsWidth = value
	}
	if value, ok := _c.mutation.SpriteThumbnailsHeight(); ok {
		_spec.SetField(vod.FieldSpriteThumbnailsHeight, field.TypeInt, value)
		_node.SpriteThumbnailsHeight = value
	}
	if value, ok := _c.mutation.SpriteThumbnailsRows(); ok {
		_spec.SetField(vod.FieldSpriteThumbnailsRows, field.TypeInt, value)
		_node.SpriteThumbnailsRows = value
	}
	if value, ok := _c.mutation.SpriteThumbnailsColumns(); ok {
		_spec.SetField(vod.FieldSpriteThumbnailsColumns, field.TypeInt, value)
		_node.SpriteThumbnailsColumns = value
	}
	if value, ok := _c.mutation.StorageSizeBytes(); ok {
		_spec.SetField(vod.FieldStorageSizeBytes, field.TypeInt64, value)
		_node.StorageSizeBytes = value
	}
	if value, ok := _c.mutation.StreamedAt(); ok {
		_spec.SetField(vod.FieldStreamedAt, field.TypeTime, value)
		_node.StreamedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(vod.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vod.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vod.ChannelTable,
			Columns: []string{vod.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.channel_vods = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.QueueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   vod.QueueTable,
			Columns: []string{vod.QueueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(queue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlaylistsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   vod.PlaylistsTable,
			Columns: vod.PlaylistsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChaptersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vod.ChaptersTable,
			Columns: []string{vod.ChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chapter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MutedSegmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vod.MutedSegmentsTable,
			Columns: []string{vod.MutedSegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mutedsegment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MultistreamInfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   vod.MultistreamInfoTable,
			Columns: []string{vod.MultistreamInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(multistreaminfo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.YoutubeUploadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   vod.YoutubeUploadTable,
			Columns: []string{vod.YoutubeUploadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(youtubeupload.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VodCreateBulk is the builder for creating many Vod entities in bulk.
type VodCreateBulk struct {
	config
	err      error
	builders []*VodCreate
}

// Save creates the Vod entities in the database.
func (_c *VodCreateBulk) Save(ctx context.Context) ([]*Vod, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Vod, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VodMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VodCreateBulk) SaveX(ctx context.Context) []*Vod {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VodCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VodCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
