// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/channel"
	"github.com/zibbp/ganymede/ent/predicate"
	"github.com/zibbp/ganymede/ent/youtubeconfig"
	"github.com/zibbp/ganymede/ent/youtubeplaylistmapping"
)

// YoutubeConfigUpdate is the builder for updating YoutubeConfig entities.
type YoutubeConfigUpdate struct {
	config
	hooks    []Hook
	mutation *YoutubeConfigMutation
}

// Where appends a list predicates to the YoutubeConfigUpdate builder.
func (_u *YoutubeConfigUpdate) Where(ps ...predicate.YoutubeConfig) *YoutubeConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUploadEnabled sets the "upload_enabled" field.
func (_u *YoutubeConfigUpdate) SetUploadEnabled(v bool) *YoutubeConfigUpdate {
	_u.mutation.SetUploadEnabled(v)
	return _u
}

// SetNillableUploadEnabled sets the "upload_enabled" field if the given value is not nil.
func (_u *YoutubeConfigUpdate) SetNillableUploadEnabled(v *bool) *YoutubeConfigUpdate {
	if v != nil {
		_u.SetUploadEnabled(*v)
	}
	return _u
}

// SetDefaultPrivacy sets the "default_privacy" field.
func (_u *YoutubeConfigUpdate) SetDefaultPrivacy(v string) *YoutubeConfigUpdate {
	_u.mutation.SetDefaultPrivacy(v)
	return _u
}

// SetNillableDefaultPrivacy sets the "default_privacy" field if the given value is not nil.
func (_u *YoutubeConfigUpdate) SetNillableDefaultPrivacy(v *string) *YoutubeConfigUpdate {
	if v != nil {
		_u.SetDefaultPrivacy(*v)
	}
	return _u
}

// SetDefaultCategoryID sets the "default_category_id" field.
func (_u *YoutubeConfigUpdate) SetDefaultCategoryID(v string) *YoutubeConfigUpdate {
	_u.mutation.SetDefaultCategoryID(v)
	return _u
}

// SetNillableDefaultCategoryID sets the "default_category_id" field if the given value is not nil.
func (_u *YoutubeConfigUpdate) SetNillableDefaultCategoryID(v *string) *YoutubeConfigUpdate {
	if v != nil {
		_u.SetDefaultCategoryID(*v)
	}
	return _u
}

// SetDescriptionTemplate sets the "description_template" field.
func (_u *YoutubeConfigUpdate) SetDescriptionTemplate(v string) *YoutubeConfigUpdate {
	_u.mutation.SetDescriptionTemplate(v)
	return _u
}

// SetNillableDescriptionTemplate sets the "description_template" field if the given value is not nil.
func (_u *YoutubeConfigUpdate) SetNillableDescriptionTemplate(v *string) *YoutubeConfigUpdate {
	if v != nil {
		_u.SetDescriptionTemplate(*v)
	}
	return _u
}

// ClearDescriptionTemplate clears the value of the "description_template" field.
func (_u *YoutubeConfigUpdate) ClearDescriptionTemplate() *YoutubeConfigUpdate {
	_u.mutation.ClearDescriptionTemplate()
	return _u
}

// SetTitleTemplate sets the "title_template" field.
func (_u *YoutubeConfigUpdate) SetTitleTemplate(v string) *YoutubeConfigUpdate {
	_u.mutation.SetTitleTemplate(v)
	return _u
}

// SetNillableTitleTemplate sets the "title_template" field if the given value is not nil.
func (_u *YoutubeConfigUpdate) SetNillableTitleTemplate(v *string) *YoutubeConfigUpdate {
	if v != nil {
		_u.SetTitleTemplate(*v)
	}
	return _u
}

// ClearTitleTemplate clears the value of the "title_template" field.
func (_u *YoutubeConfigUpdate) ClearTitleTemplate() *YoutubeConfigUpdate {
	_u.mutation.ClearTitleTemplate()
	return _u
}

// SetTags sets the "tags" field.
func (_u *YoutubeConfigUpdate) SetTags(v []string) *YoutubeConfigUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *YoutubeConfigUpdate) AppendTags(v []string) *YoutubeConfigUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *YoutubeConfigUpdate) ClearTags() *YoutubeConfigUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetAddChapters sets the "add_chapters" field.
func (_u *YoutubeConfigUpdate) SetAddChapters(v bool) *YoutubeConfigUpdate {
	_u.mutation.SetAddChapters(v)
	return _u
}

// SetNillableAddChapters sets the "add_chapters" field if the given value is not nil.
func (_u *YoutubeConfigUpdate) SetNillableAddChapters(v *bool) *YoutubeConfigUpdate {
	if v != nil {
		_u.SetAddChapters(*v)
	}
	return _u
}

// SetNotifySubscribers sets the "notify_subscribers" field.
func (_u *YoutubeConfigUpdate) SetNotifySubscribers(v bool) *YoutubeConfigUpdate {
	_u.mutation.SetNotifySubscribers(v)
	return _u
}

// SetNillableNotifySubscribers sets the "notify_subscribers" field if the given value is not nil.
func (_u *YoutubeConfigUpdate) SetNillableNotifySubscribers(v *bool) *YoutubeConfigUpdate {
	if v != nil {
		_u.SetNotifySubscribers(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *YoutubeConfigUpdate) SetUpdatedAt(v time.Time) *YoutubeConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_u *YoutubeConfigUpdate) SetChannelID(id uuid.UUID) *YoutubeConfigUpdate {
	_u.mutation.SetChannelID(id)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *YoutubeConfigUpdate) SetChannel(v *Channel) *YoutubeConfigUpdate {
	return _u.SetChannelID(v.ID)
}

// AddPlaylistMappingIDs adds the "playlist_mappings" edge to the YoutubePlaylistMapping entity by IDs.
func (_u *YoutubeConfigUpdate) AddPlaylistMappingIDs(ids ...uuid.UUID) *YoutubeConfigUpdate {
	_u.mutation.AddPlaylistMappingIDs(ids...)
	return _u
}

// AddPlaylistMappings adds the "playlist_mappings" edges to the YoutubePlaylistMapping entity.
func (_u *YoutubeConfigUpdate) AddPlaylistMappings(v ...*YoutubePlaylistMapping) *YoutubeConfigUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlaylistMappingIDs(ids...)
}

// Mutation returns the YoutubeConfigMutation object of the builder.
func (_u *YoutubeConfigUpdate) Mutation() *YoutubeConfigMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *YoutubeConfigUpdate) ClearChannel() *YoutubeConfigUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearPlaylistMappings clears all "playlist_mappings" edges to the YoutubePlaylistMapping entity.
func (_u *YoutubeConfigUpdate) ClearPlaylistMappings() *YoutubeConfigUpdate {
	_u.mutation.ClearPlaylistMappings()
	return _u
}

// RemovePlaylistMappingIDs removes the "playlist_mappings" edge to YoutubePlaylistMapping entities by IDs.
func (_u *YoutubeConfigUpdate) RemovePlaylistMappingIDs(ids ...uuid.UUID) *YoutubeConfigUpdate {
	_u.mutation.RemovePlaylistMappingIDs(ids...)
	return _u
}

// RemovePlaylistMappings removes "playlist_mappings" edges to YoutubePlaylistMapping entities.
func (_u *YoutubeConfigUpdate) RemovePlaylistMappings(v ...*YoutubePlaylistMapping) *YoutubeConfigUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlaylistMappingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *YoutubeConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *YoutubeConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *YoutubeConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *YoutubeConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *YoutubeConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := youtubeconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *YoutubeConfigUpdate) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "YoutubeConfig.channel"`)
	}
	return nil
}

func (_u *YoutubeConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(youtubeconfig.Table, youtubeconfig.Columns, sqlgraph.NewFieldSpec(youtubeconfig.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UploadEnabled(); ok {
		_spec.SetField(youtubeconfig.FieldUploadEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultPrivacy(); ok {
		_spec.SetField(youtubeconfig.FieldDefaultPrivacy, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultCategoryID(); ok {
		_spec.SetField(youtubeconfig.FieldDefaultCategoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DescriptionTemplate(); ok {
		_spec.SetField(youtubeconfig.FieldDescriptionTemplate, field.TypeString, value)
	}
	if _u.mutation.DescriptionTemplateCleared() {
		_spec.ClearField(youtubeconfig.FieldDescriptionTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.TitleTemplate(); ok {
		_spec.SetField(youtubeconfig.FieldTitleTemplate, field.TypeString, value)
	}
	if _u.mutation.TitleTemplateCleared() {
		_spec.ClearField(youtubeconfig.FieldTitleTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(youtubeconfig.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, youtubeconfig.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(youtubeconfig.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.AddChapters(); ok {
		_spec.SetField(youtubeconfig.FieldAddChapters, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifySubscribers(); ok {
		_spec.SetField(youtubeconfig.FieldNotifySubscribers, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(youtubeconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   youtubeconfig.ChannelTable,
			Columns: []string{youtubeconfig.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   youtubeconfig.ChannelTable,
			Columns: []string{youtubeconfig.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlaylistMappingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   youtubeconfig.PlaylistMappingsTable,
			Columns: []string{youtubeconfig.PlaylistMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(youtubeplaylistmapping.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlaylistMappingsIDs(); len(nodes) > 0 && !_u.mutation.PlaylistMappingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   youtubeconfig.PlaylistMappingsTable,
			Columns: []string{youtubeconfig.PlaylistMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(youtubeplaylistmapping.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlaylistMappingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   youtubeconfig.PlaylistMappingsTable,
			Columns: []string{youtubeconfig.PlaylistMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(youtubeplaylistmapping.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{youtubeconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// YoutubeConfigUpdateOne is the builder for updating a single YoutubeConfig entity.
type YoutubeConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *YoutubeConfigMutation
}

// SetUploadEnabled sets the "upload_enabled" field.
func (_u *YoutubeConfigUpdateOne) SetUploadEnabled(v bool) *YoutubeConfigUpdateOne {
	_u.mutation.SetUploadEnabled(v)
	return _u
}

// SetNillableUploadEnabled sets the "upload_enabled" field if the given value is not nil.
func (_u *YoutubeConfigUpdateOne) SetNillableUploadEnabled(v *bool) *YoutubeConfigUpdateOne {
	if v != nil {
		_u.SetUploadEnabled(*v)
	}
	return _u
}

// SetDefaultPrivacy sets the "default_privacy" field.
func (_u *YoutubeConfigUpdateOne) SetDefaultPrivacy(v string) *YoutubeConfigUpdateOne {
	_u.mutation.SetDefaultPrivacy(v)
	return _u
}

// SetNillableDefaultPrivacy sets the "default_privacy" field if the given value is not nil.
func (_u *YoutubeConfigUpdateOne) SetNillableDefaultPrivacy(v *string) *YoutubeConfigUpdateOne {
	if v != nil {
		_u.SetDefaultPrivacy(*v)
	}
	return _u
}

// SetDefaultCategoryID sets the "default_category_id" field.
func (_u *YoutubeConfigUpdateOne) SetDefaultCategoryID(v string) *YoutubeConfigUpdateOne {
	_u.mutation.SetDefaultCategoryID(v)
	return _u
}

// SetNillableDefaultCategoryID sets the "default_category_id" field if the given value is not nil.
func (_u *YoutubeConfigUpdateOne) SetNillableDefaultCategoryID(v *string) *YoutubeConfigUpdateOne {
	if v != nil {
		_u.SetDefaultCategoryID(*v)
	}
	return _u
}

// SetDescriptionTemplate sets the "description_template" field.
func (_u *YoutubeConfigUpdateOne) SetDescriptionTemplate(v string) *YoutubeConfigUpdateOne {
	_u.mutation.SetDescriptionTemplate(v)
	return _u
}

// SetNillableDescriptionTemplate sets the "description_template" field if the given value is not nil.
func (_u *YoutubeConfigUpdateOne) SetNillableDescriptionTemplate(v *string) *YoutubeConfigUpdateOne {
	if v != nil {
		_u.SetDescriptionTemplate(*v)
	}
	return _u
}

// ClearDescriptionTemplate clears the value of the "description_template" field.
func (_u *YoutubeConfigUpdateOne) ClearDescriptionTemplate() *YoutubeConfigUpdateOne {
	_u.mutation.ClearDescriptionTemplate()
	return _u
}

// SetTitleTemplate sets the "title_template" field.
func (_u *YoutubeConfigUpdateOne) SetTitleTemplate(v string) *YoutubeConfigUpdateOne {
	_u.mutation.SetTitleTemplate(v)
	return _u
}

// SetNillableTitleTemplate sets the "title_template" field if the given value is not nil.
func (_u *YoutubeConfigUpdateOne) SetNillableTitleTemplate(v *string) *YoutubeConfigUpdateOne {
	if v != nil {
		_u.SetTitleTemplate(*v)
	}
	return _u
}

// ClearTitleTemplate clears the value of the "title_template" field.
func (_u *YoutubeConfigUpdateOne) ClearTitleTemplate() *YoutubeConfigUpdateOne {
	_u.mutation.ClearTitleTemplate()
	return _u
}

// SetTags sets the "tags" field.
func (_u *YoutubeConfigUpdateOne) SetTags(v []string) *YoutubeConfigUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *YoutubeConfigUpdateOne) AppendTags(v []string) *YoutubeConfigUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *YoutubeConfigUpdateOne) ClearTags() *YoutubeConfigUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetAddChapters sets the "add_chapters" field.
func (_u *YoutubeConfigUpdateOne) SetAddChapters(v bool) *YoutubeConfigUpdateOne {
	_u.mutation.SetAddChapters(v)
	return _u
}

// SetNillableAddChapters sets the "add_chapters" field if the given value is not nil.
func (_u *YoutubeConfigUpdateOne) SetNillableAddChapters(v *bool) *YoutubeConfigUpdateOne {
	if v != nil {
		_u.SetAddChapters(*v)
	}
	return _u
}

// SetNotifySubscribers sets the "notify_subscribers" field.
func (_u *YoutubeConfigUpdateOne) SetNotifySubscribers(v bool) *YoutubeConfigUpdateOne {
	_u.mutation.SetNotifySubscribers(v)
	return _u
}

// SetNillableNotifySubscribers sets the "notify_subscribers" field if the given value is not nil.
func (_u *YoutubeConfigUpdateOne) SetNillableNotifySubscribers(v *bool) *YoutubeConfigUpdateOne {
	if v != nil {
		_u.SetNotifySubscribers(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *YoutubeConfigUpdateOne) SetUpdatedAt(v time.Time) *YoutubeConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_u *YoutubeConfigUpdateOne) SetChannelID(id uuid.UUID) *YoutubeConfigUpdateOne {
	_u.mutation.SetChannelID(id)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *YoutubeConfigUpdateOne) SetChannel(v *Channel) *YoutubeConfigUpdateOne {
	return _u.SetChannelID(v.ID)
}

// AddPlaylistMappingIDs adds the "playlist_mappings" edge to the YoutubePlaylistMapping entity by IDs.
func (_u *YoutubeConfigUpdateOne) AddPlaylistMappingIDs(ids ...uuid.UUID) *YoutubeConfigUpdateOne {
	_u.mutation.AddPlaylistMappingIDs(ids...)
	return _u
}

// AddPlaylistMappings adds the "playlist_mappings" edges to the YoutubePlaylistMapping entity.
func (_u *YoutubeConfigUpdateOne) AddPlaylistMappings(v ...*YoutubePlaylistMapping) *YoutubeConfigUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlaylistMappingIDs(ids...)
}

// Mutation returns the YoutubeConfigMutation object of the builder.
func (_u *YoutubeConfigUpdateOne) Mutation() *YoutubeConfigMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *YoutubeConfigUpdateOne) ClearChannel() *YoutubeConfigUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearPlaylistMappings clears all "playlist_mappings" edges to the YoutubePlaylistMapping entity.
func (_u *YoutubeConfigUpdateOne) ClearPlaylistMappings() *YoutubeConfigUpdateOne {
	_u.mutation.ClearPlaylistMappings()
	return _u
}

// RemovePlaylistMappingIDs removes the "playlist_mappings" edge to YoutubePlaylistMapping entities by IDs.
func (_u *YoutubeConfigUpdateOne) RemovePlaylistMappingIDs(ids ...uuid.UUID) *YoutubeConfigUpdateOne {
	_u.mutation.RemovePlaylistMappingIDs(ids...)
	return _u
}

// RemovePlaylistMappings removes "playlist_mappings" edges to YoutubePlaylistMapping entities.
func (_u *YoutubeConfigUpdateOne) RemovePlaylistMappings(v ...*YoutubePlaylistMapping) *YoutubeConfigUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlaylistMappingIDs(ids...)
}

// Where appends a list predicates to the YoutubeConfigUpdate builder.
func (_u *YoutubeConfigUpdateOne) Where(ps ...predicate.YoutubeConfig) *YoutubeConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *YoutubeConfigUpdateOne) Select(field string, fields ...string) *YoutubeConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated YoutubeConfig entity.
func (_u *YoutubeConfigUpdateOne) Save(ctx context.Context) (*YoutubeConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *YoutubeConfigUpdateOne) SaveX(ctx context.Context) *YoutubeConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *YoutubeConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *YoutubeConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *YoutubeConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := youtubeconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *YoutubeConfigUpdateOne) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "YoutubeConfig.channel"`)
	}
	return nil
}

func (_u *YoutubeConfigUpdateOne) sqlSave(ctx context.Context) (_node *YoutubeConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(youtubeconfig.Table, youtubeconfig.Columns, sqlgraph.NewFieldSpec(youtubeconfig.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "YoutubeConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, youtubeconfig.FieldID)
		for _, f := range fields {
			if !youtubeconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != youtubeconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UploadEnabled(); ok {
		_spec.SetField(youtubeconfig.FieldUploadEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultPrivacy(); ok {
		_spec.SetField(youtubeconfig.FieldDefaultPrivacy, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultCategoryID(); ok {
		_spec.SetField(youtubeconfig.FieldDefaultCategoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DescriptionTemplate(); ok {
		_spec.SetField(youtubeconfig.FieldDescriptionTemplate, field.TypeString, value)
	}
	if _u.mutation.DescriptionTemplateCleared() {
		_spec.ClearField(youtubeconfig.FieldDescriptionTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.TitleTemplate(); ok {
		_spec.SetField(youtubeconfig.FieldTitleTemplate, field.TypeString, value)
	}
	if _u.mutation.TitleTemplateCleared() {
		_spec.ClearField(youtubeconfig.FieldTitleTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(youtubeconfig.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, youtubeconfig.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(youtubeconfig.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.AddChapters(); ok {
		_spec.SetField(youtubeconfig.FieldAddChapters, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotifySubscribers(); ok {
		_spec.SetField(youtubeconfig.FieldNotifySubscribers, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(youtubeconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   youtubeconfig.ChannelTable,
			Columns: []string{youtubeconfig.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   youtubeconfig.ChannelTable,
			Columns: []string{youtubeconfig.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlaylistMappingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   youtubeconfig.PlaylistMappingsTable,
			Columns: []string{youtubeconfig.PlaylistMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(youtubeplaylistmapping.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlaylistMappingsIDs(); len(nodes) > 0 && !_u.mutation.PlaylistMappingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   youtubeconfig.PlaylistMappingsTable,
			Columns: []string{youtubeconfig.PlaylistMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(youtubeplaylistmapping.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlaylistMappingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   youtubeconfig.PlaylistMappingsTable,
			Columns: []string{youtubeconfig.PlaylistMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(youtubeplaylistmapping.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &YoutubeConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{youtubeconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
