// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/predicate"
	"github.com/zibbp/ganymede/ent/vod"
	"github.com/zibbp/ganymede/ent/youtubeupload"
)

// YoutubeUploadUpdate is the builder for updating YoutubeUpload entities.
type YoutubeUploadUpdate struct {
	config
	hooks    []Hook
	mutation *YoutubeUploadMutation
}

// Where appends a list predicates to the YoutubeUploadUpdate builder.
func (_u *YoutubeUploadUpdate) Where(ps ...predicate.YoutubeUpload) *YoutubeUploadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetYoutubeVideoID sets the "youtube_video_id" field.
func (_u *YoutubeUploadUpdate) SetYoutubeVideoID(v string) *YoutubeUploadUpdate {
	_u.mutation.SetYoutubeVideoID(v)
	return _u
}

// SetNillableYoutubeVideoID sets the "youtube_video_id" field if the given value is not nil.
func (_u *YoutubeUploadUpdate) SetNillableYoutubeVideoID(v *string) *YoutubeUploadUpdate {
	if v != nil {
		_u.SetYoutubeVideoID(*v)
	}
	return _u
}

// ClearYoutubeVideoID clears the value of the "youtube_video_id" field.
func (_u *YoutubeUploadUpdate) ClearYoutubeVideoID() *YoutubeUploadUpdate {
	_u.mutation.ClearYoutubeVideoID()
	return _u
}

// SetYoutubeURL sets the "youtube_url" field.
func (_u *YoutubeUploadUpdate) SetYoutubeURL(v string) *YoutubeUploadUpdate {
	_u.mutation.SetYoutubeURL(v)
	return _u
}

// SetNillableYoutubeURL sets the "youtube_url" field if the given value is not nil.
func (_u *YoutubeUploadUpdate) SetNillableYoutubeURL(v *string) *YoutubeUploadUpdate {
	if v != nil {
		_u.SetYoutubeURL(*v)
	}
	return _u
}

// ClearYoutubeURL clears the value of the "youtube_url" field.
func (_u *YoutubeUploadUpdate) ClearYoutubeURL() *YoutubeUploadUpdate {
	_u.mutation.ClearYoutubeURL()
	return _u
}

// SetStatus sets the "status" field.
func (_u *YoutubeUploadUpdate) SetStatus(v string) *YoutubeUploadUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *YoutubeUploadUpdate) SetNillableStatus(v *string) *YoutubeUploadUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *YoutubeUploadUpdate) SetErrorMessage(v string) *YoutubeUploadUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *YoutubeUploadUpdate) SetNillableErrorMessage(v *string) *YoutubeUploadUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *YoutubeUploadUpdate) ClearErrorMessage() *YoutubeUploadUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *YoutubeUploadUpdate) SetRetryCount(v int) *YoutubeUploadUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *YoutubeUploadUpdate) SetNillableRetryCount(v *int) *YoutubeUploadUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *YoutubeUploadUpdate) AddRetryCount(v int) *YoutubeUploadUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetUploadedAt sets the "uploaded_at" field.
func (_u *YoutubeUploadUpdate) SetUploadedAt(v time.Time) *YoutubeUploadUpdate {
	_u.mutation.SetUploadedAt(v)
	return _u
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (_u *YoutubeUploadUpdate) SetNillableUploadedAt(v *time.Time) *YoutubeUploadUpdate {
	if v != nil {
		_u.SetUploadedAt(*v)
	}
	return _u
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (_u *YoutubeUploadUpdate) ClearUploadedAt() *YoutubeUploadUpdate {
	_u.mutation.ClearUploadedAt()
	return _u
}

// SetPlaylistIds sets the "playlist_ids" field.
func (_u *YoutubeUploadUpdate) SetPlaylistIds(v []string) *YoutubeUploadUpdate {
	_u.mutation.SetPlaylistIds(v)
	return _u
}

// AppendPlaylistIds appends value to the "playlist_ids" field.
func (_u *YoutubeUploadUpdate) AppendPlaylistIds(v []string) *YoutubeUploadUpdate {
	_u.mutation.AppendPlaylistIds(v)
	return _u
}

// ClearPlaylistIds clears the value of the "playlist_ids" field.
func (_u *YoutubeUploadUpdate) ClearPlaylistIds() *YoutubeUploadUpdate {
	_u.mutation.ClearPlaylistIds()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *YoutubeUploadUpdate) SetUpdatedAt(v time.Time) *YoutubeUploadUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetVodID sets the "vod" edge to the Vod entity by ID.
func (_u *YoutubeUploadUpdate) SetVodID(id uuid.UUID) *YoutubeUploadUpdate {
	_u.mutation.SetVodID(id)
	return _u
}

// SetVod sets the "vod" edge to the Vod entity.
func (_u *YoutubeUploadUpdate) SetVod(v *Vod) *YoutubeUploadUpdate {
	return _u.SetVodID(v.ID)
}

// Mutation returns the YoutubeUploadMutation object of the builder.
func (_u *YoutubeUploadUpdate) Mutation() *YoutubeUploadMutation {
	return _u.mutation
}

// ClearVod clears the "vod" edge to the Vod entity.
func (_u *YoutubeUploadUpdate) ClearVod() *YoutubeUploadUpdate {
	_u.mutation.ClearVod()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *YoutubeUploadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *YoutubeUploadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *YoutubeUploadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *YoutubeUploadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *YoutubeUploadUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := youtubeupload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *YoutubeUploadUpdate) check() error {
	if _u.mutation.VodCleared() && len(_u.mutation.VodIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "YoutubeUpload.vod"`)
	}
	return nil
}

func (_u *YoutubeUploadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(youtubeupload.Table, youtubeupload.Columns, sqlgraph.NewFieldSpec(youtubeupload.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.YoutubeVideoID(); ok {
		_spec.SetField(youtubeupload.FieldYoutubeVideoID, field.TypeString, value)
	}
	if _u.mutation.YoutubeVideoIDCleared() {
		_spec.ClearField(youtubeupload.FieldYoutubeVideoID, field.TypeString)
	}
	if value, ok := _u.mutation.YoutubeURL(); ok {
		_spec.SetField(youtubeupload.FieldYoutubeURL, field.TypeString, value)
	}
	if _u.mutation.YoutubeURLCleared() {
		_spec.ClearField(youtubeupload.FieldYoutubeURL, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(youtubeupload.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(youtubeupload.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(youtubeupload.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(youtubeupload.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(youtubeupload.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UploadedAt(); ok {
		_spec.SetField(youtubeupload.FieldUploadedAt, field.TypeTime, value)
	}
	if _u.mutation.UploadedAtCleared() {
		_spec.ClearField(youtubeupload.FieldUploadedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PlaylistIds(); ok {
		_spec.SetField(youtubeupload.FieldPlaylistIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlaylistIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, youtubeupload.FieldPlaylistIds, value)
		})
	}
	if _u.mutation.PlaylistIdsCleared() {
		_spec.ClearField(youtubeupload.FieldPlaylistIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(youtubeupload.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.VodCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   youtubeupload.VodTable,
			Columns: []string{youtubeupload.VodColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VodIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   youtubeupload.VodTable,
			Columns: []string{youtubeupload.VodColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{youtubeupload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// YoutubeUploadUpdateOne is the builder for updating a single YoutubeUpload entity.
type YoutubeUploadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *YoutubeUploadMutation
}

// SetYoutubeVideoID sets the "youtube_video_id" field.
func (_u *YoutubeUploadUpdateOne) SetYoutubeVideoID(v string) *YoutubeUploadUpdateOne {
	_u.mutation.SetYoutubeVideoID(v)
	return _u
}

// SetNillableYoutubeVideoID sets the "youtube_video_id" field if the given value is not nil.
func (_u *YoutubeUploadUpdateOne) SetNillableYoutubeVideoID(v *string) *YoutubeUploadUpdateOne {
	if v != nil {
		_u.SetYoutubeVideoID(*v)
	}
	return _u
}

// ClearYoutubeVideoID clears the value of the "youtube_video_id" field.
func (_u *YoutubeUploadUpdateOne) ClearYoutubeVideoID() *YoutubeUploadUpdateOne {
	_u.mutation.ClearYoutubeVideoID()
	return _u
}

// SetYoutubeURL sets the "youtube_url" field.
func (_u *YoutubeUploadUpdateOne) SetYoutubeURL(v string) *YoutubeUploadUpdateOne {
	_u.mutation.SetYoutubeURL(v)
	return _u
}

// SetNillableYoutubeURL sets the "youtube_url" field if the given value is not nil.
func (_u *YoutubeUploadUpdateOne) SetNillableYoutubeURL(v *string) *YoutubeUploadUpdateOne {
	if v != nil {
		_u.SetYoutubeURL(*v)
	}
	return _u
}

// ClearYoutubeURL clears the value of the "youtube_url" field.
func (_u *YoutubeUploadUpdateOne) ClearYoutubeURL() *YoutubeUploadUpdateOne {
	_u.mutation.ClearYoutubeURL()
	return _u
}

// SetStatus sets the "status" field.
func (_u *YoutubeUploadUpdateOne) SetStatus(v string) *YoutubeUploadUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *YoutubeUploadUpdateOne) SetNillableStatus(v *string) *YoutubeUploadUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *YoutubeUploadUpdateOne) SetErrorMessage(v string) *YoutubeUploadUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *YoutubeUploadUpdateOne) SetNillableErrorMessage(v *string) *YoutubeUploadUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *YoutubeUploadUpdateOne) ClearErrorMessage() *YoutubeUploadUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *YoutubeUploadUpdateOne) SetRetryCount(v int) *YoutubeUploadUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *YoutubeUploadUpdateOne) SetNillableRetryCount(v *int) *YoutubeUploadUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *YoutubeUploadUpdateOne) AddRetryCount(v int) *YoutubeUploadUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetUploadedAt sets the "uploaded_at" field.
func (_u *YoutubeUploadUpdateOne) SetUploadedAt(v time.Time) *YoutubeUploadUpdateOne {
	_u.mutation.SetUploadedAt(v)
	return _u
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (_u *YoutubeUploadUpdateOne) SetNillableUploadedAt(v *time.Time) *YoutubeUploadUpdateOne {
	if v != nil {
		_u.SetUploadedAt(*v)
	}
	return _u
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (_u *YoutubeUploadUpdateOne) ClearUploadedAt() *YoutubeUploadUpdateOne {
	_u.mutation.ClearUploadedAt()
	return _u
}

// SetPlaylistIds sets the "playlist_ids" field.
func (_u *YoutubeUploadUpdateOne) SetPlaylistIds(v []string) *YoutubeUploadUpdateOne {
	_u.mutation.SetPlaylistIds(v)
	return _u
}

// AppendPlaylistIds appends value to the "playlist_ids" field.
func (_u *YoutubeUploadUpdateOne) AppendPlaylistIds(v []string) *YoutubeUploadUpdateOne {
	_u.mutation.AppendPlaylistIds(v)
	return _u
}

// ClearPlaylistIds clears the value of the "playlist_ids" field.
func (_u *YoutubeUploadUpdateOne) ClearPlaylistIds() *YoutubeUploadUpdateOne {
	_u.mutation.ClearPlaylistIds()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *YoutubeUploadUpdateOne) SetUpdatedAt(v time.Time) *YoutubeUploadUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetVodID sets the "vod" edge to the Vod entity by ID.
func (_u *YoutubeUploadUpdateOne) SetVodID(id uuid.UUID) *YoutubeUploadUpdateOne {
	_u.mutation.SetVodID(id)
	return _u
}

// SetVod sets the "vod" edge to the Vod entity.
func (_u *YoutubeUploadUpdateOne) SetVod(v *Vod) *YoutubeUploadUpdateOne {
	return _u.SetVodID(v.ID)
}

// Mutation returns the YoutubeUploadMutation object of the builder.
func (_u *YoutubeUploadUpdateOne) Mutation() *YoutubeUploadMutation {
	return _u.mutation
}

// ClearVod clears the "vod" edge to the Vod entity.
func (_u *YoutubeUploadUpdateOne) ClearVod() *YoutubeUploadUpdateOne {
	_u.mutation.ClearVod()
	return _u
}

// Where appends a list predicates to the YoutubeUploadUpdate builder.
func (_u *YoutubeUploadUpdateOne) Where(ps ...predicate.YoutubeUpload) *YoutubeUploadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *YoutubeUploadUpdateOne) Select(field string, fields ...string) *YoutubeUploadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated YoutubeUpload entity.
func (_u *YoutubeUploadUpdateOne) Save(ctx context.Context) (*YoutubeUpload, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *YoutubeUploadUpdateOne) SaveX(ctx context.Context) *YoutubeUpload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *YoutubeUploadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *YoutubeUploadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *YoutubeUploadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := youtubeupload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *YoutubeUploadUpdateOne) check() error {
	if _u.mutation.VodCleared() && len(_u.mutation.VodIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "YoutubeUpload.vod"`)
	}
	return nil
}

func (_u *YoutubeUploadUpdateOne) sqlSave(ctx context.Context) (_node *YoutubeUpload, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(youtubeupload.Table, youtubeupload.Columns, sqlgraph.NewFieldSpec(youtubeupload.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "YoutubeUpload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, youtubeupload.FieldID)
		for _, f := range fields {
			if !youtubeupload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != youtubeupload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.YoutubeVideoID(); ok {
		_spec.SetField(youtubeupload.FieldYoutubeVideoID, field.TypeString, value)
	}
	if _u.mutation.YoutubeVideoIDCleared() {
		_spec.ClearField(youtubeupload.FieldYoutubeVideoID, field.TypeString)
	}
	if value, ok := _u.mutation.YoutubeURL(); ok {
		_spec.SetField(youtubeupload.FieldYoutubeURL, field.TypeString, value)
	}
	if _u.mutation.YoutubeURLCleared() {
		_spec.ClearField(youtubeupload.FieldYoutubeURL, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(youtubeupload.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(youtubeupload.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(youtubeupload.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(youtubeupload.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(youtubeupload.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UploadedAt(); ok {
		_spec.SetField(youtubeupload.FieldUploadedAt, field.TypeTime, value)
	}
	if _u.mutation.UploadedAtCleared() {
		_spec.ClearField(youtubeupload.FieldUploadedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PlaylistIds(); ok {
		_spec.SetField(youtubeupload.FieldPlaylistIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlaylistIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, youtubeupload.FieldPlaylistIds, value)
		})
	}
	if _u.mutation.PlaylistIdsCleared() {
		_spec.ClearField(youtubeupload.FieldPlaylistIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(youtubeupload.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.VodCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   youtubeupload.VodTable,
			Columns: []string{youtubeupload.VodColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VodIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   youtubeupload.VodTable,
			Columns: []string{youtubeupload.VodColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &YoutubeUpload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{youtubeupload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
