// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/youtubeconfig"
	"github.com/zibbp/ganymede/ent/youtubeplaylistmapping"
)

// YoutubePlaylistMappingCreate is the builder for creating a YoutubePlaylistMapping entity.
type YoutubePlaylistMappingCreate struct {
	config
	mutation *YoutubePlaylistMappingMutation
	hooks    []Hook
}

// SetGameCategory sets the "game_category" field.
func (_c *YoutubePlaylistMappingCreate) SetGameCategory(v string) *YoutubePlaylistMappingCreate {
	_c.mutation.SetGameCategory(v)
	return _c
}

// SetPlaylistID sets the "playlist_id" field.
func (_c *YoutubePlaylistMappingCreate) SetPlaylistID(v string) *YoutubePlaylistMappingCreate {
	_c.mutation.SetPlaylistID(v)
	return _c
}

// SetPlaylistName sets the "playlist_name" field.
func (_c *YoutubePlaylistMappingCreate) SetPlaylistName(v string) *YoutubePlaylistMappingCreate {
	_c.mutation.SetPlaylistName(v)
	return _c
}

// SetNillablePlaylistName sets the "playlist_name" field if the given value is not nil.
func (_c *YoutubePlaylistMappingCreate) SetNillablePlaylistName(v *string) *YoutubePlaylistMappingCreate {
	if v != nil {
		_c.SetPlaylistName(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *YoutubePlaylistMappingCreate) SetPriority(v int) *YoutubePlaylistMappingCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *YoutubePlaylistMappingCreate) SetNillablePriority(v *int) *YoutubePlaylistMappingCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *YoutubePlaylistMappingCreate) SetUpdatedAt(v time.Time) *YoutubePlaylistMappingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *YoutubePlaylistMappingCreate) SetNillableUpdatedAt(v *time.Time) *YoutubePlaylistMappingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *YoutubePlaylistMappingCreate) SetCreatedAt(v time.Time) *YoutubePlaylistMappingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *YoutubePlaylistMappingCreate) SetNillableCreatedAt(v *time.Time) *YoutubePlaylistMappingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *YoutubePlaylistMappingCreate) SetID(v uuid.UUID) *YoutubePlaylistMappingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *YoutubePlaylistMappingCreate) SetNillableID(v *uuid.UUID) *YoutubePlaylistMappingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetYoutubeConfigID sets the "youtube_config" edge to the YoutubeConfig entity by ID.
func (_c *YoutubePlaylistMappingCreate) SetYoutubeConfigID(id uuid.UUID) *YoutubePlaylistMappingCreate {
	_c.mutation.SetYoutubeConfigID(id)
	return _c
}

// SetYoutubeConfig sets the "youtube_config" edge to the YoutubeConfig entity.
func (_c *YoutubePlaylistMappingCreate) SetYoutubeConfig(v *YoutubeConfig) *YoutubePlaylistMappingCreate {
	return _c.SetYoutubeConfigID(v.ID)
}

// Mutation returns the YoutubePlaylistMappingMutation object of the builder.
func (_c *YoutubePlaylistMappingCreate) Mutation() *YoutubePlaylistMappingMutation {
	return _c.mutation
}

// Save creates the YoutubePlaylistMapping in the database.
func (_c *YoutubePlaylistMappingCreate) Save(ctx context.Context) (*YoutubePlaylistMapping, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *YoutubePlaylistMappingCreate) SaveX(ctx context.Context) *YoutubePlaylistMapping {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *YoutubePlaylistMappingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *YoutubePlaylistMappingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *YoutubePlaylistMappingCreate) defaults() {
	if _, ok := _c.mutation.Priority(); !ok {
		v := youtubeplaylistmapping.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := youtubeplaylistmapping.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := youtubeplaylistmapping.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := youtubeplaylistmapping.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *YoutubePlaylistMappingCreate) check() error {
	if _, ok := _c.mutation.GameCategory(); !ok {
		return &ValidationError{Name: "game_category", err: errors.New(`ent: missing required field "YoutubePlaylistMapping.game_category"`)}
	}
	if _, ok := _c.mutation.PlaylistID(); !ok {
		return &ValidationError{Name: "playlist_id", err: errors.New(`ent: missing required field "YoutubePlaylistMapping.playlist_id"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "YoutubePlaylistMapping.priority"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "YoutubePlaylistMapping.updated_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "YoutubePlaylistMapping.created_at"`)}
	}
	if len(_c.mutation.YoutubeConfigIDs()) == 0 {
		return &ValidationError{Name: "youtube_config", err: errors.New(`ent: missing required edge "YoutubePlaylistMapping.youtube_config"`)}
	}
	return nil
}

func (_c *YoutubePlaylistMappingCreate) sqlSave(ctx context.Context) (*YoutubePlaylistMapping, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *YoutubePlaylistMappingCreate) createSpec() (*YoutubePlaylistMapping, *sqlgraph.CreateSpec) {
	var (
		_node = &YoutubePlaylistMapping{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(youtubeplaylistmapping.Table, sqlgraph.NewFieldSpec(youtubeplaylistmapping.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GameCategory(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldGameCategory, field.TypeString, value)
		_node.GameCategory = value
	}
	if value, ok := _c.mutation.PlaylistID(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldPlaylistID, field.TypeString, value)
		_node.PlaylistID = value
	}
	if value, ok := _c.mutation.PlaylistName(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldPlaylistName, field.TypeString, value)
		_node.PlaylistName = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.YoutubeConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   youtubeplaylistmapping.YoutubeConfigTable,
			Columns: []string{youtubeplaylistmapping.YoutubeConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(youtubeconfig.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.youtube_config_playlist_mappings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// YoutubePlaylistMappingCreateBulk is the builder for creating many YoutubePlaylistMapping entities in bulk.
type YoutubePlaylistMappingCreateBulk struct {
	config
	err      error
	builders []*YoutubePlaylistMappingCreate
}

// Save creates the YoutubePlaylistMapping entities in the database.
func (_c *YoutubePlaylistMappingCreateBulk) Save(ctx context.Context) ([]*YoutubePlaylistMapping, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*YoutubePlaylistMapping, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*YoutubePlaylistMappingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *YoutubePlaylistMappingCreateBulk) SaveX(ctx context.Context) []*YoutubePlaylistMapping {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *YoutubePlaylistMappingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *YoutubePlaylistMappingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
