// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/channel"
	"github.com/zibbp/ganymede/ent/predicate"
	"github.com/zibbp/ganymede/ent/youtubeconfig"
	"github.com/zibbp/ganymede/ent/youtubeplaylistmapping"
)

// YoutubeConfigQuery is the builder for querying YoutubeConfig entities.
type YoutubeConfigQuery struct {
	config
	ctx                  *QueryContext
	order                []youtubeconfig.OrderOption
	inters               []Interceptor
	predicates           []predicate.YoutubeConfig
	withChannel          *ChannelQuery
	withPlaylistMappings *YoutubePlaylistMappingQuery
	withFKs              bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the YoutubeConfigQuery builder.
func (_q *YoutubeConfigQuery) Where(ps ...predicate.YoutubeConfig) *YoutubeConfigQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *YoutubeConfigQuery) Limit(limit int) *YoutubeConfigQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *YoutubeConfigQuery) Offset(offset int) *YoutubeConfigQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *YoutubeConfigQuery) Unique(unique bool) *YoutubeConfigQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *YoutubeConfigQuery) Order(o ...youtubeconfig.OrderOption) *YoutubeConfigQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryChannel chains the current query on the "channel" edge.
func (_q *YoutubeConfigQuery) QueryChannel() *ChannelQuery {
	query := (&ChannelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(youtubeconfig.Table, youtubeconfig.FieldID, selector),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, youtubeconfig.ChannelTable, youtubeconfig.ChannelColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPlaylistMappings chains the current query on the "playlist_mappings" edge.
func (_q *YoutubeConfigQuery) QueryPlaylistMappings() *YoutubePlaylistMappingQuery {
	query := (&YoutubePlaylistMappingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(youtubeconfig.Table, youtubeconfig.FieldID, selector),
			sqlgraph.To(youtubeplaylistmapping.Table, youtubeplaylistmapping.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, youtubeconfig.PlaylistMappingsTable, youtubeconfig.PlaylistMappingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first YoutubeConfig entity from the query.
// Returns a *NotFoundError when no YoutubeConfig was found.
func (_q *YoutubeConfigQuery) First(ctx context.Context) (*YoutubeConfig, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{youtubeconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *YoutubeConfigQuery) FirstX(ctx context.Context) *YoutubeConfig {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first YoutubeConfig ID from the query.
// Returns a *NotFoundError when no YoutubeConfig ID was found.
func (_q *YoutubeConfigQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{youtubeconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *YoutubeConfigQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single YoutubeConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one YoutubeConfig entity is found.
// Returns a *NotFoundError when no YoutubeConfig entities are found.
func (_q *YoutubeConfigQuery) Only(ctx context.Context) (*YoutubeConfig, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{youtubeconfig.Label}
	default:
		return nil, &NotSingularError{youtubeconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *YoutubeConfigQuery) OnlyX(ctx context.Context) *YoutubeConfig {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only YoutubeConfig ID in the query.
// Returns a *NotSingularError when more than one YoutubeConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *YoutubeConfigQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{youtubeconfig.Label}
	default:
		err = &NotSingularError{youtubeconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *YoutubeConfigQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of YoutubeConfigs.
func (_q *YoutubeConfigQuery) All(ctx context.Context) ([]*YoutubeConfig, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*YoutubeConfig, *YoutubeConfigQuery]()
	return withInterceptors[[]*YoutubeConfig](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *YoutubeConfigQuery) AllX(ctx context.Context) []*YoutubeConfig {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of YoutubeConfig IDs.
func (_q *YoutubeConfigQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(youtubeconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *YoutubeConfigQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *YoutubeConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*YoutubeConfigQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *YoutubeConfigQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *YoutubeConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *YoutubeConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the YoutubeConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *YoutubeConfigQuery) Clone() *YoutubeConfigQuery {
	if _q == nil {
		return nil
	}
	return &YoutubeConfigQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]youtubeconfig.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.YoutubeConfig{}, _q.predicates...),
		withChannel:          _q.withChannel.Clone(),
		withPlaylistMappings: _q.withPlaylistMappings.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithChannel tells the query-builder to eager-load the nodes that are connected to
// the "channel" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *YoutubeConfigQuery) WithChannel(opts ...func(*ChannelQuery)) *YoutubeConfigQuery {
	query := (&ChannelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChannel = query
	return _q
}

// WithPlaylistMappings tells the query-builder to eager-load the nodes that are connected to
// the "playlist_mappings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *YoutubeConfigQuery) WithPlaylistMappings(opts ...func(*YoutubePlaylistMappingQuery)) *YoutubeConfigQuery {
	query := (&YoutubePlaylistMappingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlaylistMappings = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UploadEnabled bool `json:"upload_enabled,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.YoutubeConfig.Query().
//		GroupBy(youtubeconfig.FieldUploadEnabled).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *YoutubeConfigQuery) GroupBy(field string, fields ...string) *YoutubeConfigGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &YoutubeConfigGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = youtubeconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UploadEnabled bool `json:"upload_enabled,omitempty"`
//	}
//
//	client.YoutubeConfig.Query().
//		Select(youtubeconfig.FieldUploadEnabled).
//		Scan(ctx, &v)
func (_q *YoutubeConfigQuery) Select(fields ...string) *YoutubeConfigSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &YoutubeConfigSelect{YoutubeConfigQuery: _q}
	sbuild.label = youtubeconfig.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a YoutubeConfigSelect configured with the given aggregations.
func (_q *YoutubeConfigQuery) Aggregate(fns ...AggregateFunc) *YoutubeConfigSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *YoutubeConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !youtubeconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *YoutubeConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*YoutubeConfig, error) {
	var (
		nodes       = []*YoutubeConfig{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withChannel != nil,
			_q.withPlaylistMappings != nil,
		}
	)
	if _q.withChannel != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, youtubeconfig.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*YoutubeConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &YoutubeConfig{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withChannel; query != nil {
		if err := _q.loadChannel(ctx, query, nodes, nil,
			func(n *YoutubeConfig, e *Channel) { n.Edges.Channel = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPlaylistMappings; query != nil {
		if err := _q.loadPlaylistMappings(ctx, query, nodes,
			func(n *YoutubeConfig) { n.Edges.PlaylistMappings = []*YoutubePlaylistMapping{} },
			func(n *YoutubeConfig, e *YoutubePlaylistMapping) {
				n.Edges.PlaylistMappings = append(n.Edges.PlaylistMappings, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *YoutubeConfigQuery) loadChannel(ctx context.Context, query *ChannelQuery, nodes []*YoutubeConfig, init func(*YoutubeConfig), assign func(*YoutubeConfig, *Channel)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*YoutubeConfig)
	for i := range nodes {
		if nodes[i].channel_youtube_config == nil {
			continue
		}
		fk := *nodes[i].channel_youtube_config
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(channel.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "channel_youtube_config" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *YoutubeConfigQuery) loadPlaylistMappings(ctx context.Context, query *YoutubePlaylistMappingQuery, nodes []*YoutubeConfig, init func(*YoutubeConfig), assign func(*YoutubeConfig, *YoutubePlaylistMapping)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*YoutubeConfig)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.YoutubePlaylistMapping(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(youtubeconfig.PlaylistMappingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.youtube_config_playlist_mappings
		if fk == nil {
			return fmt.Errorf(`foreign-key "youtube_config_playlist_mappings" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "youtube_config_playlist_mappings" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *YoutubeConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *YoutubeConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(youtubeconfig.Table, youtubeconfig.Columns, sqlgraph.NewFieldSpec(youtubeconfig.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, youtubeconfig.FieldID)
		for i := range fields {
			if fields[i] != youtubeconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *YoutubeConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(youtubeconfig.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = youtubeconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// YoutubeConfigGroupBy is the group-by builder for YoutubeConfig entities.
type YoutubeConfigGroupBy struct {
	selector
	build *YoutubeConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *YoutubeConfigGroupBy) Aggregate(fns ...AggregateFunc) *YoutubeConfigGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *YoutubeConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*YoutubeConfigQuery, *YoutubeConfigGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *YoutubeConfigGroupBy) sqlScan(ctx context.Context, root *YoutubeConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// YoutubeConfigSelect is the builder for selecting fields of YoutubeConfig entities.
type YoutubeConfigSelect struct {
	*YoutubeConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *YoutubeConfigSelect) Aggregate(fns ...AggregateFunc) *YoutubeConfigSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *YoutubeConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*YoutubeConfigQuery, *YoutubeConfigSelect](ctx, _s.YoutubeConfigQuery, _s, _s.inters, v)
}

func (_s *YoutubeConfigSelect) sqlScan(ctx context.Context, root *YoutubeConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
