// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/vod"
	"github.com/zibbp/ganymede/ent/youtubeupload"
)

// YoutubeUpload is the model entity for the YoutubeUpload schema.
type YoutubeUpload struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// YouTube video ID after successful upload
	YoutubeVideoID string `json:"youtube_video_id,omitempty"`
	// Full YouTube URL of the uploaded video
	YoutubeURL string `json:"youtube_url,omitempty"`
	// Upload status: pending, uploading, completed, failed
	Status string `json:"status,omitempty"`
	// Error message if upload failed
	ErrorMessage string `json:"error_message,omitempty"`
	// Number of times upload was retried
	RetryCount int `json:"retry_count,omitempty"`
	// Time when upload completed successfully
	UploadedAt time.Time `json:"uploaded_at,omitempty"`
	// YouTube playlist IDs the video was added to
	PlaylistIds []string `json:"playlist_ids,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the YoutubeUploadQuery when eager-loading is set.
	Edges              YoutubeUploadEdges `json:"edges"`
	vod_youtube_upload *uuid.UUID
	selectValues       sql.SelectValues
}

// YoutubeUploadEdges holds the relations/edges for other nodes in the graph.
type YoutubeUploadEdges struct {
	// Vod holds the value of the vod edge.
	Vod *Vod `json:"vod,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// VodOrErr returns the Vod value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e YoutubeUploadEdges) VodOrErr() (*Vod, error) {
	if e.Vod != nil {
		return e.Vod, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: vod.Label}
	}
	return nil, &NotLoadedError{edge: "vod"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*YoutubeUpload) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case youtubeupload.FieldPlaylistIds:
			values[i] = new([]byte)
		case youtubeupload.FieldRetryCount:
			values[i] = new(sql.NullInt64)
		case youtubeupload.FieldYoutubeVideoID, youtubeupload.FieldYoutubeURL, youtubeupload.FieldStatus, youtubeupload.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case youtubeupload.FieldUploadedAt, youtubeupload.FieldUpdatedAt, youtubeupload.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case youtubeupload.FieldID:
			values[i] = new(uuid.UUID)
		case youtubeupload.ForeignKeys[0]: // vod_youtube_upload
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the YoutubeUpload fields.
func (_m *YoutubeUpload) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case youtubeupload.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case youtubeupload.FieldYoutubeVideoID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field youtube_video_id", values[i])
			} else if value.Valid {
				_m.YoutubeVideoID = value.String
			}
		case youtubeupload.FieldYoutubeURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field youtube_url", values[i])
			} else if value.Valid {
				_m.YoutubeURL = value.String
			}
		case youtubeupload.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case youtubeupload.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case youtubeupload.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case youtubeupload.FieldUploadedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded_at", values[i])
			} else if value.Valid {
				_m.UploadedAt = value.Time
			}
		case youtubeupload.FieldPlaylistIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field playlist_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PlaylistIds); err != nil {
					return fmt.Errorf("unmarshal field playlist_ids: %w", err)
				}
			}
		case youtubeupload.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case youtubeupload.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case youtubeupload.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field vod_youtube_upload", values[i])
			} else if value.Valid {
				_m.vod_youtube_upload = new(uuid.UUID)
				*_m.vod_youtube_upload = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the YoutubeUpload.
// This includes values selected through modifiers, order, etc.
func (_m *YoutubeUpload) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVod queries the "vod" edge of the YoutubeUpload entity.
func (_m *YoutubeUpload) QueryVod() *VodQuery {
	return NewYoutubeUploadClient(_m.config).QueryVod(_m)
}

// Update returns a builder for updating this YoutubeUpload.
// Note that you need to call YoutubeUpload.Unwrap() before calling this method if this YoutubeUpload
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *YoutubeUpload) Update() *YoutubeUploadUpdateOne {
	return NewYoutubeUploadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the YoutubeUpload entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *YoutubeUpload) Unwrap() *YoutubeUpload {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: YoutubeUpload is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *YoutubeUpload) String() string {
	var builder strings.Builder
	builder.WriteString("YoutubeUpload(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("youtube_video_id=")
	builder.WriteString(_m.YoutubeVideoID)
	builder.WriteString(", ")
	builder.WriteString("youtube_url=")
	builder.WriteString(_m.YoutubeURL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("uploaded_at=")
	builder.WriteString(_m.UploadedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("playlist_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlaylistIds))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// YoutubeUploads is a parsable slice of YoutubeUpload.
type YoutubeUploads []*YoutubeUpload
