// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zibbp/ganymede/ent/predicate"
	"github.com/zibbp/ganymede/ent/youtubecredential"
)

// YoutubeCredentialDelete is the builder for deleting a YoutubeCredential entity.
type YoutubeCredentialDelete struct {
	config
	hooks    []Hook
	mutation *YoutubeCredentialMutation
}

// Where appends a list predicates to the YoutubeCredentialDelete builder.
func (_d *YoutubeCredentialDelete) Where(ps ...predicate.YoutubeCredential) *YoutubeCredentialDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *YoutubeCredentialDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *YoutubeCredentialDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *YoutubeCredentialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(youtubecredential.Table, sqlgraph.NewFieldSpec(youtubecredential.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// YoutubeCredentialDeleteOne is the builder for deleting a single YoutubeCredential entity.
type YoutubeCredentialDeleteOne struct {
	_d *YoutubeCredentialDelete
}

// Where appends a list predicates to the YoutubeCredentialDelete builder.
func (_d *YoutubeCredentialDeleteOne) Where(ps ...predicate.YoutubeCredential) *YoutubeCredentialDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *YoutubeCredentialDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{youtubecredential.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *YoutubeCredentialDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
