// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/youtubeconfig"
	"github.com/zibbp/ganymede/ent/youtubeplaylistmapping"
)

// YoutubePlaylistMapping is the model entity for the YoutubePlaylistMapping schema.
type YoutubePlaylistMapping struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Game/category name to match (case-insensitive, supports wildcards with *)
	GameCategory string `json:"game_category,omitempty"`
	// YouTube playlist ID to add videos to
	PlaylistID string `json:"playlist_id,omitempty"`
	// Human-readable playlist name for reference
	PlaylistName string `json:"playlist_name,omitempty"`
	// Priority for matching (higher = checked first)
	Priority int `json:"priority,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the YoutubePlaylistMappingQuery when eager-loading is set.
	Edges                            YoutubePlaylistMappingEdges `json:"edges"`
	youtube_config_playlist_mappings *uuid.UUID
	selectValues                     sql.SelectValues
}

// YoutubePlaylistMappingEdges holds the relations/edges for other nodes in the graph.
type YoutubePlaylistMappingEdges struct {
	// YoutubeConfig holds the value of the youtube_config edge.
	YoutubeConfig *YoutubeConfig `json:"youtube_config,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// YoutubeConfigOrErr returns the YoutubeConfig value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e YoutubePlaylistMappingEdges) YoutubeConfigOrErr() (*YoutubeConfig, error) {
	if e.YoutubeConfig != nil {
		return e.YoutubeConfig, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: youtubeconfig.Label}
	}
	return nil, &NotLoadedError{edge: "youtube_config"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*YoutubePlaylistMapping) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case youtubeplaylistmapping.FieldPriority:
			values[i] = new(sql.NullInt64)
		case youtubeplaylistmapping.FieldGameCategory, youtubeplaylistmapping.FieldPlaylistID, youtubeplaylistmapping.FieldPlaylistName:
			values[i] = new(sql.NullString)
		case youtubeplaylistmapping.FieldUpdatedAt, youtubeplaylistmapping.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case youtubeplaylistmapping.FieldID:
			values[i] = new(uuid.UUID)
		case youtubeplaylistmapping.ForeignKeys[0]: // youtube_config_playlist_mappings
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the YoutubePlaylistMapping fields.
func (_m *YoutubePlaylistMapping) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case youtubeplaylistmapping.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case youtubeplaylistmapping.FieldGameCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field game_category", values[i])
			} else if value.Valid {
				_m.GameCategory = value.String
			}
		case youtubeplaylistmapping.FieldPlaylistID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field playlist_id", values[i])
			} else if value.Valid {
				_m.PlaylistID = value.String
			}
		case youtubeplaylistmapping.FieldPlaylistName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field playlist_name", values[i])
			} else if value.Valid {
				_m.PlaylistName = value.String
			}
		case youtubeplaylistmapping.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case youtubeplaylistmapping.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case youtubeplaylistmapping.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case youtubeplaylistmapping.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field youtube_config_playlist_mappings", values[i])
			} else if value.Valid {
				_m.youtube_config_playlist_mappings = new(uuid.UUID)
				*_m.youtube_config_playlist_mappings = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the YoutubePlaylistMapping.
// This includes values selected through modifiers, order, etc.
func (_m *YoutubePlaylistMapping) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryYoutubeConfig queries the "youtube_config" edge of the YoutubePlaylistMapping entity.
func (_m *YoutubePlaylistMapping) QueryYoutubeConfig() *YoutubeConfigQuery {
	return NewYoutubePlaylistMappingClient(_m.config).QueryYoutubeConfig(_m)
}

// Update returns a builder for updating this YoutubePlaylistMapping.
// Note that you need to call YoutubePlaylistMapping.Unwrap() before calling this method if this YoutubePlaylistMapping
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *YoutubePlaylistMapping) Update() *YoutubePlaylistMappingUpdateOne {
	return NewYoutubePlaylistMappingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the YoutubePlaylistMapping entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *YoutubePlaylistMapping) Unwrap() *YoutubePlaylistMapping {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: YoutubePlaylistMapping is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *YoutubePlaylistMapping) String() string {
	var builder strings.Builder
	builder.WriteString("YoutubePlaylistMapping(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("game_category=")
	builder.WriteString(_m.GameCategory)
	builder.WriteString(", ")
	builder.WriteString("playlist_id=")
	builder.WriteString(_m.PlaylistID)
	builder.WriteString(", ")
	builder.WriteString("playlist_name=")
	builder.WriteString(_m.PlaylistName)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// YoutubePlaylistMappings is a parsable slice of YoutubePlaylistMapping.
type YoutubePlaylistMappings []*YoutubePlaylistMapping
