// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zibbp/ganymede/ent/predicate"
	"github.com/zibbp/ganymede/ent/youtubeplaylistmapping"
)

// YoutubePlaylistMappingDelete is the builder for deleting a YoutubePlaylistMapping entity.
type YoutubePlaylistMappingDelete struct {
	config
	hooks    []Hook
	mutation *YoutubePlaylistMappingMutation
}

// Where appends a list predicates to the YoutubePlaylistMappingDelete builder.
func (_d *YoutubePlaylistMappingDelete) Where(ps ...predicate.YoutubePlaylistMapping) *YoutubePlaylistMappingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *YoutubePlaylistMappingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *YoutubePlaylistMappingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *YoutubePlaylistMappingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(youtubeplaylistmapping.Table, sqlgraph.NewFieldSpec(youtubeplaylistmapping.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// YoutubePlaylistMappingDeleteOne is the builder for deleting a single YoutubePlaylistMapping entity.
type YoutubePlaylistMappingDeleteOne struct {
	_d *YoutubePlaylistMappingDelete
}

// Where appends a list predicates to the YoutubePlaylistMappingDelete builder.
func (_d *YoutubePlaylistMappingDeleteOne) Where(ps ...predicate.YoutubePlaylistMapping) *YoutubePlaylistMappingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *YoutubePlaylistMappingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{youtubeplaylistmapping.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *YoutubePlaylistMappingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
