// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/predicate"
	"github.com/zibbp/ganymede/ent/youtubeconfig"
	"github.com/zibbp/ganymede/ent/youtubeplaylistmapping"
)

// YoutubePlaylistMappingUpdate is the builder for updating YoutubePlaylistMapping entities.
type YoutubePlaylistMappingUpdate struct {
	config
	hooks    []Hook
	mutation *YoutubePlaylistMappingMutation
}

// Where appends a list predicates to the YoutubePlaylistMappingUpdate builder.
func (_u *YoutubePlaylistMappingUpdate) Where(ps ...predicate.YoutubePlaylistMapping) *YoutubePlaylistMappingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGameCategory sets the "game_category" field.
func (_u *YoutubePlaylistMappingUpdate) SetGameCategory(v string) *YoutubePlaylistMappingUpdate {
	_u.mutation.SetGameCategory(v)
	return _u
}

// SetNillableGameCategory sets the "game_category" field if the given value is not nil.
func (_u *YoutubePlaylistMappingUpdate) SetNillableGameCategory(v *string) *YoutubePlaylistMappingUpdate {
	if v != nil {
		_u.SetGameCategory(*v)
	}
	return _u
}

// SetPlaylistID sets the "playlist_id" field.
func (_u *YoutubePlaylistMappingUpdate) SetPlaylistID(v string) *YoutubePlaylistMappingUpdate {
	_u.mutation.SetPlaylistID(v)
	return _u
}

// SetNillablePlaylistID sets the "playlist_id" field if the given value is not nil.
func (_u *YoutubePlaylistMappingUpdate) SetNillablePlaylistID(v *string) *YoutubePlaylistMappingUpdate {
	if v != nil {
		_u.SetPlaylistID(*v)
	}
	return _u
}

// SetPlaylistName sets the "playlist_name" field.
func (_u *YoutubePlaylistMappingUpdate) SetPlaylistName(v string) *YoutubePlaylistMappingUpdate {
	_u.mutation.SetPlaylistName(v)
	return _u
}

// SetNillablePlaylistName sets the "playlist_name" field if the given value is not nil.
func (_u *YoutubePlaylistMappingUpdate) SetNillablePlaylistName(v *string) *YoutubePlaylistMappingUpdate {
	if v != nil {
		_u.SetPlaylistName(*v)
	}
	return _u
}

// ClearPlaylistName clears the value of the "playlist_name" field.
func (_u *YoutubePlaylistMappingUpdate) ClearPlaylistName() *YoutubePlaylistMappingUpdate {
	_u.mutation.ClearPlaylistName()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *YoutubePlaylistMappingUpdate) SetPriority(v int) *YoutubePlaylistMappingUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *YoutubePlaylistMappingUpdate) SetNillablePriority(v *int) *YoutubePlaylistMappingUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *YoutubePlaylistMappingUpdate) AddPriority(v int) *YoutubePlaylistMappingUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *YoutubePlaylistMappingUpdate) SetUpdatedAt(v time.Time) *YoutubePlaylistMappingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetYoutubeConfigID sets the "youtube_config" edge to the YoutubeConfig entity by ID.
func (_u *YoutubePlaylistMappingUpdate) SetYoutubeConfigID(id uuid.UUID) *YoutubePlaylistMappingUpdate {
	_u.mutation.SetYoutubeConfigID(id)
	return _u
}

// SetYoutubeConfig sets the "youtube_config" edge to the YoutubeConfig entity.
func (_u *YoutubePlaylistMappingUpdate) SetYoutubeConfig(v *YoutubeConfig) *YoutubePlaylistMappingUpdate {
	return _u.SetYoutubeConfigID(v.ID)
}

// Mutation returns the YoutubePlaylistMappingMutation object of the builder.
func (_u *YoutubePlaylistMappingUpdate) Mutation() *YoutubePlaylistMappingMutation {
	return _u.mutation
}

// ClearYoutubeConfig clears the "youtube_config" edge to the YoutubeConfig entity.
func (_u *YoutubePlaylistMappingUpdate) ClearYoutubeConfig() *YoutubePlaylistMappingUpdate {
	_u.mutation.ClearYoutubeConfig()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *YoutubePlaylistMappingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *YoutubePlaylistMappingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *YoutubePlaylistMappingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *YoutubePlaylistMappingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *YoutubePlaylistMappingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := youtubeplaylistmapping.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *YoutubePlaylistMappingUpdate) check() error {
	if _u.mutation.YoutubeConfigCleared() && len(_u.mutation.YoutubeConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "YoutubePlaylistMapping.youtube_config"`)
	}
	return nil
}

func (_u *YoutubePlaylistMappingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(youtubeplaylistmapping.Table, youtubeplaylistmapping.Columns, sqlgraph.NewFieldSpec(youtubeplaylistmapping.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GameCategory(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldGameCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlaylistID(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldPlaylistID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlaylistName(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldPlaylistName, field.TypeString, value)
	}
	if _u.mutation.PlaylistNameCleared() {
		_spec.ClearField(youtubeplaylistmapping.FieldPlaylistName, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(youtubeplaylistmapping.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.YoutubeConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   youtubeplaylistmapping.YoutubeConfigTable,
			Columns: []string{youtubeplaylistmapping.YoutubeConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(youtubeconfig.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.YoutubeConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   youtubeplaylistmapping.YoutubeConfigTable,
			Columns: []string{youtubeplaylistmapping.YoutubeConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(youtubeconfig.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{youtubeplaylistmapping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// YoutubePlaylistMappingUpdateOne is the builder for updating a single YoutubePlaylistMapping entity.
type YoutubePlaylistMappingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *YoutubePlaylistMappingMutation
}

// SetGameCategory sets the "game_category" field.
func (_u *YoutubePlaylistMappingUpdateOne) SetGameCategory(v string) *YoutubePlaylistMappingUpdateOne {
	_u.mutation.SetGameCategory(v)
	return _u
}

// SetNillableGameCategory sets the "game_category" field if the given value is not nil.
func (_u *YoutubePlaylistMappingUpdateOne) SetNillableGameCategory(v *string) *YoutubePlaylistMappingUpdateOne {
	if v != nil {
		_u.SetGameCategory(*v)
	}
	return _u
}

// SetPlaylistID sets the "playlist_id" field.
func (_u *YoutubePlaylistMappingUpdateOne) SetPlaylistID(v string) *YoutubePlaylistMappingUpdateOne {
	_u.mutation.SetPlaylistID(v)
	return _u
}

// SetNillablePlaylistID sets the "playlist_id" field if the given value is not nil.
func (_u *YoutubePlaylistMappingUpdateOne) SetNillablePlaylistID(v *string) *YoutubePlaylistMappingUpdateOne {
	if v != nil {
		_u.SetPlaylistID(*v)
	}
	return _u
}

// SetPlaylistName sets the "playlist_name" field.
func (_u *YoutubePlaylistMappingUpdateOne) SetPlaylistName(v string) *YoutubePlaylistMappingUpdateOne {
	_u.mutation.SetPlaylistName(v)
	return _u
}

// SetNillablePlaylistName sets the "playlist_name" field if the given value is not nil.
func (_u *YoutubePlaylistMappingUpdateOne) SetNillablePlaylistName(v *string) *YoutubePlaylistMappingUpdateOne {
	if v != nil {
		_u.SetPlaylistName(*v)
	}
	return _u
}

// ClearPlaylistName clears the value of the "playlist_name" field.
func (_u *YoutubePlaylistMappingUpdateOne) ClearPlaylistName() *YoutubePlaylistMappingUpdateOne {
	_u.mutation.ClearPlaylistName()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *YoutubePlaylistMappingUpdateOne) SetPriority(v int) *YoutubePlaylistMappingUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *YoutubePlaylistMappingUpdateOne) SetNillablePriority(v *int) *YoutubePlaylistMappingUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *YoutubePlaylistMappingUpdateOne) AddPriority(v int) *YoutubePlaylistMappingUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *YoutubePlaylistMappingUpdateOne) SetUpdatedAt(v time.Time) *YoutubePlaylistMappingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetYoutubeConfigID sets the "youtube_config" edge to the YoutubeConfig entity by ID.
func (_u *YoutubePlaylistMappingUpdateOne) SetYoutubeConfigID(id uuid.UUID) *YoutubePlaylistMappingUpdateOne {
	_u.mutation.SetYoutubeConfigID(id)
	return _u
}

// SetYoutubeConfig sets the "youtube_config" edge to the YoutubeConfig entity.
func (_u *YoutubePlaylistMappingUpdateOne) SetYoutubeConfig(v *YoutubeConfig) *YoutubePlaylistMappingUpdateOne {
	return _u.SetYoutubeConfigID(v.ID)
}

// Mutation returns the YoutubePlaylistMappingMutation object of the builder.
func (_u *YoutubePlaylistMappingUpdateOne) Mutation() *YoutubePlaylistMappingMutation {
	return _u.mutation
}

// ClearYoutubeConfig clears the "youtube_config" edge to the YoutubeConfig entity.
func (_u *YoutubePlaylistMappingUpdateOne) ClearYoutubeConfig() *YoutubePlaylistMappingUpdateOne {
	_u.mutation.ClearYoutubeConfig()
	return _u
}

// Where appends a list predicates to the YoutubePlaylistMappingUpdate builder.
func (_u *YoutubePlaylistMappingUpdateOne) Where(ps ...predicate.YoutubePlaylistMapping) *YoutubePlaylistMappingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *YoutubePlaylistMappingUpdateOne) Select(field string, fields ...string) *YoutubePlaylistMappingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated YoutubePlaylistMapping entity.
func (_u *YoutubePlaylistMappingUpdateOne) Save(ctx context.Context) (*YoutubePlaylistMapping, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *YoutubePlaylistMappingUpdateOne) SaveX(ctx context.Context) *YoutubePlaylistMapping {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *YoutubePlaylistMappingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *YoutubePlaylistMappingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *YoutubePlaylistMappingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := youtubeplaylistmapping.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *YoutubePlaylistMappingUpdateOne) check() error {
	if _u.mutation.YoutubeConfigCleared() && len(_u.mutation.YoutubeConfigIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "YoutubePlaylistMapping.youtube_config"`)
	}
	return nil
}

func (_u *YoutubePlaylistMappingUpdateOne) sqlSave(ctx context.Context) (_node *YoutubePlaylistMapping, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(youtubeplaylistmapping.Table, youtubeplaylistmapping.Columns, sqlgraph.NewFieldSpec(youtubeplaylistmapping.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "YoutubePlaylistMapping.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, youtubeplaylistmapping.FieldID)
		for _, f := range fields {
			if !youtubeplaylistmapping.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != youtubeplaylistmapping.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GameCategory(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldGameCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlaylistID(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldPlaylistID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlaylistName(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldPlaylistName, field.TypeString, value)
	}
	if _u.mutation.PlaylistNameCleared() {
		_spec.ClearField(youtubeplaylistmapping.FieldPlaylistName, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(youtubeplaylistmapping.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(youtubeplaylistmapping.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.YoutubeConfigCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   youtubeplaylistmapping.YoutubeConfigTable,
			Columns: []string{youtubeplaylistmapping.YoutubeConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(youtubeconfig.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.YoutubeConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   youtubeplaylistmapping.YoutubeConfigTable,
			Columns: []string{youtubeplaylistmapping.YoutubeConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(youtubeconfig.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &YoutubePlaylistMapping{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{youtubeplaylistmapping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
