// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/channel"
	"github.com/zibbp/ganymede/ent/youtubeconfig"
)

// YoutubeConfig is the model entity for the YoutubeConfig schema.
type YoutubeConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Enable automatic upload to YouTube for this channel
	UploadEnabled bool `json:"upload_enabled,omitempty"`
	// Default privacy status: private, unlisted, or public
	DefaultPrivacy string `json:"default_privacy,omitempty"`
	// YouTube category ID (20 = Gaming)
	DefaultCategoryID string `json:"default_category_id,omitempty"`
	// Template for video description, supports placeholders
	DescriptionTemplate string `json:"description_template,omitempty"`
	// Template for video title, supports placeholders like {title}, {date}, {channel}
	TitleTemplate string `json:"title_template,omitempty"`
	// Default tags to add to uploaded videos
	Tags []string `json:"tags,omitempty"`
	// Add chapter markers to YouTube video
	AddChapters bool `json:"add_chapters,omitempty"`
	// Notify subscribers when video is uploaded
	NotifySubscribers bool `json:"notify_subscribers,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the YoutubeConfigQuery when eager-loading is set.
	Edges                  YoutubeConfigEdges `json:"edges"`
	channel_youtube_config *uuid.UUID
	selectValues           sql.SelectValues
}

// YoutubeConfigEdges holds the relations/edges for other nodes in the graph.
type YoutubeConfigEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// PlaylistMappings holds the value of the playlist_mappings edge.
	PlaylistMappings []*YoutubePlaylistMapping `json:"playlist_mappings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e YoutubeConfigEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// PlaylistMappingsOrErr returns the PlaylistMappings value or an error if the edge
// was not loaded in eager-loading.
func (e YoutubeConfigEdges) PlaylistMappingsOrErr() ([]*YoutubePlaylistMapping, error) {
	if e.loadedTypes[1] {
		return e.PlaylistMappings, nil
	}
	return nil, &NotLoadedError{edge: "playlist_mappings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*YoutubeConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case youtubeconfig.FieldTags:
			values[i] = new([]byte)
		case youtubeconfig.FieldUploadEnabled, youtubeconfig.FieldAddChapters, youtubeconfig.FieldNotifySubscribers:
			values[i] = new(sql.NullBool)
		case youtubeconfig.FieldDefaultPrivacy, youtubeconfig.FieldDefaultCategoryID, youtubeconfig.FieldDescriptionTemplate, youtubeconfig.FieldTitleTemplate:
			values[i] = new(sql.NullString)
		case youtubeconfig.FieldUpdatedAt, youtubeconfig.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case youtubeconfig.FieldID:
			values[i] = new(uuid.UUID)
		case youtubeconfig.ForeignKeys[0]: // channel_youtube_config
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the YoutubeConfig fields.
func (_m *YoutubeConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case youtubeconfig.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case youtubeconfig.FieldUploadEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field upload_enabled", values[i])
			} else if value.Valid {
				_m.UploadEnabled = value.Bool
			}
		case youtubeconfig.FieldDefaultPrivacy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_privacy", values[i])
			} else if value.Valid {
				_m.DefaultPrivacy = value.String
			}
		case youtubeconfig.FieldDefaultCategoryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_category_id", values[i])
			} else if value.Valid {
				_m.DefaultCategoryID = value.String
			}
		case youtubeconfig.FieldDescriptionTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description_template", values[i])
			} else if value.Valid {
				_m.DescriptionTemplate = value.String
			}
		case youtubeconfig.FieldTitleTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_template", values[i])
			} else if value.Valid {
				_m.TitleTemplate = value.String
			}
		case youtubeconfig.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case youtubeconfig.FieldAddChapters:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field add_chapters", values[i])
			} else if value.Valid {
				_m.AddChapters = value.Bool
			}
		case youtubeconfig.FieldNotifySubscribers:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field notify_subscribers", values[i])
			} else if value.Valid {
				_m.NotifySubscribers = value.Bool
			}
		case youtubeconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case youtubeconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case youtubeconfig.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field channel_youtube_config", values[i])
			} else if value.Valid {
				_m.channel_youtube_config = new(uuid.UUID)
				*_m.channel_youtube_config = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the YoutubeConfig.
// This includes values selected through modifiers, order, etc.
func (_m *YoutubeConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the YoutubeConfig entity.
func (_m *YoutubeConfig) QueryChannel() *ChannelQuery {
	return NewYoutubeConfigClient(_m.config).QueryChannel(_m)
}

// QueryPlaylistMappings queries the "playlist_mappings" edge of the YoutubeConfig entity.
func (_m *YoutubeConfig) QueryPlaylistMappings() *YoutubePlaylistMappingQuery {
	return NewYoutubeConfigClient(_m.config).QueryPlaylistMappings(_m)
}

// Update returns a builder for updating this YoutubeConfig.
// Note that you need to call YoutubeConfig.Unwrap() before calling this method if this YoutubeConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *YoutubeConfig) Update() *YoutubeConfigUpdateOne {
	return NewYoutubeConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the YoutubeConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *YoutubeConfig) Unwrap() *YoutubeConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: YoutubeConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *YoutubeConfig) String() string {
	var builder strings.Builder
	builder.WriteString("YoutubeConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("upload_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.UploadEnabled))
	builder.WriteString(", ")
	builder.WriteString("default_privacy=")
	builder.WriteString(_m.DefaultPrivacy)
	builder.WriteString(", ")
	builder.WriteString("default_category_id=")
	builder.WriteString(_m.DefaultCategoryID)
	builder.WriteString(", ")
	builder.WriteString("description_template=")
	builder.WriteString(_m.DescriptionTemplate)
	builder.WriteString(", ")
	builder.WriteString("title_template=")
	builder.WriteString(_m.TitleTemplate)
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	builder.WriteString("add_chapters=")
	builder.WriteString(fmt.Sprintf("%v", _m.AddChapters))
	builder.WriteString(", ")
	builder.WriteString("notify_subscribers=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotifySubscribers))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// YoutubeConfigs is a parsable slice of YoutubeConfig.
type YoutubeConfigs []*YoutubeConfig
