// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/youtubecredential"
)

// YoutubeCredential is the model entity for the YoutubeCredential schema.
type YoutubeCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OAuth2 access token for YouTube API
	AccessToken string `json:"-"`
	// OAuth2 refresh token for YouTube API
	RefreshToken string `json:"-"`
	// TokenType holds the value of the "token_type" field.
	TokenType string `json:"token_type,omitempty"`
	// Token expiration time
	Expiry time.Time `json:"expiry,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*YoutubeCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case youtubecredential.FieldAccessToken, youtubecredential.FieldRefreshToken, youtubecredential.FieldTokenType:
			values[i] = new(sql.NullString)
		case youtubecredential.FieldExpiry, youtubecredential.FieldUpdatedAt, youtubecredential.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case youtubecredential.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the YoutubeCredential fields.
func (_m *YoutubeCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case youtubecredential.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case youtubecredential.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				_m.AccessToken = value.String
			}
		case youtubecredential.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				_m.RefreshToken = value.String
			}
		case youtubecredential.FieldTokenType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_type", values[i])
			} else if value.Valid {
				_m.TokenType = value.String
			}
		case youtubecredential.FieldExpiry:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiry", values[i])
			} else if value.Valid {
				_m.Expiry = value.Time
			}
		case youtubecredential.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case youtubecredential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the YoutubeCredential.
// This includes values selected through modifiers, order, etc.
func (_m *YoutubeCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this YoutubeCredential.
// Note that you need to call YoutubeCredential.Unwrap() before calling this method if this YoutubeCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *YoutubeCredential) Update() *YoutubeCredentialUpdateOne {
	return NewYoutubeCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the YoutubeCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *YoutubeCredential) Unwrap() *YoutubeCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: YoutubeCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *YoutubeCredential) String() string {
	var builder strings.Builder
	builder.WriteString("YoutubeCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("access_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("refresh_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("token_type=")
	builder.WriteString(_m.TokenType)
	builder.WriteString(", ")
	builder.WriteString("expiry=")
	builder.WriteString(_m.Expiry.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// YoutubeCredentials is a parsable slice of YoutubeCredential.
type YoutubeCredentials []*YoutubeCredential
