// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/vod"
	"github.com/zibbp/ganymede/ent/youtubeupload"
)

// YoutubeUploadCreate is the builder for creating a YoutubeUpload entity.
type YoutubeUploadCreate struct {
	config
	mutation *YoutubeUploadMutation
	hooks    []Hook
}

// SetYoutubeVideoID sets the "youtube_video_id" field.
func (_c *YoutubeUploadCreate) SetYoutubeVideoID(v string) *YoutubeUploadCreate {
	_c.mutation.SetYoutubeVideoID(v)
	return _c
}

// SetNillableYoutubeVideoID sets the "youtube_video_id" field if the given value is not nil.
func (_c *YoutubeUploadCreate) SetNillableYoutubeVideoID(v *string) *YoutubeUploadCreate {
	if v != nil {
		_c.SetYoutubeVideoID(*v)
	}
	return _c
}

// SetYoutubeURL sets the "youtube_url" field.
func (_c *YoutubeUploadCreate) SetYoutubeURL(v string) *YoutubeUploadCreate {
	_c.mutation.SetYoutubeURL(v)
	return _c
}

// SetNillableYoutubeURL sets the "youtube_url" field if the given value is not nil.
func (_c *YoutubeUploadCreate) SetNillableYoutubeURL(v *string) *YoutubeUploadCreate {
	if v != nil {
		_c.SetYoutubeURL(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *YoutubeUploadCreate) SetStatus(v string) *YoutubeUploadCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *YoutubeUploadCreate) SetNillableStatus(v *string) *YoutubeUploadCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *YoutubeUploadCreate) SetErrorMessage(v string) *YoutubeUploadCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *YoutubeUploadCreate) SetNillableErrorMessage(v *string) *YoutubeUploadCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *YoutubeUploadCreate) SetRetryCount(v int) *YoutubeUploadCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *YoutubeUploadCreate) SetNillableRetryCount(v *int) *YoutubeUploadCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetUploadedAt sets the "uploaded_at" field.
func (_c *YoutubeUploadCreate) SetUploadedAt(v time.Time) *YoutubeUploadCreate {
	_c.mutation.SetUploadedAt(v)
	return _c
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (_c *YoutubeUploadCreate) SetNillableUploadedAt(v *time.Time) *YoutubeUploadCreate {
	if v != nil {
		_c.SetUploadedAt(*v)
	}
	return _c
}

// SetPlaylistIds sets the "playlist_ids" field.
func (_c *YoutubeUploadCreate) SetPlaylistIds(v []string) *YoutubeUploadCreate {
	_c.mutation.SetPlaylistIds(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *YoutubeUploadCreate) SetUpdatedAt(v time.Time) *YoutubeUploadCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *YoutubeUploadCreate) SetNillableUpdatedAt(v *time.Time) *YoutubeUploadCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *YoutubeUploadCreate) SetCreatedAt(v time.Time) *YoutubeUploadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *YoutubeUploadCreate) SetNillableCreatedAt(v *time.Time) *YoutubeUploadCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *YoutubeUploadCreate) SetID(v uuid.UUID) *YoutubeUploadCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *YoutubeUploadCreate) SetNillableID(v *uuid.UUID) *YoutubeUploadCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetVodID sets the "vod" edge to the Vod entity by ID.
func (_c *YoutubeUploadCreate) SetVodID(id uuid.UUID) *YoutubeUploadCreate {
	_c.mutation.SetVodID(id)
	return _c
}

// SetVod sets the "vod" edge to the Vod entity.
func (_c *YoutubeUploadCreate) SetVod(v *Vod) *YoutubeUploadCreate {
	return _c.SetVodID(v.ID)
}

// Mutation returns the YoutubeUploadMutation object of the builder.
func (_c *YoutubeUploadCreate) Mutation() *YoutubeUploadMutation {
	return _c.mutation
}

// Save creates the YoutubeUpload in the database.
func (_c *YoutubeUploadCreate) Save(ctx context.Context) (*YoutubeUpload, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *YoutubeUploadCreate) SaveX(ctx context.Context) *YoutubeUpload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *YoutubeUploadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *YoutubeUploadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *YoutubeUploadCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := youtubeupload.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := youtubeupload.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := youtubeupload.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := youtubeupload.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := youtubeupload.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *YoutubeUploadCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "YoutubeUpload.status"`)}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "YoutubeUpload.retry_count"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "YoutubeUpload.updated_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "YoutubeUpload.created_at"`)}
	}
	if len(_c.mutation.VodIDs()) == 0 {
		return &ValidationError{Name: "vod", err: errors.New(`ent: missing required edge "YoutubeUpload.vod"`)}
	}
	return nil
}

func (_c *YoutubeUploadCreate) sqlSave(ctx context.Context) (*YoutubeUpload, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *YoutubeUploadCreate) createSpec() (*YoutubeUpload, *sqlgraph.CreateSpec) {
	var (
		_node = &YoutubeUpload{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(youtubeupload.Table, sqlgraph.NewFieldSpec(youtubeupload.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.YoutubeVideoID(); ok {
		_spec.SetField(youtubeupload.FieldYoutubeVideoID, field.TypeString, value)
		_node.YoutubeVideoID = value
	}
	if value, ok := _c.mutation.YoutubeURL(); ok {
		_spec.SetField(youtubeupload.FieldYoutubeURL, field.TypeString, value)
		_node.YoutubeURL = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(youtubeupload.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(youtubeupload.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(youtubeupload.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.UploadedAt(); ok {
		_spec.SetField(youtubeupload.FieldUploadedAt, field.TypeTime, value)
		_node.UploadedAt = value
	}
	if value, ok := _c.mutation.PlaylistIds(); ok {
		_spec.SetField(youtubeupload.FieldPlaylistIds, field.TypeJSON, value)
		_node.PlaylistIds = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(youtubeupload.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(youtubeupload.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.VodIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   youtubeupload.VodTable,
			Columns: []string{youtubeupload.VodColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vod.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.vod_youtube_upload = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// YoutubeUploadCreateBulk is the builder for creating many YoutubeUpload entities in bulk.
type YoutubeUploadCreateBulk struct {
	config
	err      error
	builders []*YoutubeUploadCreate
}

// Save creates the YoutubeUpload entities in the database.
func (_c *YoutubeUploadCreateBulk) Save(ctx context.Context) ([]*YoutubeUpload, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*YoutubeUpload, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*YoutubeUploadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *YoutubeUploadCreateBulk) SaveX(ctx context.Context) []*YoutubeUpload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *YoutubeUploadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *YoutubeUploadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
