// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zibbp/ganymede/ent/predicate"
	"github.com/zibbp/ganymede/ent/youtubecredential"
)

// YoutubeCredentialUpdate is the builder for updating YoutubeCredential entities.
type YoutubeCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *YoutubeCredentialMutation
}

// Where appends a list predicates to the YoutubeCredentialUpdate builder.
func (_u *YoutubeCredentialUpdate) Where(ps ...predicate.YoutubeCredential) *YoutubeCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *YoutubeCredentialUpdate) SetAccessToken(v string) *YoutubeCredentialUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *YoutubeCredentialUpdate) SetNillableAccessToken(v *string) *YoutubeCredentialUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *YoutubeCredentialUpdate) SetRefreshToken(v string) *YoutubeCredentialUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *YoutubeCredentialUpdate) SetNillableRefreshToken(v *string) *YoutubeCredentialUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// SetTokenType sets the "token_type" field.
func (_u *YoutubeCredentialUpdate) SetTokenType(v string) *YoutubeCredentialUpdate {
	_u.mutation.SetTokenType(v)
	return _u
}

// SetNillableTokenType sets the "token_type" field if the given value is not nil.
func (_u *YoutubeCredentialUpdate) SetNillableTokenType(v *string) *YoutubeCredentialUpdate {
	if v != nil {
		_u.SetTokenType(*v)
	}
	return _u
}

// SetExpiry sets the "expiry" field.
func (_u *YoutubeCredentialUpdate) SetExpiry(v time.Time) *YoutubeCredentialUpdate {
	_u.mutation.SetExpiry(v)
	return _u
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (_u *YoutubeCredentialUpdate) SetNillableExpiry(v *time.Time) *YoutubeCredentialUpdate {
	if v != nil {
		_u.SetExpiry(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *YoutubeCredentialUpdate) SetUpdatedAt(v time.Time) *YoutubeCredentialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the YoutubeCredentialMutation object of the builder.
func (_u *YoutubeCredentialUpdate) Mutation() *YoutubeCredentialMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *YoutubeCredentialUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *YoutubeCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *YoutubeCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *YoutubeCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *YoutubeCredentialUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := youtubecredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *YoutubeCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(youtubecredential.Table, youtubecredential.Columns, sqlgraph.NewFieldSpec(youtubecredential.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(youtubecredential.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(youtubecredential.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenType(); ok {
		_spec.SetField(youtubecredential.FieldTokenType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Expiry(); ok {
		_spec.SetField(youtubecredential.FieldExpiry, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(youtubecredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{youtubecredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// YoutubeCredentialUpdateOne is the builder for updating a single YoutubeCredential entity.
type YoutubeCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *YoutubeCredentialMutation
}

// SetAccessToken sets the "access_token" field.
func (_u *YoutubeCredentialUpdateOne) SetAccessToken(v string) *YoutubeCredentialUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *YoutubeCredentialUpdateOne) SetNillableAccessToken(v *string) *YoutubeCredentialUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *YoutubeCredentialUpdateOne) SetRefreshToken(v string) *YoutubeCredentialUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *YoutubeCredentialUpdateOne) SetNillableRefreshToken(v *string) *YoutubeCredentialUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// SetTokenType sets the "token_type" field.
func (_u *YoutubeCredentialUpdateOne) SetTokenType(v string) *YoutubeCredentialUpdateOne {
	_u.mutation.SetTokenType(v)
	return _u
}

// SetNillableTokenType sets the "token_type" field if the given value is not nil.
func (_u *YoutubeCredentialUpdateOne) SetNillableTokenType(v *string) *YoutubeCredentialUpdateOne {
	if v != nil {
		_u.SetTokenType(*v)
	}
	return _u
}

// SetExpiry sets the "expiry" field.
func (_u *YoutubeCredentialUpdateOne) SetExpiry(v time.Time) *YoutubeCredentialUpdateOne {
	_u.mutation.SetExpiry(v)
	return _u
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (_u *YoutubeCredentialUpdateOne) SetNillableExpiry(v *time.Time) *YoutubeCredentialUpdateOne {
	if v != nil {
		_u.SetExpiry(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *YoutubeCredentialUpdateOne) SetUpdatedAt(v time.Time) *YoutubeCredentialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the YoutubeCredentialMutation object of the builder.
func (_u *YoutubeCredentialUpdateOne) Mutation() *YoutubeCredentialMutation {
	return _u.mutation
}

// Where appends a list predicates to the YoutubeCredentialUpdate builder.
func (_u *YoutubeCredentialUpdateOne) Where(ps ...predicate.YoutubeCredential) *YoutubeCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *YoutubeCredentialUpdateOne) Select(field string, fields ...string) *YoutubeCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated YoutubeCredential entity.
func (_u *YoutubeCredentialUpdateOne) Save(ctx context.Context) (*YoutubeCredential, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *YoutubeCredentialUpdateOne) SaveX(ctx context.Context) *YoutubeCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *YoutubeCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *YoutubeCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *YoutubeCredentialUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := youtubecredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *YoutubeCredentialUpdateOne) sqlSave(ctx context.Context) (_node *YoutubeCredential, err error) {
	_spec := sqlgraph.NewUpdateSpec(youtubecredential.Table, youtubecredential.Columns, sqlgraph.NewFieldSpec(youtubecredential.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "YoutubeCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, youtubecredential.FieldID)
		for _, f := range fields {
			if !youtubecredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != youtubecredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(youtubecredential.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(youtubecredential.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenType(); ok {
		_spec.SetField(youtubecredential.FieldTokenType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Expiry(); ok {
		_spec.SetField(youtubecredential.FieldExpiry, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(youtubecredential.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &YoutubeCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{youtubecredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
