// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/youtubecredential"
)

// YoutubeCredentialCreate is the builder for creating a YoutubeCredential entity.
type YoutubeCredentialCreate struct {
	config
	mutation *YoutubeCredentialMutation
	hooks    []Hook
}

// SetAccessToken sets the "access_token" field.
func (_c *YoutubeCredentialCreate) SetAccessToken(v string) *YoutubeCredentialCreate {
	_c.mutation.SetAccessToken(v)
	return _c
}

// SetRefreshToken sets the "refresh_token" field.
func (_c *YoutubeCredentialCreate) SetRefreshToken(v string) *YoutubeCredentialCreate {
	_c.mutation.SetRefreshToken(v)
	return _c
}

// SetTokenType sets the "token_type" field.
func (_c *YoutubeCredentialCreate) SetTokenType(v string) *YoutubeCredentialCreate {
	_c.mutation.SetTokenType(v)
	return _c
}

// SetNillableTokenType sets the "token_type" field if the given value is not nil.
func (_c *YoutubeCredentialCreate) SetNillableTokenType(v *string) *YoutubeCredentialCreate {
	if v != nil {
		_c.SetTokenType(*v)
	}
	return _c
}

// SetExpiry sets the "expiry" field.
func (_c *YoutubeCredentialCreate) SetExpiry(v time.Time) *YoutubeCredentialCreate {
	_c.mutation.SetExpiry(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *YoutubeCredentialCreate) SetUpdatedAt(v time.Time) *YoutubeCredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *YoutubeCredentialCreate) SetNillableUpdatedAt(v *time.Time) *YoutubeCredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *YoutubeCredentialCreate) SetCreatedAt(v time.Time) *YoutubeCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *YoutubeCredentialCreate) SetNillableCreatedAt(v *time.Time) *YoutubeCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *YoutubeCredentialCreate) SetID(v uuid.UUID) *YoutubeCredentialCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *YoutubeCredentialCreate) SetNillableID(v *uuid.UUID) *YoutubeCredentialCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the YoutubeCredentialMutation object of the builder.
func (_c *YoutubeCredentialCreate) Mutation() *YoutubeCredentialMutation {
	return _c.mutation
}

// Save creates the YoutubeCredential in the database.
func (_c *YoutubeCredentialCreate) Save(ctx context.Context) (*YoutubeCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *YoutubeCredentialCreate) SaveX(ctx context.Context) *YoutubeCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *YoutubeCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *YoutubeCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *YoutubeCredentialCreate) defaults() {
	if _, ok := _c.mutation.TokenType(); !ok {
		v := youtubecredential.DefaultTokenType
		_c.mutation.SetTokenType(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := youtubecredential.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := youtubecredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := youtubecredential.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *YoutubeCredentialCreate) check() error {
	if _, ok := _c.mutation.AccessToken(); !ok {
		return &ValidationError{Name: "access_token", err: errors.New(`ent: missing required field "YoutubeCredential.access_token"`)}
	}
	if _, ok := _c.mutation.RefreshToken(); !ok {
		return &ValidationError{Name: "refresh_token", err: errors.New(`ent: missing required field "YoutubeCredential.refresh_token"`)}
	}
	if _, ok := _c.mutation.TokenType(); !ok {
		return &ValidationError{Name: "token_type", err: errors.New(`ent: missing required field "YoutubeCredential.token_type"`)}
	}
	if _, ok := _c.mutation.Expiry(); !ok {
		return &ValidationError{Name: "expiry", err: errors.New(`ent: missing required field "YoutubeCredential.expiry"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "YoutubeCredential.updated_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "YoutubeCredential.created_at"`)}
	}
	return nil
}

func (_c *YoutubeCredentialCreate) sqlSave(ctx context.Context) (*YoutubeCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *YoutubeCredentialCreate) createSpec() (*YoutubeCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &YoutubeCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(youtubecredential.Table, sqlgraph.NewFieldSpec(youtubecredential.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.AccessToken(); ok {
		_spec.SetField(youtubecredential.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := _c.mutation.RefreshToken(); ok {
		_spec.SetField(youtubecredential.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := _c.mutation.TokenType(); ok {
		_spec.SetField(youtubecredential.FieldTokenType, field.TypeString, value)
		_node.TokenType = value
	}
	if value, ok := _c.mutation.Expiry(); ok {
		_spec.SetField(youtubecredential.FieldExpiry, field.TypeTime, value)
		_node.Expiry = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(youtubecredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(youtubecredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// YoutubeCredentialCreateBulk is the builder for creating many YoutubeCredential entities in bulk.
type YoutubeCredentialCreateBulk struct {
	config
	err      error
	builders []*YoutubeCredentialCreate
}

// Save creates the YoutubeCredential entities in the database.
func (_c *YoutubeCredentialCreateBulk) Save(ctx context.Context) ([]*YoutubeCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*YoutubeCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*YoutubeCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *YoutubeCredentialCreateBulk) SaveX(ctx context.Context) []*YoutubeCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *YoutubeCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *YoutubeCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
