// Code generated by ent, DO NOT EDIT.

package youtubeupload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLTE(FieldID, id))
}

// YoutubeVideoID applies equality check predicate on the "youtube_video_id" field. It's identical to YoutubeVideoIDEQ.
func YoutubeVideoID(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldYoutubeVideoID, v))
}

// YoutubeURL applies equality check predicate on the "youtube_url" field. It's identical to YoutubeURLEQ.
func YoutubeURL(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldYoutubeURL, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldStatus, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldErrorMessage, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldRetryCount, v))
}

// UploadedAt applies equality check predicate on the "uploaded_at" field. It's identical to UploadedAtEQ.
func UploadedAt(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldUploadedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldCreatedAt, v))
}

// YoutubeVideoIDEQ applies the EQ predicate on the "youtube_video_id" field.
func YoutubeVideoIDEQ(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldYoutubeVideoID, v))
}

// YoutubeVideoIDNEQ applies the NEQ predicate on the "youtube_video_id" field.
func YoutubeVideoIDNEQ(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNEQ(FieldYoutubeVideoID, v))
}

// YoutubeVideoIDIn applies the In predicate on the "youtube_video_id" field.
func YoutubeVideoIDIn(vs ...string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIn(FieldYoutubeVideoID, vs...))
}

// YoutubeVideoIDNotIn applies the NotIn predicate on the "youtube_video_id" field.
func YoutubeVideoIDNotIn(vs ...string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotIn(FieldYoutubeVideoID, vs...))
}

// YoutubeVideoIDGT applies the GT predicate on the "youtube_video_id" field.
func YoutubeVideoIDGT(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGT(FieldYoutubeVideoID, v))
}

// YoutubeVideoIDGTE applies the GTE predicate on the "youtube_video_id" field.
func YoutubeVideoIDGTE(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGTE(FieldYoutubeVideoID, v))
}

// YoutubeVideoIDLT applies the LT predicate on the "youtube_video_id" field.
func YoutubeVideoIDLT(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLT(FieldYoutubeVideoID, v))
}

// YoutubeVideoIDLTE applies the LTE predicate on the "youtube_video_id" field.
func YoutubeVideoIDLTE(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLTE(FieldYoutubeVideoID, v))
}

// YoutubeVideoIDContains applies the Contains predicate on the "youtube_video_id" field.
func YoutubeVideoIDContains(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldContains(FieldYoutubeVideoID, v))
}

// YoutubeVideoIDHasPrefix applies the HasPrefix predicate on the "youtube_video_id" field.
func YoutubeVideoIDHasPrefix(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldHasPrefix(FieldYoutubeVideoID, v))
}

// YoutubeVideoIDHasSuffix applies the HasSuffix predicate on the "youtube_video_id" field.
func YoutubeVideoIDHasSuffix(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldHasSuffix(FieldYoutubeVideoID, v))
}

// YoutubeVideoIDIsNil applies the IsNil predicate on the "youtube_video_id" field.
func YoutubeVideoIDIsNil() predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIsNull(FieldYoutubeVideoID))
}

// YoutubeVideoIDNotNil applies the NotNil predicate on the "youtube_video_id" field.
func YoutubeVideoIDNotNil() predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotNull(FieldYoutubeVideoID))
}

// YoutubeVideoIDEqualFold applies the EqualFold predicate on the "youtube_video_id" field.
func YoutubeVideoIDEqualFold(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEqualFold(FieldYoutubeVideoID, v))
}

// YoutubeVideoIDContainsFold applies the ContainsFold predicate on the "youtube_video_id" field.
func YoutubeVideoIDContainsFold(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldContainsFold(FieldYoutubeVideoID, v))
}

// YoutubeURLEQ applies the EQ predicate on the "youtube_url" field.
func YoutubeURLEQ(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldYoutubeURL, v))
}

// YoutubeURLNEQ applies the NEQ predicate on the "youtube_url" field.
func YoutubeURLNEQ(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNEQ(FieldYoutubeURL, v))
}

// YoutubeURLIn applies the In predicate on the "youtube_url" field.
func YoutubeURLIn(vs ...string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIn(FieldYoutubeURL, vs...))
}

// YoutubeURLNotIn applies the NotIn predicate on the "youtube_url" field.
func YoutubeURLNotIn(vs ...string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotIn(FieldYoutubeURL, vs...))
}

// YoutubeURLGT applies the GT predicate on the "youtube_url" field.
func YoutubeURLGT(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGT(FieldYoutubeURL, v))
}

// YoutubeURLGTE applies the GTE predicate on the "youtube_url" field.
func YoutubeURLGTE(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGTE(FieldYoutubeURL, v))
}

// YoutubeURLLT applies the LT predicate on the "youtube_url" field.
func YoutubeURLLT(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLT(FieldYoutubeURL, v))
}

// YoutubeURLLTE applies the LTE predicate on the "youtube_url" field.
func YoutubeURLLTE(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLTE(FieldYoutubeURL, v))
}

// YoutubeURLContains applies the Contains predicate on the "youtube_url" field.
func YoutubeURLContains(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldContains(FieldYoutubeURL, v))
}

// YoutubeURLHasPrefix applies the HasPrefix predicate on the "youtube_url" field.
func YoutubeURLHasPrefix(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldHasPrefix(FieldYoutubeURL, v))
}

// YoutubeURLHasSuffix applies the HasSuffix predicate on the "youtube_url" field.
func YoutubeURLHasSuffix(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldHasSuffix(FieldYoutubeURL, v))
}

// YoutubeURLIsNil applies the IsNil predicate on the "youtube_url" field.
func YoutubeURLIsNil() predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIsNull(FieldYoutubeURL))
}

// YoutubeURLNotNil applies the NotNil predicate on the "youtube_url" field.
func YoutubeURLNotNil() predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotNull(FieldYoutubeURL))
}

// YoutubeURLEqualFold applies the EqualFold predicate on the "youtube_url" field.
func YoutubeURLEqualFold(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEqualFold(FieldYoutubeURL, v))
}

// YoutubeURLContainsFold applies the ContainsFold predicate on the "youtube_url" field.
func YoutubeURLContainsFold(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldContainsFold(FieldYoutubeURL, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldContainsFold(FieldErrorMessage, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLTE(FieldRetryCount, v))
}

// UploadedAtEQ applies the EQ predicate on the "uploaded_at" field.
func UploadedAtEQ(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldUploadedAt, v))
}

// UploadedAtNEQ applies the NEQ predicate on the "uploaded_at" field.
func UploadedAtNEQ(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNEQ(FieldUploadedAt, v))
}

// UploadedAtIn applies the In predicate on the "uploaded_at" field.
func UploadedAtIn(vs ...time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIn(FieldUploadedAt, vs...))
}

// UploadedAtNotIn applies the NotIn predicate on the "uploaded_at" field.
func UploadedAtNotIn(vs ...time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotIn(FieldUploadedAt, vs...))
}

// UploadedAtGT applies the GT predicate on the "uploaded_at" field.
func UploadedAtGT(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGT(FieldUploadedAt, v))
}

// UploadedAtGTE applies the GTE predicate on the "uploaded_at" field.
func UploadedAtGTE(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGTE(FieldUploadedAt, v))
}

// UploadedAtLT applies the LT predicate on the "uploaded_at" field.
func UploadedAtLT(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLT(FieldUploadedAt, v))
}

// UploadedAtLTE applies the LTE predicate on the "uploaded_at" field.
func UploadedAtLTE(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLTE(FieldUploadedAt, v))
}

// UploadedAtIsNil applies the IsNil predicate on the "uploaded_at" field.
func UploadedAtIsNil() predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIsNull(FieldUploadedAt))
}

// UploadedAtNotNil applies the NotNil predicate on the "uploaded_at" field.
func UploadedAtNotNil() predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotNull(FieldUploadedAt))
}

// PlaylistIdsIsNil applies the IsNil predicate on the "playlist_ids" field.
func PlaylistIdsIsNil() predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIsNull(FieldPlaylistIds))
}

// PlaylistIdsNotNil applies the NotNil predicate on the "playlist_ids" field.
func PlaylistIdsNotNil() predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotNull(FieldPlaylistIds))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.FieldLTE(FieldCreatedAt, v))
}

// HasVod applies the HasEdge predicate on the "vod" edge.
func HasVod() predicate.YoutubeUpload {
	return predicate.YoutubeUpload(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, VodTable, VodColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVodWith applies the HasEdge predicate on the "vod" edge with a given conditions (other predicates).
func HasVodWith(preds ...predicate.Vod) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(func(s *sql.Selector) {
		step := newVodStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.YoutubeUpload) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.YoutubeUpload) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.YoutubeUpload) predicate.YoutubeUpload {
	return predicate.YoutubeUpload(sql.NotPredicates(p))
}
