// Code generated by ent, DO NOT EDIT.

package youtubeupload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the youtubeupload type in the database.
	Label = "youtube_upload"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldYoutubeVideoID holds the string denoting the youtube_video_id field in the database.
	FieldYoutubeVideoID = "youtube_video_id"
	// FieldYoutubeURL holds the string denoting the youtube_url field in the database.
	FieldYoutubeURL = "youtube_url"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldUploadedAt holds the string denoting the uploaded_at field in the database.
	FieldUploadedAt = "uploaded_at"
	// FieldPlaylistIds holds the string denoting the playlist_ids field in the database.
	FieldPlaylistIds = "playlist_ids"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeVod holds the string denoting the vod edge name in mutations.
	EdgeVod = "vod"
	// Table holds the table name of the youtubeupload in the database.
	Table = "youtube_uploads"
	// VodTable is the table that holds the vod relation/edge.
	VodTable = "youtube_uploads"
	// VodInverseTable is the table name for the Vod entity.
	// It exists in this package in order to avoid circular dependency with the "vod" package.
	VodInverseTable = "vods"
	// VodColumn is the table column denoting the vod relation/edge.
	VodColumn = "vod_youtube_upload"
)

// Columns holds all SQL columns for youtubeupload fields.
var Columns = []string{
	FieldID,
	FieldYoutubeVideoID,
	FieldYoutubeURL,
	FieldStatus,
	FieldErrorMessage,
	FieldRetryCount,
	FieldUploadedAt,
	FieldPlaylistIds,
	FieldUpdatedAt,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "youtube_uploads"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"vod_youtube_upload",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the YoutubeUpload queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByYoutubeVideoID orders the results by the youtube_video_id field.
func ByYoutubeVideoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYoutubeVideoID, opts...).ToFunc()
}

// ByYoutubeURL orders the results by the youtube_url field.
func ByYoutubeURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldYoutubeURL, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByUploadedAt orders the results by the uploaded_at field.
func ByUploadedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByVodField orders the results by vod field.
func ByVodField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVodStep(), sql.OrderByField(field, opts...))
	}
}
func newVodStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VodInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, VodTable, VodColumn),
	)
}
