// Code generated by ent, DO NOT EDIT.

package youtubeplaylistmapping

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLTE(FieldID, id))
}

// GameCategory applies equality check predicate on the "game_category" field. It's identical to GameCategoryEQ.
func GameCategory(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldGameCategory, v))
}

// PlaylistID applies equality check predicate on the "playlist_id" field. It's identical to PlaylistIDEQ.
func PlaylistID(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldPlaylistID, v))
}

// PlaylistName applies equality check predicate on the "playlist_name" field. It's identical to PlaylistNameEQ.
func PlaylistName(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldPlaylistName, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldPriority, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldCreatedAt, v))
}

// GameCategoryEQ applies the EQ predicate on the "game_category" field.
func GameCategoryEQ(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldGameCategory, v))
}

// GameCategoryNEQ applies the NEQ predicate on the "game_category" field.
func GameCategoryNEQ(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNEQ(FieldGameCategory, v))
}

// GameCategoryIn applies the In predicate on the "game_category" field.
func GameCategoryIn(vs ...string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldIn(FieldGameCategory, vs...))
}

// GameCategoryNotIn applies the NotIn predicate on the "game_category" field.
func GameCategoryNotIn(vs ...string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNotIn(FieldGameCategory, vs...))
}

// GameCategoryGT applies the GT predicate on the "game_category" field.
func GameCategoryGT(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGT(FieldGameCategory, v))
}

// GameCategoryGTE applies the GTE predicate on the "game_category" field.
func GameCategoryGTE(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGTE(FieldGameCategory, v))
}

// GameCategoryLT applies the LT predicate on the "game_category" field.
func GameCategoryLT(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLT(FieldGameCategory, v))
}

// GameCategoryLTE applies the LTE predicate on the "game_category" field.
func GameCategoryLTE(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLTE(FieldGameCategory, v))
}

// GameCategoryContains applies the Contains predicate on the "game_category" field.
func GameCategoryContains(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldContains(FieldGameCategory, v))
}

// GameCategoryHasPrefix applies the HasPrefix predicate on the "game_category" field.
func GameCategoryHasPrefix(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldHasPrefix(FieldGameCategory, v))
}

// GameCategoryHasSuffix applies the HasSuffix predicate on the "game_category" field.
func GameCategoryHasSuffix(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldHasSuffix(FieldGameCategory, v))
}

// GameCategoryEqualFold applies the EqualFold predicate on the "game_category" field.
func GameCategoryEqualFold(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEqualFold(FieldGameCategory, v))
}

// GameCategoryContainsFold applies the ContainsFold predicate on the "game_category" field.
func GameCategoryContainsFold(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldContainsFold(FieldGameCategory, v))
}

// PlaylistIDEQ applies the EQ predicate on the "playlist_id" field.
func PlaylistIDEQ(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldPlaylistID, v))
}

// PlaylistIDNEQ applies the NEQ predicate on the "playlist_id" field.
func PlaylistIDNEQ(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNEQ(FieldPlaylistID, v))
}

// PlaylistIDIn applies the In predicate on the "playlist_id" field.
func PlaylistIDIn(vs ...string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldIn(FieldPlaylistID, vs...))
}

// PlaylistIDNotIn applies the NotIn predicate on the "playlist_id" field.
func PlaylistIDNotIn(vs ...string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNotIn(FieldPlaylistID, vs...))
}

// PlaylistIDGT applies the GT predicate on the "playlist_id" field.
func PlaylistIDGT(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGT(FieldPlaylistID, v))
}

// PlaylistIDGTE applies the GTE predicate on the "playlist_id" field.
func PlaylistIDGTE(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGTE(FieldPlaylistID, v))
}

// PlaylistIDLT applies the LT predicate on the "playlist_id" field.
func PlaylistIDLT(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLT(FieldPlaylistID, v))
}

// PlaylistIDLTE applies the LTE predicate on the "playlist_id" field.
func PlaylistIDLTE(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLTE(FieldPlaylistID, v))
}

// PlaylistIDContains applies the Contains predicate on the "playlist_id" field.
func PlaylistIDContains(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldContains(FieldPlaylistID, v))
}

// PlaylistIDHasPrefix applies the HasPrefix predicate on the "playlist_id" field.
func PlaylistIDHasPrefix(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldHasPrefix(FieldPlaylistID, v))
}

// PlaylistIDHasSuffix applies the HasSuffix predicate on the "playlist_id" field.
func PlaylistIDHasSuffix(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldHasSuffix(FieldPlaylistID, v))
}

// PlaylistIDEqualFold applies the EqualFold predicate on the "playlist_id" field.
func PlaylistIDEqualFold(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEqualFold(FieldPlaylistID, v))
}

// PlaylistIDContainsFold applies the ContainsFold predicate on the "playlist_id" field.
func PlaylistIDContainsFold(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldContainsFold(FieldPlaylistID, v))
}

// PlaylistNameEQ applies the EQ predicate on the "playlist_name" field.
func PlaylistNameEQ(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldPlaylistName, v))
}

// PlaylistNameNEQ applies the NEQ predicate on the "playlist_name" field.
func PlaylistNameNEQ(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNEQ(FieldPlaylistName, v))
}

// PlaylistNameIn applies the In predicate on the "playlist_name" field.
func PlaylistNameIn(vs ...string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldIn(FieldPlaylistName, vs...))
}

// PlaylistNameNotIn applies the NotIn predicate on the "playlist_name" field.
func PlaylistNameNotIn(vs ...string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNotIn(FieldPlaylistName, vs...))
}

// PlaylistNameGT applies the GT predicate on the "playlist_name" field.
func PlaylistNameGT(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGT(FieldPlaylistName, v))
}

// PlaylistNameGTE applies the GTE predicate on the "playlist_name" field.
func PlaylistNameGTE(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGTE(FieldPlaylistName, v))
}

// PlaylistNameLT applies the LT predicate on the "playlist_name" field.
func PlaylistNameLT(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLT(FieldPlaylistName, v))
}

// PlaylistNameLTE applies the LTE predicate on the "playlist_name" field.
func PlaylistNameLTE(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLTE(FieldPlaylistName, v))
}

// PlaylistNameContains applies the Contains predicate on the "playlist_name" field.
func PlaylistNameContains(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldContains(FieldPlaylistName, v))
}

// PlaylistNameHasPrefix applies the HasPrefix predicate on the "playlist_name" field.
func PlaylistNameHasPrefix(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldHasPrefix(FieldPlaylistName, v))
}

// PlaylistNameHasSuffix applies the HasSuffix predicate on the "playlist_name" field.
func PlaylistNameHasSuffix(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldHasSuffix(FieldPlaylistName, v))
}

// PlaylistNameIsNil applies the IsNil predicate on the "playlist_name" field.
func PlaylistNameIsNil() predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldIsNull(FieldPlaylistName))
}

// PlaylistNameNotNil applies the NotNil predicate on the "playlist_name" field.
func PlaylistNameNotNil() predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNotNull(FieldPlaylistName))
}

// PlaylistNameEqualFold applies the EqualFold predicate on the "playlist_name" field.
func PlaylistNameEqualFold(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEqualFold(FieldPlaylistName, v))
}

// PlaylistNameContainsFold applies the ContainsFold predicate on the "playlist_name" field.
func PlaylistNameContainsFold(v string) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldContainsFold(FieldPlaylistName, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLTE(FieldPriority, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.FieldLTE(FieldCreatedAt, v))
}

// HasYoutubeConfig applies the HasEdge predicate on the "youtube_config" edge.
func HasYoutubeConfig() predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, YoutubeConfigTable, YoutubeConfigColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasYoutubeConfigWith applies the HasEdge predicate on the "youtube_config" edge with a given conditions (other predicates).
func HasYoutubeConfigWith(preds ...predicate.YoutubeConfig) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(func(s *sql.Selector) {
		step := newYoutubeConfigStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.YoutubePlaylistMapping) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.YoutubePlaylistMapping) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.YoutubePlaylistMapping) predicate.YoutubePlaylistMapping {
	return predicate.YoutubePlaylistMapping(sql.NotPredicates(p))
}
