// Code generated by ent, DO NOT EDIT.

package youtubeplaylistmapping

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the youtubeplaylistmapping type in the database.
	Label = "youtube_playlist_mapping"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGameCategory holds the string denoting the game_category field in the database.
	FieldGameCategory = "game_category"
	// FieldPlaylistID holds the string denoting the playlist_id field in the database.
	FieldPlaylistID = "playlist_id"
	// FieldPlaylistName holds the string denoting the playlist_name field in the database.
	FieldPlaylistName = "playlist_name"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeYoutubeConfig holds the string denoting the youtube_config edge name in mutations.
	EdgeYoutubeConfig = "youtube_config"
	// Table holds the table name of the youtubeplaylistmapping in the database.
	Table = "youtube_playlist_mappings"
	// YoutubeConfigTable is the table that holds the youtube_config relation/edge.
	YoutubeConfigTable = "youtube_playlist_mappings"
	// YoutubeConfigInverseTable is the table name for the YoutubeConfig entity.
	// It exists in this package in order to avoid circular dependency with the "youtubeconfig" package.
	YoutubeConfigInverseTable = "youtube_configs"
	// YoutubeConfigColumn is the table column denoting the youtube_config relation/edge.
	YoutubeConfigColumn = "youtube_config_playlist_mappings"
)

// Columns holds all SQL columns for youtubeplaylistmapping fields.
var Columns = []string{
	FieldID,
	FieldGameCategory,
	FieldPlaylistID,
	FieldPlaylistName,
	FieldPriority,
	FieldUpdatedAt,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "youtube_playlist_mappings"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"youtube_config_playlist_mappings",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the YoutubePlaylistMapping queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGameCategory orders the results by the game_category field.
func ByGameCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameCategory, opts...).ToFunc()
}

// ByPlaylistID orders the results by the playlist_id field.
func ByPlaylistID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaylistID, opts...).ToFunc()
}

// ByPlaylistName orders the results by the playlist_name field.
func ByPlaylistName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaylistName, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByYoutubeConfigField orders the results by youtube_config field.
func ByYoutubeConfigField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newYoutubeConfigStep(), sql.OrderByField(field, opts...))
	}
}
func newYoutubeConfigStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(YoutubeConfigInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, YoutubeConfigTable, YoutubeConfigColumn),
	)
}
