// Code generated by ent, DO NOT EDIT.

package youtubeconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/zibbp/ganymede/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLTE(FieldID, id))
}

// UploadEnabled applies equality check predicate on the "upload_enabled" field. It's identical to UploadEnabledEQ.
func UploadEnabled(v bool) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldUploadEnabled, v))
}

// DefaultPrivacy applies equality check predicate on the "default_privacy" field. It's identical to DefaultPrivacyEQ.
func DefaultPrivacy(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldDefaultPrivacy, v))
}

// DefaultCategoryID applies equality check predicate on the "default_category_id" field. It's identical to DefaultCategoryIDEQ.
func DefaultCategoryID(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldDefaultCategoryID, v))
}

// DescriptionTemplate applies equality check predicate on the "description_template" field. It's identical to DescriptionTemplateEQ.
func DescriptionTemplate(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldDescriptionTemplate, v))
}

// TitleTemplate applies equality check predicate on the "title_template" field. It's identical to TitleTemplateEQ.
func TitleTemplate(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldTitleTemplate, v))
}

// AddChapters applies equality check predicate on the "add_chapters" field. It's identical to AddChaptersEQ.
func AddChapters(v bool) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldAddChapters, v))
}

// NotifySubscribers applies equality check predicate on the "notify_subscribers" field. It's identical to NotifySubscribersEQ.
func NotifySubscribers(v bool) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldNotifySubscribers, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UploadEnabledEQ applies the EQ predicate on the "upload_enabled" field.
func UploadEnabledEQ(v bool) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldUploadEnabled, v))
}

// UploadEnabledNEQ applies the NEQ predicate on the "upload_enabled" field.
func UploadEnabledNEQ(v bool) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNEQ(FieldUploadEnabled, v))
}

// DefaultPrivacyEQ applies the EQ predicate on the "default_privacy" field.
func DefaultPrivacyEQ(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldDefaultPrivacy, v))
}

// DefaultPrivacyNEQ applies the NEQ predicate on the "default_privacy" field.
func DefaultPrivacyNEQ(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNEQ(FieldDefaultPrivacy, v))
}

// DefaultPrivacyIn applies the In predicate on the "default_privacy" field.
func DefaultPrivacyIn(vs ...string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldIn(FieldDefaultPrivacy, vs...))
}

// DefaultPrivacyNotIn applies the NotIn predicate on the "default_privacy" field.
func DefaultPrivacyNotIn(vs ...string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNotIn(FieldDefaultPrivacy, vs...))
}

// DefaultPrivacyGT applies the GT predicate on the "default_privacy" field.
func DefaultPrivacyGT(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGT(FieldDefaultPrivacy, v))
}

// DefaultPrivacyGTE applies the GTE predicate on the "default_privacy" field.
func DefaultPrivacyGTE(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGTE(FieldDefaultPrivacy, v))
}

// DefaultPrivacyLT applies the LT predicate on the "default_privacy" field.
func DefaultPrivacyLT(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLT(FieldDefaultPrivacy, v))
}

// DefaultPrivacyLTE applies the LTE predicate on the "default_privacy" field.
func DefaultPrivacyLTE(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLTE(FieldDefaultPrivacy, v))
}

// DefaultPrivacyContains applies the Contains predicate on the "default_privacy" field.
func DefaultPrivacyContains(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldContains(FieldDefaultPrivacy, v))
}

// DefaultPrivacyHasPrefix applies the HasPrefix predicate on the "default_privacy" field.
func DefaultPrivacyHasPrefix(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldHasPrefix(FieldDefaultPrivacy, v))
}

// DefaultPrivacyHasSuffix applies the HasSuffix predicate on the "default_privacy" field.
func DefaultPrivacyHasSuffix(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldHasSuffix(FieldDefaultPrivacy, v))
}

// DefaultPrivacyEqualFold applies the EqualFold predicate on the "default_privacy" field.
func DefaultPrivacyEqualFold(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEqualFold(FieldDefaultPrivacy, v))
}

// DefaultPrivacyContainsFold applies the ContainsFold predicate on the "default_privacy" field.
func DefaultPrivacyContainsFold(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldContainsFold(FieldDefaultPrivacy, v))
}

// DefaultCategoryIDEQ applies the EQ predicate on the "default_category_id" field.
func DefaultCategoryIDEQ(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldDefaultCategoryID, v))
}

// DefaultCategoryIDNEQ applies the NEQ predicate on the "default_category_id" field.
func DefaultCategoryIDNEQ(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNEQ(FieldDefaultCategoryID, v))
}

// DefaultCategoryIDIn applies the In predicate on the "default_category_id" field.
func DefaultCategoryIDIn(vs ...string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldIn(FieldDefaultCategoryID, vs...))
}

// DefaultCategoryIDNotIn applies the NotIn predicate on the "default_category_id" field.
func DefaultCategoryIDNotIn(vs ...string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNotIn(FieldDefaultCategoryID, vs...))
}

// DefaultCategoryIDGT applies the GT predicate on the "default_category_id" field.
func DefaultCategoryIDGT(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGT(FieldDefaultCategoryID, v))
}

// DefaultCategoryIDGTE applies the GTE predicate on the "default_category_id" field.
func DefaultCategoryIDGTE(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGTE(FieldDefaultCategoryID, v))
}

// DefaultCategoryIDLT applies the LT predicate on the "default_category_id" field.
func DefaultCategoryIDLT(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLT(FieldDefaultCategoryID, v))
}

// DefaultCategoryIDLTE applies the LTE predicate on the "default_category_id" field.
func DefaultCategoryIDLTE(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLTE(FieldDefaultCategoryID, v))
}

// DefaultCategoryIDContains applies the Contains predicate on the "default_category_id" field.
func DefaultCategoryIDContains(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldContains(FieldDefaultCategoryID, v))
}

// DefaultCategoryIDHasPrefix applies the HasPrefix predicate on the "default_category_id" field.
func DefaultCategoryIDHasPrefix(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldHasPrefix(FieldDefaultCategoryID, v))
}

// DefaultCategoryIDHasSuffix applies the HasSuffix predicate on the "default_category_id" field.
func DefaultCategoryIDHasSuffix(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldHasSuffix(FieldDefaultCategoryID, v))
}

// DefaultCategoryIDEqualFold applies the EqualFold predicate on the "default_category_id" field.
func DefaultCategoryIDEqualFold(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEqualFold(FieldDefaultCategoryID, v))
}

// DefaultCategoryIDContainsFold applies the ContainsFold predicate on the "default_category_id" field.
func DefaultCategoryIDContainsFold(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldContainsFold(FieldDefaultCategoryID, v))
}

// DescriptionTemplateEQ applies the EQ predicate on the "description_template" field.
func DescriptionTemplateEQ(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldDescriptionTemplate, v))
}

// DescriptionTemplateNEQ applies the NEQ predicate on the "description_template" field.
func DescriptionTemplateNEQ(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNEQ(FieldDescriptionTemplate, v))
}

// DescriptionTemplateIn applies the In predicate on the "description_template" field.
func DescriptionTemplateIn(vs ...string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldIn(FieldDescriptionTemplate, vs...))
}

// DescriptionTemplateNotIn applies the NotIn predicate on the "description_template" field.
func DescriptionTemplateNotIn(vs ...string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNotIn(FieldDescriptionTemplate, vs...))
}

// DescriptionTemplateGT applies the GT predicate on the "description_template" field.
func DescriptionTemplateGT(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGT(FieldDescriptionTemplate, v))
}

// DescriptionTemplateGTE applies the GTE predicate on the "description_template" field.
func DescriptionTemplateGTE(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGTE(FieldDescriptionTemplate, v))
}

// DescriptionTemplateLT applies the LT predicate on the "description_template" field.
func DescriptionTemplateLT(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLT(FieldDescriptionTemplate, v))
}

// DescriptionTemplateLTE applies the LTE predicate on the "description_template" field.
func DescriptionTemplateLTE(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLTE(FieldDescriptionTemplate, v))
}

// DescriptionTemplateContains applies the Contains predicate on the "description_template" field.
func DescriptionTemplateContains(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldContains(FieldDescriptionTemplate, v))
}

// DescriptionTemplateHasPrefix applies the HasPrefix predicate on the "description_template" field.
func DescriptionTemplateHasPrefix(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldHasPrefix(FieldDescriptionTemplate, v))
}

// DescriptionTemplateHasSuffix applies the HasSuffix predicate on the "description_template" field.
func DescriptionTemplateHasSuffix(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldHasSuffix(FieldDescriptionTemplate, v))
}

// DescriptionTemplateIsNil applies the IsNil predicate on the "description_template" field.
func DescriptionTemplateIsNil() predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldIsNull(FieldDescriptionTemplate))
}

// DescriptionTemplateNotNil applies the NotNil predicate on the "description_template" field.
func DescriptionTemplateNotNil() predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNotNull(FieldDescriptionTemplate))
}

// DescriptionTemplateEqualFold applies the EqualFold predicate on the "description_template" field.
func DescriptionTemplateEqualFold(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEqualFold(FieldDescriptionTemplate, v))
}

// DescriptionTemplateContainsFold applies the ContainsFold predicate on the "description_template" field.
func DescriptionTemplateContainsFold(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldContainsFold(FieldDescriptionTemplate, v))
}

// TitleTemplateEQ applies the EQ predicate on the "title_template" field.
func TitleTemplateEQ(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldTitleTemplate, v))
}

// TitleTemplateNEQ applies the NEQ predicate on the "title_template" field.
func TitleTemplateNEQ(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNEQ(FieldTitleTemplate, v))
}

// TitleTemplateIn applies the In predicate on the "title_template" field.
func TitleTemplateIn(vs ...string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldIn(FieldTitleTemplate, vs...))
}

// TitleTemplateNotIn applies the NotIn predicate on the "title_template" field.
func TitleTemplateNotIn(vs ...string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNotIn(FieldTitleTemplate, vs...))
}

// TitleTemplateGT applies the GT predicate on the "title_template" field.
func TitleTemplateGT(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGT(FieldTitleTemplate, v))
}

// TitleTemplateGTE applies the GTE predicate on the "title_template" field.
func TitleTemplateGTE(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGTE(FieldTitleTemplate, v))
}

// TitleTemplateLT applies the LT predicate on the "title_template" field.
func TitleTemplateLT(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLT(FieldTitleTemplate, v))
}

// TitleTemplateLTE applies the LTE predicate on the "title_template" field.
func TitleTemplateLTE(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLTE(FieldTitleTemplate, v))
}

// TitleTemplateContains applies the Contains predicate on the "title_template" field.
func TitleTemplateContains(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldContains(FieldTitleTemplate, v))
}

// TitleTemplateHasPrefix applies the HasPrefix predicate on the "title_template" field.
func TitleTemplateHasPrefix(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldHasPrefix(FieldTitleTemplate, v))
}

// TitleTemplateHasSuffix applies the HasSuffix predicate on the "title_template" field.
func TitleTemplateHasSuffix(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldHasSuffix(FieldTitleTemplate, v))
}

// TitleTemplateIsNil applies the IsNil predicate on the "title_template" field.
func TitleTemplateIsNil() predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldIsNull(FieldTitleTemplate))
}

// TitleTemplateNotNil applies the NotNil predicate on the "title_template" field.
func TitleTemplateNotNil() predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNotNull(FieldTitleTemplate))
}

// TitleTemplateEqualFold applies the EqualFold predicate on the "title_template" field.
func TitleTemplateEqualFold(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEqualFold(FieldTitleTemplate, v))
}

// TitleTemplateContainsFold applies the ContainsFold predicate on the "title_template" field.
func TitleTemplateContainsFold(v string) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldContainsFold(FieldTitleTemplate, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNotNull(FieldTags))
}

// AddChaptersEQ applies the EQ predicate on the "add_chapters" field.
func AddChaptersEQ(v bool) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldAddChapters, v))
}

// AddChaptersNEQ applies the NEQ predicate on the "add_chapters" field.
func AddChaptersNEQ(v bool) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNEQ(FieldAddChapters, v))
}

// NotifySubscribersEQ applies the EQ predicate on the "notify_subscribers" field.
func NotifySubscribersEQ(v bool) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldNotifySubscribers, v))
}

// NotifySubscribersNEQ applies the NEQ predicate on the "notify_subscribers" field.
func NotifySubscribersNEQ(v bool) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNEQ(FieldNotifySubscribers, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.YoutubeConfig {
	return predicate.YoutubeConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlaylistMappings applies the HasEdge predicate on the "playlist_mappings" edge.
func HasPlaylistMappings() predicate.YoutubeConfig {
	return predicate.YoutubeConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlaylistMappingsTable, PlaylistMappingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlaylistMappingsWith applies the HasEdge predicate on the "playlist_mappings" edge with a given conditions (other predicates).
func HasPlaylistMappingsWith(preds ...predicate.YoutubePlaylistMapping) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(func(s *sql.Selector) {
		step := newPlaylistMappingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.YoutubeConfig) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.YoutubeConfig) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.YoutubeConfig) predicate.YoutubeConfig {
	return predicate.YoutubeConfig(sql.NotPredicates(p))
}
