// Code generated by ent, DO NOT EDIT.

package youtubeconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the youtubeconfig type in the database.
	Label = "youtube_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUploadEnabled holds the string denoting the upload_enabled field in the database.
	FieldUploadEnabled = "upload_enabled"
	// FieldDefaultPrivacy holds the string denoting the default_privacy field in the database.
	FieldDefaultPrivacy = "default_privacy"
	// FieldDefaultCategoryID holds the string denoting the default_category_id field in the database.
	FieldDefaultCategoryID = "default_category_id"
	// FieldDescriptionTemplate holds the string denoting the description_template field in the database.
	FieldDescriptionTemplate = "description_template"
	// FieldTitleTemplate holds the string denoting the title_template field in the database.
	FieldTitleTemplate = "title_template"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldAddChapters holds the string denoting the add_chapters field in the database.
	FieldAddChapters = "add_chapters"
	// FieldNotifySubscribers holds the string denoting the notify_subscribers field in the database.
	FieldNotifySubscribers = "notify_subscribers"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// EdgePlaylistMappings holds the string denoting the playlist_mappings edge name in mutations.
	EdgePlaylistMappings = "playlist_mappings"
	// Table holds the table name of the youtubeconfig in the database.
	Table = "youtube_configs"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "youtube_configs"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_youtube_config"
	// PlaylistMappingsTable is the table that holds the playlist_mappings relation/edge.
	PlaylistMappingsTable = "youtube_playlist_mappings"
	// PlaylistMappingsInverseTable is the table name for the YoutubePlaylistMapping entity.
	// It exists in this package in order to avoid circular dependency with the "youtubeplaylistmapping" package.
	PlaylistMappingsInverseTable = "youtube_playlist_mappings"
	// PlaylistMappingsColumn is the table column denoting the playlist_mappings relation/edge.
	PlaylistMappingsColumn = "youtube_config_playlist_mappings"
)

// Columns holds all SQL columns for youtubeconfig fields.
var Columns = []string{
	FieldID,
	FieldUploadEnabled,
	FieldDefaultPrivacy,
	FieldDefaultCategoryID,
	FieldDescriptionTemplate,
	FieldTitleTemplate,
	FieldTags,
	FieldAddChapters,
	FieldNotifySubscribers,
	FieldUpdatedAt,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "youtube_configs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"channel_youtube_config",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUploadEnabled holds the default value on creation for the "upload_enabled" field.
	DefaultUploadEnabled bool
	// DefaultDefaultPrivacy holds the default value on creation for the "default_privacy" field.
	DefaultDefaultPrivacy string
	// DefaultDefaultCategoryID holds the default value on creation for the "default_category_id" field.
	DefaultDefaultCategoryID string
	// DefaultAddChapters holds the default value on creation for the "add_chapters" field.
	DefaultAddChapters bool
	// DefaultNotifySubscribers holds the default value on creation for the "notify_subscribers" field.
	DefaultNotifySubscribers bool
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the YoutubeConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUploadEnabled orders the results by the upload_enabled field.
func ByUploadEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadEnabled, opts...).ToFunc()
}

// ByDefaultPrivacy orders the results by the default_privacy field.
func ByDefaultPrivacy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultPrivacy, opts...).ToFunc()
}

// ByDefaultCategoryID orders the results by the default_category_id field.
func ByDefaultCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultCategoryID, opts...).ToFunc()
}

// ByDescriptionTemplate orders the results by the description_template field.
func ByDescriptionTemplate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescriptionTemplate, opts...).ToFunc()
}

// ByTitleTemplate orders the results by the title_template field.
func ByTitleTemplate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleTemplate, opts...).ToFunc()
}

// ByAddChapters orders the results by the add_chapters field.
func ByAddChapters(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddChapters, opts...).ToFunc()
}

// ByNotifySubscribers orders the results by the notify_subscribers field.
func ByNotifySubscribers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifySubscribers, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}

// ByPlaylistMappingsCount orders the results by playlist_mappings count.
func ByPlaylistMappingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlaylistMappingsStep(), opts...)
	}
}

// ByPlaylistMappings orders the results by playlist_mappings terms.
func ByPlaylistMappings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlaylistMappingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, ChannelTable, ChannelColumn),
	)
}
func newPlaylistMappingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlaylistMappingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PlaylistMappingsTable, PlaylistMappingsColumn),
	)
}
